# Generated by Django 5.1.15 on 2026-10-04 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(default='', max_length=20)),
                ('delivery_method', models.CharField(default='PICKUP', max_length=20)),
                ('city', models.CharField(default='Yaoundé', max_length=50)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('authorized_pickup_name', models.CharField(blank=True, default='', max_length=120)),
                ('authorized_pickup_phone', models.CharField(blank=True, default='', max_length=20)),
                ('payment_status', models.CharField(default='PENDING', max_length=20)),
                ('fulfillment_status', models.CharField(default='CREATED', max_length=30)),
                ('subtotal_xaf', models.PositiveIntegerField(default=0)),
                ('delivery_fee_xaf', models.PositiveIntegerField(default=0)),
                ('total_xaf', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relay_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.relaypointprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_snapshot', models.CharField(max_length=200)),
                ('price_xaf_snapshot', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('line_total_xaf', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
        ),
    ]
