# backend/apps/whatsapp_assistant/conversation/texts.py
# Tous les textes de l'assistant, en français et en anglais.
# Mise en forme WhatsApp : *gras*, _italique_, ~barré~.
# Boutons : 20 caractères maximum. Lignes de liste : 24 (titre) / 72 (description).

TEXTS = {
    "fr": {
        "welcome": "Bonjour{name} 👋 Je suis *{assistant}*, votre assistant shopping.\nQue souhaitez-vous faire ?",
        "welcome_footer": "Écrivez « menu » à tout moment",
        "btn_shop": "🛍️ Acheter",
        "btn_search": "🔎 Rechercher",
        "btn_help": "💬 Aide",
        "btn_menu": "🏠 Menu",
        "btn_categories": "📂 Catégories",
        "btn_next": "➡️ Suivant",
        "btn_list": "📋 Liste",
        "categories_body": "Choisissez une catégorie 👇",
        "categories_button": "Voir les catégories",
        "categories_section": "Catégories",
        "subcategories_body": "*{name}* : choisissez une sous-catégorie 👇",
        "subcategories_button": "Voir le choix",
        "row_all": "Tout voir",
        "row_all_desc": "Tous les articles de {name}",
        "row_back": "↩️ Retour",
        "row_back_desc": "Catégorie précédente",
        "row_more": "➡️ Voir plus",
        "row_more_desc": "Page suivante",
        "children_count": "{count} sous-catégories",
        "children_one": "1 sous-catégorie",
        "articles_count": "{count} articles",
        "article_one": "1 article",
        "coming_soon": "Bientôt disponible",
        "no_categories": "La boutique se remplit : aucun article en vente pour le moment. Revenez très vite 🙂",
        "catalog_unavailable": "⏳ Le catalogue est momentanément indisponible. Réessayez dans un instant.",
        "products_body": "*{title}* · {count} article{s} 👇\nTouchez un article pour voir sa photo et son prix.",
        "products_button": "Voir les articles",
        "products_section": "Articles",
        "no_products": "Il n'y a pas encore d'article dans *{name}*. Les vendeurs en ajoutent chaque jour 🙂",
        "last_product": "C'était le dernier article de la liste.",
        "rating": "⭐ {rating}/5 ({reviews} avis)",
        "shop": "🏪 {shop}",
        "btn_buy": "Acheter sur BelivaY",
        "secure_checkout": "Paiement Mobile Money sécurisé",
        "what_next": "👆 Touchez *Acheter sur BelivaY* pour commander : panier, livraison et paiement se font dans l'application.\nOu continuez à parcourir :",
        "not_buyable": "🕓 _Bientôt disponible à l'achat en ligne._",
        "search_prompt": "🔎 Tapez le nom de l'article recherché, par exemple *robe wax* ou *casque bluetooth*.",
        "search_title": "Résultats « {query} »",
        "search_fuzzy": "_Orthographe corrigée pour vous._",
        "search_related": "_Rien d'exact : voici des articles proches._",
        "search_empty": "😕 Aucun article trouvé pour « {query} ».\nEssayez un autre mot, ou parcourez les catégories.",
        "help": "💬 *Besoin d'aide ?*\nNotre équipe vous répond :\n📞 {phone} (appel ou WhatsApp)\n✉️ {email}\n\nÀ tout moment, écrivez *menu* pour revenir à l'accueil ou *langue* pour changer de langue.",
        "unsupported": "Je ne sais pas encore lire ce type de message 🙈\nUtilisez les boutons, ou écrivez le nom d'un article.",

        # ── Livreurs ──
        "template_mission": "Nouvelle mission {ref}",
        "template_tour": "Récapitulatif · {tour}",
        "tour_label": "Tournée {zone}, {date} {period}",
        "period_MORNING": "matin",
        "period_AFTERNOON": "après-midi",
        "relay_prefix": "Point relais",
        "status_to_accept": "🕓 À accepter",
        "status_ASSIGNED": "✅ Acceptée",
        "status_PICKED_UP": "📦 Colis ramassé",
        "status_IN_TRANSIT": "🚚 En route",
        "status_OUT_FOR_DELIVERY": "🏁 En livraison",
        "status_other": "Statut : {status}",
        "mission_title": "📦 *Mission {ref}*\n{status} · {items} article{s}",
        "mission_stop": "Arrêt n° {number} de la tournée",
        "pickup_title": "*1️⃣ Ramassage*",
        "home_title": "*2️⃣ Livraison à domicile*",
        "relay_title": "*2️⃣ Dépôt au point relais*",
        "line_landmarks": "🧭 Repères : {value}",
        "line_hint": "💡 {value}",
        "line_note": "📝 Note du client : {value}",
        "line_hours": "🕘 Horaires : {value}",
        "line_shop_phone": "📞 Boutique : {value}",
        "line_relay_phone": "📞 Point relais : {value}",
        "line_no_pin": "_Position GPS non renseignée._",
        "privacy_note": "🔒 Le vendeur vous remet le code de remise au ramassage. Le contact du client reste dans l'application livreur.",
        "pin_pickup": "Ramassage · {name}",
        "pin_delivery": "Livraison · {ref}",
        "mission_actions": "Que voulez-vous faire ?",
        "btn_accept": "✅ Accepter",
        "btn_addresses": "📍 Adresses",
        "btn_my_missions": "📋 Mes missions",
        "accepted": "✅ *Mission {ref} acceptée.*\nDirection {pickup} pour le ramassage. Bonne route ! 🛵",
        "already_accepted": "✅ La mission {ref} est déjà acceptée.",
        "not_yours": "Cette mission ne vous est pas (ou plus) attribuée. Vos missions à jour sont dans l'application livreur.",
        "unavailable": "La mission {ref} n'attend plus d'acceptation ({status}).",
        "finished": "La mission {ref} est terminée ({status}) : ses adresses ne sont plus affichées.",
        "inactive": "Votre compte livreur n'est pas actif pour le moment. Contactez le support : {phone}.",
        "not_courier": "Ce bouton est réservé aux livreurs BelivaY.",
        "missions_body": "📋 *Vos missions en cours : {count}*\nTouchez une mission pour voir ses adresses.",
        "missions_button": "Mes missions",
        "missions_section": "Missions",
        "missions_empty": "Vous n'avez aucune mission en cours. Les nouvelles missions arrivent ici dès qu'elles vous sont assignées 🛵",
        "tour_body": "🗺️ *{tour}* · {count} colis\nDans l'ordre de passage :\n{lines}\n\nTouchez un arrêt pour ses adresses et sa position.",
        "tour_button": "Voir les arrêts",
        "tour_section": "Arrêts",
        "tour_row": "Arrêt {number} · {ref}",
    },
    "en": {
        "welcome": "Hello{name} 👋 I'm *{assistant}*, your shopping assistant.\nWhat would you like to do?",
        "welcome_footer": "Type « menu » at any time",
        "btn_shop": "🛍️ Shop",
        "btn_search": "🔎 Search",
        "btn_help": "💬 Help",
        "btn_menu": "🏠 Menu",
        "btn_categories": "📂 Categories",
        "btn_next": "➡️ Next",
        "btn_list": "📋 List",
        "categories_body": "Choose a category 👇",
        "categories_button": "See categories",
        "categories_section": "Categories",
        "subcategories_body": "*{name}*: choose a sub-category 👇",
        "subcategories_button": "See options",
        "row_all": "See all",
        "row_all_desc": "All items in {name}",
        "row_back": "↩️ Back",
        "row_back_desc": "Previous category",
        "row_more": "➡️ See more",
        "row_more_desc": "Next page",
        "children_count": "{count} sub-categories",
        "children_one": "1 sub-category",
        "articles_count": "{count} items",
        "article_one": "1 item",
        "coming_soon": "Coming soon",
        "no_categories": "The shop is filling up: no items on sale yet. Come back soon 🙂",
        "catalog_unavailable": "⏳ The catalogue is temporarily unavailable. Please try again in a moment.",
        "products_body": "*{title}* · {count} item{s} 👇\nTap an item to see its photo and price.",
        "products_button": "See items",
        "products_section": "Items",
        "no_products": "There are no items in *{name}* yet. Sellers add new ones every day 🙂",
        "last_product": "That was the last item in the list.",
        "rating": "⭐ {rating}/5 ({reviews} reviews)",
        "shop": "🏪 {shop}",
        "btn_buy": "Buy on BelivaY",
        "secure_checkout": "Secure Mobile Money payment",
        "what_next": "👆 Tap *Buy on BelivaY* to order: cart, delivery and payment happen in the app.\nOr keep browsing:",
        "not_buyable": "🕓 _Available to buy online soon._",
        "search_prompt": "🔎 Type the name of the item you're looking for, e.g. *wax dress* or *bluetooth headset*.",
        "search_title": "Results « {query} »",
        "search_fuzzy": "_Spelling corrected for you._",
        "search_related": "_No exact match: here are similar items._",
        "search_empty": "😕 No item found for « {query} ».\nTry another word, or browse the categories.",
        "help": "💬 *Need help?*\nOur team is here for you:\n📞 {phone} (call or WhatsApp)\n✉️ {email}\n\nAt any time, type *menu* to go back home or *language* to switch language.",
        "unsupported": "I can't read this type of message yet 🙈\nUse the buttons, or type the name of an item.",

        # ── Couriers ──
        "template_mission": "New job {ref}",
        "template_tour": "Summary · {tour}",
        "tour_label": "{zone} round, {date} {period}",
        "period_MORNING": "morning",
        "period_AFTERNOON": "afternoon",
        "relay_prefix": "Relay point",
        "status_to_accept": "🕓 To accept",
        "status_ASSIGNED": "✅ Accepted",
        "status_PICKED_UP": "📦 Picked up",
        "status_IN_TRANSIT": "🚚 On the way",
        "status_OUT_FOR_DELIVERY": "🏁 Out for delivery",
        "status_other": "Status: {status}",
        "mission_title": "📦 *Job {ref}*\n{status} · {items} item{s}",
        "mission_stop": "Stop no. {number} of the round",
        "pickup_title": "*1️⃣ Pickup*",
        "home_title": "*2️⃣ Home delivery*",
        "relay_title": "*2️⃣ Drop-off at relay point*",
        "line_landmarks": "🧭 Landmarks: {value}",
        "line_hint": "💡 {value}",
        "line_note": "📝 Customer note: {value}",
        "line_hours": "🕘 Opening hours: {value}",
        "line_shop_phone": "📞 Shop: {value}",
        "line_relay_phone": "📞 Relay point: {value}",
        "line_no_pin": "_No GPS position provided._",
        "privacy_note": "🔒 The seller gives you the handover code at pickup. The customer's contact stays in the courier app.",
        "pin_pickup": "Pickup · {name}",
        "pin_delivery": "Drop-off · {ref}",
        "mission_actions": "What would you like to do?",
        "btn_accept": "✅ Accept",
        "btn_addresses": "📍 Addresses",
        "btn_my_missions": "📋 My jobs",
        "accepted": "✅ *Job {ref} accepted.*\nHead to {pickup} for the pickup. Safe ride! 🛵",
        "already_accepted": "✅ Job {ref} is already accepted.",
        "not_yours": "This job is not (or no longer) assigned to you. Your up-to-date jobs are in the courier app.",
        "unavailable": "Job {ref} is no longer waiting for acceptance ({status}).",
        "finished": "Job {ref} is finished ({status}): its addresses are no longer shown.",
        "inactive": "Your courier account is not active at the moment. Contact support: {phone}.",
        "not_courier": "This button is for BelivaY couriers only.",
        "missions_body": "📋 *Your current jobs: {count}*\nTap a job to see its addresses.",
        "missions_button": "My jobs",
        "missions_section": "Jobs",
        "missions_empty": "You have no current job. New jobs arrive here as soon as they are assigned to you 🛵",
        "tour_body": "🗺️ *{tour}* · {count} parcels\nIn route order:\n{lines}\n\nTap a stop for its addresses and location.",
        "tour_button": "See the stops",
        "tour_section": "Stops",
        "tour_row": "Stop {number} · {ref}",
    },
}

# Avant le choix de la langue, l'assistant parle les deux.
LANGUAGE_PROMPT = (
    "👋 Bienvenue chez *{assistant}* ! Choisissez votre langue.\n_Welcome to {assistant}! Please choose your language._"
)


def t(language: str, key: str, **values) -> str:
    table = TEXTS.get(language) or TEXTS["fr"]
    return table[key].format(**values)


def price(amount: int) -> str:
    """18500 → « 18 500 FCFA »."""
    return f"{amount:,}".replace(",", " ") + " FCFA"
