# backend/apps/whatsapp_assistant/conversation/texts.py
# Tous les textes de l'assistant, en français et en anglais.
# Mise en forme WhatsApp : *gras*, _italique_, ~barré~.
# Boutons : 20 caractères maximum. Lignes de liste : 24 (titre) / 72 (description).

TEXTS = {
    "fr": {
        "welcome": "Bonjour{name} 👋 Je suis *{assistant}*, votre assistant shopping.\nQue souhaitez-vous faire ?",
        "welcome_footer": "« menu » ou « ma commande » à tout moment",
        "btn_shop": "🛍️ Acheter",
        "btn_search": "🔎 Rechercher",
        "btn_help": "💬 Aide",
        "btn_menu": "🏠 Menu",
        "btn_categories": "📂 Catégories",
        "btn_next": "➡️ Suivant",
        "btn_list": "📋 Liste",
        "categories_body": "Choisissez une catégorie 👇",
        "categories_button": "Voir les catégories",
        "categories_section": "Catégories",
        "subcategories_body": "*{name}* : choisissez une sous-catégorie 👇",
        "subcategories_button": "Voir le choix",
        "row_all": "Tout voir",
        "row_all_desc": "Tous les articles de {name}",
        "row_back": "↩️ Retour",
        "row_back_desc": "Catégorie précédente",
        "row_more": "➡️ Voir plus",
        "row_more_desc": "Page suivante",
        "children_count": "{count} sous-catégories",
        "children_one": "1 sous-catégorie",
        "articles_count": "{count} articles",
        "article_one": "1 article",
        "coming_soon": "Bientôt disponible",
        "no_categories": "La boutique se remplit : aucun article en vente pour le moment. Revenez très vite 🙂",
        "catalog_unavailable": "⏳ Le catalogue est momentanément indisponible. Réessayez dans un instant.",
        "products_body": "*{title}* · {count} article{s} 👇\nTouchez un article pour voir sa photo et son prix.",
        "products_button": "Voir les articles",
        "products_section": "Articles",
        "no_products": "Il n'y a pas encore d'article dans *{name}*. Les vendeurs en ajoutent chaque jour 🙂",
        "last_product": "C'était le dernier article de la liste.",
        "rating": "⭐ {rating}/5 ({reviews} avis)",
        "shop": "🏪 {shop}",
        "btn_buy": "Acheter sur BelivaY",
        "secure_checkout": "Paiement Mobile Money sécurisé",
        "what_next": "👆 Touchez *Acheter sur BelivaY* pour commander : panier, livraison et paiement se font dans l'application.\nOu continuez à parcourir :",
        "not_buyable": "🕓 _Bientôt disponible à l'achat en ligne._",
        "search_prompt": "🔎 Tapez le nom de l'article recherché, par exemple *robe wax* ou *casque bluetooth*.",
        "search_title": "Résultats « {query} »",
        "search_fuzzy": "_Orthographe corrigée pour vous._",
        "search_related": "_Rien d'exact : voici des articles proches._",
        "search_empty": "😕 Aucun article trouvé pour « {query} ».\nEssayez un autre mot, ou parcourez les catégories.",
        "help": "💬 *Besoin d'aide ?*\nNotre équipe vous répond :\n📞 {phone} (appel ou WhatsApp)\n✉️ {email}\n\nÀ tout moment, écrivez *menu* pour revenir à l'accueil ou *langue* pour changer de langue.",
        "unsupported": "Je ne sais pas encore lire ce type de message 🙈\nUtilisez les boutons, ou écrivez le nom d'un article.",

        # ── Livreurs ──
        "template_mission": "Nouvelle mission {ref}",
        "template_tour": "Récapitulatif · {tour}",
        "tour_label": "Tournée {zone}, {date} {period}",
        "period_MORNING": "matin",
        "period_AFTERNOON": "après-midi",
        "relay_prefix": "Point relais",
        "status_to_accept": "🕓 À accepter",
        "status_ASSIGNED": "✅ Acceptée",
        "status_PICKED_UP": "📦 Colis ramassé",
        "status_IN_TRANSIT": "🚚 En route",
        "status_OUT_FOR_DELIVERY": "🏁 En livraison",
        "status_other": "Statut : {status}",
        "mission_title": "📦 *Mission {ref}*\n{status} · {items} article{s}",
        "mission_stop": "Arrêt n° {number} de la tournée",
        "pickup_title": "*1️⃣ Ramassage*",
        "home_title": "*2️⃣ Livraison à domicile*",
        "relay_title": "*2️⃣ Dépôt au point relais*",
        "line_landmarks": "🧭 Repères : {value}",
        "line_hint": "💡 {value}",
        "line_note": "📝 Note du client : {value}",
        "line_hours": "🕘 Horaires : {value}",
        "line_shop_phone": "📞 Boutique : {value}",
        "line_relay_phone": "📞 Point relais : {value}",
        "line_no_pin": "_Position GPS non renseignée._",
        "privacy_note": "🔒 Le vendeur vous remet le code de remise au ramassage. Le contact du client reste dans l'application livreur.",
        "pin_pickup": "Ramassage · {name}",
        "pin_delivery": "Livraison · {ref}",
        "mission_actions": "Que voulez-vous faire ?",
        "btn_accept": "✅ Accepter",
        "btn_addresses": "📍 Adresses",
        "btn_my_missions": "📋 Mes missions",
        "accepted": "✅ *Mission {ref} acceptée.*\nDirection {pickup} pour le ramassage. Bonne route ! 🛵",
        "already_accepted": "✅ La mission {ref} est déjà acceptée.",
        "not_yours": "Cette mission ne vous est pas (ou plus) attribuée. Vos missions à jour sont dans l'application livreur.",
        "unavailable": "La mission {ref} n'attend plus d'acceptation ({status}).",
        "finished": "La mission {ref} est terminée ({status}) : ses adresses ne sont plus affichées.",
        "inactive": "Votre compte livreur n'est pas actif pour le moment. Contactez le support : {phone}.",
        "not_courier": "Ce bouton est réservé aux livreurs BelivaY.",
        "missions_body": "📋 *Vos missions en cours : {count}*\nTouchez une mission pour voir ses adresses.",
        "missions_button": "Mes missions",
        "missions_section": "Missions",
        "missions_empty": "Vous n'avez aucune mission en cours. Les nouvelles missions arrivent ici dès qu'elles vous sont assignées 🛵",
        "tour_body": "🗺️ *{tour}* · {count} colis\nDans l'ordre de passage :\n{lines}\n\nTouchez un arrêt pour ses adresses et sa position.",
        "tour_button": "Voir les arrêts",
        "tour_section": "Arrêts",
        "tour_row": "Arrêt {number} · {ref}",

        # ── Suivi de commande (client) ──
        "orders_body": "📦 *Vos commandes : {count}*\nTouchez-en une pour voir où elle en est.",
        "orders_button": "Mes commandes",
        "orders_section": "Commandes",
        "orders_row": "{ref} · {date}",
        "orders_empty": "🔍 Je ne trouve aucune commande à ce numéro.\nSi vous avez commandé avec un autre numéro, ouvrez l'application : tout y est.\nBesoin d'aide ? Écrivez *aide*.",
        "order_title": "📦 *Commande {ref}* · passée le {date}",
        "order_items": "🛒 *Vos articles*",
        "order_item_line": "• {title} × {qty}",
        "order_total": "💰 Total : *{total}*",
        "order_delivery_fee": "_dont {fee} de livraison_",
        "order_unpaid": "⏳ *Paiement non finalisé.*\nTouchez le bouton ci-dessous pour régler par Mobile Money et lancer la livraison.",
        "order_home": "🏡 *Livraison à* {place}",
        "order_relay": "🏪 *À retirer au point relais* {place}",
        "order_parcels": "🚚 *Suivi du colis*",
        "order_parcels_many": "🚚 *Suivi de vos {count} colis*",
        "order_parcel_line": "• {ref}{shop} — {status}",
        "order_parcel_shop": " · {shop}",
        "order_eta": "   🕓 Attendu le {eta}",
        "order_no_parcel": "_Le colis sera confié à un livreur dès que le vendeur l'aura préparé._",
        "order_privacy": "🔒 Le code de réception reste dans l'application : ne le donnez qu'au livreur, à la remise.",
        "order_actions": "Que voulez-vous faire ?",
        "btn_orders": "📦 Mes commandes",
        "btn_open_app": "Ouvrir l'application",
        "btn_pay": "💳 Payer ma commande",
        "parcel_CREATED": "⏳ En attente du vendeur",
        "parcel_WAITING_MANUAL_ASSIGNMENT": "⏳ Recherche d'un livreur",
        "parcel_ASSIGNED": "🛵 Livreur assigné",
        "parcel_PICKED_UP": "📦 Ramassé chez le vendeur",
        "parcel_IN_TRANSIT": "🚚 En route",
        "parcel_OUT_FOR_DELIVERY": "🏁 En cours de livraison",
        "parcel_DELIVERED": "✅ Livré",
        "parcel_INCIDENT": "⚠️ Incident signalé",
        "parcel_FAILED": "❌ Livraison échouée",
        "parcel_CANCELLED": "❌ Annulé",
        "order_CREATED": "⏳ En attente de paiement",
        "order_PAID_IN_ESCROW": "🔒 Payée · fonds sécurisés",
        "order_VENDOR_ACKNOWLEDGED": "👍 Confirmée par le vendeur",
        "order_PREPARING": "🛠️ En préparation",
        "order_READY_FOR_PICKUP": "📦 Prête à partir",
        "order_DRIVER_ASSIGNED": "🛵 Livreur assigné",
        "order_PICKED_UP": "🚚 Prise en charge",
        "order_OUT_FOR_DELIVERY": "🏁 En cours de livraison",
        "order_DELIVERED": "✅ Livrée",
        "order_BUYER_CONFIRMED": "✅ Réception confirmée",
        "order_AUTO_CONFIRMED": "✅ Réception confirmée",
        "order_RELEASED_TO_VENDOR": "✅ Terminée",
        "order_DISPUTED": "⚠️ Litige en cours",
        "order_CANCELLED": "❌ Annulée",
        "order_REFUNDED": "↩️ Remboursée",
        "order_status_other": "Statut : {status}",

        # ── Vendeur ──
        "template_order": "Nouvelle commande {ref}",
        "sales_body": "🏪 *{count} commandes à préparer*\nTouchez-en une pour la traiter.",
        "sales_button": "À préparer",
        "sales_section": "Commandes",
        "sales_row": "{ref} · {total}",
        "sales_empty": "✅ Aucune commande en attente. Vous êtes à jour !\nLes nouvelles commandes payées arrivent ici automatiquement.",
        "not_vendor": "Ce bouton est réservé aux vendeurs BelivaY.",
        "sale_title": "🏪 *Commande {ref}* · {date}",
        "sale_buyer": "👤 Acheteur {buyer} · {city}",
        "sale_relay": "🏪 Remise au point relais",
        "sale_items": "📦 *À préparer*",
        "sale_item_line": "• {title} × {qty}",
        "sale_total": "💰 Votre part : *{total}*",
        "sale_deadline": "🕓 À préparer avant le *{deadline}*",
        "sale_late": "⚠️ *En retard* — le délai de préparation est dépassé.",
        "sale_code": "🔑 Le code de remise est dans votre application : donnez-le au livreur, en main propre.",
        "sale_actions": "Que voulez-vous faire ?",
        "btn_ack": "✅ Je confirme",
        "btn_ready": "📦 Colis prêt",
        "btn_sales": "🏪 À préparer",
        "sale_acknowledged": "✅ *Commande {ref} confirmée.*\nPréparez le colis, puis touchez « Colis prêt ».",
        "sale_ready": "📦 *Commande {ref} prête.*\nUn livreur va être assigné pour le ramassage. Merci !",
        "sale_already": "✅ La commande {ref} est déjà à ce stade.",
        "sale_not_yours": "Cette commande ne contient aucun de vos articles.",
        "sale_refused": "La commande {ref} ne peut plus être traitée ici ({status}). Ouvrez votre application.",
        "sale_inactive": "Votre boutique n'est pas active pour le moment. Contactez le support : {phone}.",
        "vendor_PAID_IN_ESCROW": "💰 Payée · à confirmer",
        "vendor_VENDOR_ACKNOWLEDGED": "👍 Confirmée · à préparer",
        "vendor_PREPARING": "🛠️ En préparation",
        "vendor_READY_FOR_PICKUP": "📦 Prête · attend un livreur",
        "vendor_DRIVER_ASSIGNED": "🛵 Livreur assigné",
        "vendor_PICKED_UP": "🚚 Ramassée",
        "vendor_DELIVERED": "✅ Livrée",
        "vendor_CANCELLED": "❌ Annulée",

        # ── Point relais ──
        "template_relay": "Colis en route {ref}",
        "parcels_body": "🏪 *{count} colis à traiter*\nTouchez-en un pour le détail.",
        "parcels_button": "Mes colis",
        "parcels_section": "Colis",
        "parcels_row_in": "📥 {ref}",
        "parcels_row_out": "📤 {ref}",
        "parcels_empty": "✅ Rien à traiter pour le moment.\nLes colis qui partent vers votre relais s'annoncent ici automatiquement.",
        "not_relay": "Ce bouton est réservé aux points relais BelivaY.",
        "parcel_title": "*Colis {ref}* · {status}",
        "parcel_expected": "🚚 En route vers vous · livreur {courier}",
        "parcel_expected_plain": "🚚 En route vers vous",
        "parcel_stored": "📥 Reçu le {date} · emplacement *{slot}*",
        "parcel_items": "Contenu : {count} article{s}",
        "parcel_free_until": "🆓 Garde gratuite jusqu'au *{date}*",
        "parcel_deadline": "🕓 À retirer avant le *{date}*",
        "parcel_fee": "💰 Frais de garde dus : *{fee}*",
        "parcel_late": "⚠️ *Délai dépassé* — le colis doit repartir au vendeur.",
        "parcel_capacity": "📊 Stockage : {stored} colis sur {capacity}",
        "parcel_privacy": "🔒 Le client vous annonce son code au guichet. Ne le communiquez jamais par message.",
        "parcel_actions": "Que voulez-vous faire ?",
        "btn_receive": "📥 Colis reçu",
        "btn_handover": "📤 Remettre",
        "btn_parcels": "🏪 Mes colis",
        "ask_code": "🔑 Tapez le *code de retrait* que le client vous annonce.\nÉcrivez *annuler* pour revenir en arrière.",
        "code_cancelled": "Remise annulée. Rien n'a changé.",
        "relay_received": "📥 *Colis {ref} réceptionné.*\nEmplacement : *{slot}*. Le client vient d'être prévenu qu'il peut venir le retirer.",
        "relay_handed": "📤 *Remise confirmée* — {refs}.\nLa livraison est enregistrée. Merci !",
        "relay_already_received": "✅ Le colis {ref} est déjà réceptionné.",
        "relay_already_handed": "✅ Ce code a déjà servi : le colis a été retiré.",
        "relay_bad_code": "❌ Aucun colis en attente avec ce code chez vous.\nVérifiez auprès du client, puis touchez « Remettre » à nouveau.",
        "relay_full": "📊 Votre stockage est plein. Remettez des colis en attente, ou augmentez votre capacité dans l'application.",
        "relay_needs_app": "👤 Ce colis est retiré par un tiers autorisé : la pièce d'identité doit être enregistrée dans votre application.",
        "relay_not_yours": "Ce colis n'est pas dans votre relais.",
        "relay_refused": "Ce colis ne peut plus être traité ici. Ouvrez votre application.",
        "relay_inactive": "Votre point relais n'est pas actif pour le moment. Contactez le support : {phone}.",
        "relay_EXPECTED": "🚚 Attendu",
        "relay_RECEIVED": "📥 Reçu",
        "relay_STORED": "📦 En attente de retrait",
        "relay_PICKED_UP": "✅ Retiré",
        "relay_REFUSED": "❌ Refusé au contrôle",
        "relay_RETURNED_TO_VENDOR": "↩️ Retourné au vendeur",
        "relay_RETURNED_TO_BELIVAY": "↩️ Retourné à BelivaY",

        # ── Parler à un humain ──
        "btn_human": "💬 Un conseiller",
        "human_ask": "💬 *Dites-nous tout.*\nÉcrivez votre question ou votre problème en un message. Un conseiller BelivaY vous répondra ici même.\n\nÉcrivez *annuler* pour revenir en arrière.",
        "human_ask_email": "✉️ Une dernière chose : votre *adresse e-mail*, pour que nous puissions vous répondre même si WhatsApp ne passe pas.",
        "human_bad_email": "Cette adresse ne semble pas valide. Réessayez, ou écrivez *annuler*.",
        "human_too_short": "Votre message est un peu court. Décrivez ce qui se passe en quelques mots de plus.",
        "human_cancelled": "Demande annulée. Je reste à votre disposition 🙂",
        "human_sent": "✅ *Votre demande est transmise* (n° {ref}).\nUn conseiller BelivaY vous répond ici, dans cette conversation.\n\nJe me mets en retrait le temps qu'il vous réponde. Écrivez *menu* si vous préférez reprendre avec moi.",
        "human_failed": "😕 Je n'arrive pas à transmettre votre demande pour le moment.\nAppelez-nous au {phone} ou écrivez à {email}.",
        "human_back": "👋 Me revoilà ! Que souhaitez-vous faire ?",
    },
    "en": {
        "welcome": "Hello{name} 👋 I'm *{assistant}*, your shopping assistant.\nWhat would you like to do?",
        "welcome_footer": "« menu » or « my order » at any time",
        "btn_shop": "🛍️ Shop",
        "btn_search": "🔎 Search",
        "btn_help": "💬 Help",
        "btn_menu": "🏠 Menu",
        "btn_categories": "📂 Categories",
        "btn_next": "➡️ Next",
        "btn_list": "📋 List",
        "categories_body": "Choose a category 👇",
        "categories_button": "See categories",
        "categories_section": "Categories",
        "subcategories_body": "*{name}*: choose a sub-category 👇",
        "subcategories_button": "See options",
        "row_all": "See all",
        "row_all_desc": "All items in {name}",
        "row_back": "↩️ Back",
        "row_back_desc": "Previous category",
        "row_more": "➡️ See more",
        "row_more_desc": "Next page",
        "children_count": "{count} sub-categories",
        "children_one": "1 sub-category",
        "articles_count": "{count} items",
        "article_one": "1 item",
        "coming_soon": "Coming soon",
        "no_categories": "The shop is filling up: no items on sale yet. Come back soon 🙂",
        "catalog_unavailable": "⏳ The catalogue is temporarily unavailable. Please try again in a moment.",
        "products_body": "*{title}* · {count} item{s} 👇\nTap an item to see its photo and price.",
        "products_button": "See items",
        "products_section": "Items",
        "no_products": "There are no items in *{name}* yet. Sellers add new ones every day 🙂",
        "last_product": "That was the last item in the list.",
        "rating": "⭐ {rating}/5 ({reviews} reviews)",
        "shop": "🏪 {shop}",
        "btn_buy": "Buy on BelivaY",
        "secure_checkout": "Secure Mobile Money payment",
        "what_next": "👆 Tap *Buy on BelivaY* to order: cart, delivery and payment happen in the app.\nOr keep browsing:",
        "not_buyable": "🕓 _Available to buy online soon._",
        "search_prompt": "🔎 Type the name of the item you're looking for, e.g. *wax dress* or *bluetooth headset*.",
        "search_title": "Results « {query} »",
        "search_fuzzy": "_Spelling corrected for you._",
        "search_related": "_No exact match: here are similar items._",
        "search_empty": "😕 No item found for « {query} ».\nTry another word, or browse the categories.",
        "help": "💬 *Need help?*\nOur team is here for you:\n📞 {phone} (call or WhatsApp)\n✉️ {email}\n\nAt any time, type *menu* to go back home or *language* to switch language.",
        "unsupported": "I can't read this type of message yet 🙈\nUse the buttons, or type the name of an item.",

        # ── Couriers ──
        "template_mission": "New job {ref}",
        "template_tour": "Summary · {tour}",
        "tour_label": "{zone} round, {date} {period}",
        "period_MORNING": "morning",
        "period_AFTERNOON": "afternoon",
        "relay_prefix": "Relay point",
        "status_to_accept": "🕓 To accept",
        "status_ASSIGNED": "✅ Accepted",
        "status_PICKED_UP": "📦 Picked up",
        "status_IN_TRANSIT": "🚚 On the way",
        "status_OUT_FOR_DELIVERY": "🏁 Out for delivery",
        "status_other": "Status: {status}",
        "mission_title": "📦 *Job {ref}*\n{status} · {items} item{s}",
        "mission_stop": "Stop no. {number} of the round",
        "pickup_title": "*1️⃣ Pickup*",
        "home_title": "*2️⃣ Home delivery*",
        "relay_title": "*2️⃣ Drop-off at relay point*",
        "line_landmarks": "🧭 Landmarks: {value}",
        "line_hint": "💡 {value}",
        "line_note": "📝 Customer note: {value}",
        "line_hours": "🕘 Opening hours: {value}",
        "line_shop_phone": "📞 Shop: {value}",
        "line_relay_phone": "📞 Relay point: {value}",
        "line_no_pin": "_No GPS position provided._",
        "privacy_note": "🔒 The seller gives you the handover code at pickup. The customer's contact stays in the courier app.",
        "pin_pickup": "Pickup · {name}",
        "pin_delivery": "Drop-off · {ref}",
        "mission_actions": "What would you like to do?",
        "btn_accept": "✅ Accept",
        "btn_addresses": "📍 Addresses",
        "btn_my_missions": "📋 My jobs",
        "accepted": "✅ *Job {ref} accepted.*\nHead to {pickup} for the pickup. Safe ride! 🛵",
        "already_accepted": "✅ Job {ref} is already accepted.",
        "not_yours": "This job is not (or no longer) assigned to you. Your up-to-date jobs are in the courier app.",
        "unavailable": "Job {ref} is no longer waiting for acceptance ({status}).",
        "finished": "Job {ref} is finished ({status}): its addresses are no longer shown.",
        "inactive": "Your courier account is not active at the moment. Contact support: {phone}.",
        "not_courier": "This button is for BelivaY couriers only.",
        "missions_body": "📋 *Your current jobs: {count}*\nTap a job to see its addresses.",
        "missions_button": "My jobs",
        "missions_section": "Jobs",
        "missions_empty": "You have no current job. New jobs arrive here as soon as they are assigned to you 🛵",
        "tour_body": "🗺️ *{tour}* · {count} parcels\nIn route order:\n{lines}\n\nTap a stop for its addresses and location.",
        "tour_button": "See the stops",
        "tour_section": "Stops",
        "tour_row": "Stop {number} · {ref}",

        # ── Order tracking (customer) ──
        "orders_body": "📦 *Your orders: {count}*\nTap one to see where it stands.",
        "orders_button": "My orders",
        "orders_section": "Orders",
        "orders_row": "{ref} · {date}",
        "orders_empty": "🔍 I can't find any order for this number.\nIf you ordered with another number, open the app: everything is there.\nNeed help? Type *help*.",
        "order_title": "📦 *Order {ref}* · placed on {date}",
        "order_items": "🛒 *Your items*",
        "order_item_line": "• {title} × {qty}",
        "order_total": "💰 Total: *{total}*",
        "order_delivery_fee": "_including {fee} delivery_",
        "order_unpaid": "⏳ *Payment not completed.*\nTap the button below to pay with Mobile Money and start the delivery.",
        "order_home": "🏡 *Delivery to* {place}",
        "order_relay": "🏪 *Pick up at relay point* {place}",
        "order_parcels": "🚚 *Parcel tracking*",
        "order_parcels_many": "🚚 *Tracking your {count} parcels*",
        "order_parcel_line": "• {ref}{shop} — {status}",
        "order_parcel_shop": " · {shop}",
        "order_eta": "   🕓 Expected on {eta}",
        "order_no_parcel": "_The parcel will be handed to a courier as soon as the seller has prepared it._",
        "order_privacy": "🔒 The receipt code stays in the app: give it to the courier only, on handover.",
        "order_actions": "What would you like to do?",
        "btn_orders": "📦 My orders",
        "btn_open_app": "Open the app",
        "btn_pay": "💳 Pay my order",
        "parcel_CREATED": "⏳ Waiting for the seller",
        "parcel_WAITING_MANUAL_ASSIGNMENT": "⏳ Looking for a courier",
        "parcel_ASSIGNED": "🛵 Courier assigned",
        "parcel_PICKED_UP": "📦 Picked up from the seller",
        "parcel_IN_TRANSIT": "🚚 On the way",
        "parcel_OUT_FOR_DELIVERY": "🏁 Out for delivery",
        "parcel_DELIVERED": "✅ Delivered",
        "parcel_INCIDENT": "⚠️ Incident reported",
        "parcel_FAILED": "❌ Delivery failed",
        "parcel_CANCELLED": "❌ Cancelled",
        "order_CREATED": "⏳ Awaiting payment",
        "order_PAID_IN_ESCROW": "🔒 Paid · funds secured",
        "order_VENDOR_ACKNOWLEDGED": "👍 Confirmed by the seller",
        "order_PREPARING": "🛠️ Being prepared",
        "order_READY_FOR_PICKUP": "📦 Ready to go",
        "order_DRIVER_ASSIGNED": "🛵 Courier assigned",
        "order_PICKED_UP": "🚚 Picked up",
        "order_OUT_FOR_DELIVERY": "🏁 Out for delivery",
        "order_DELIVERED": "✅ Delivered",
        "order_BUYER_CONFIRMED": "✅ Receipt confirmed",
        "order_AUTO_CONFIRMED": "✅ Receipt confirmed",
        "order_RELEASED_TO_VENDOR": "✅ Completed",
        "order_DISPUTED": "⚠️ Dispute open",
        "order_CANCELLED": "❌ Cancelled",
        "order_REFUNDED": "↩️ Refunded",
        "order_status_other": "Status: {status}",

        # ── Seller ──
        "template_order": "New order {ref}",
        "sales_body": "🏪 *{count} orders to prepare*\nTap one to handle it.",
        "sales_button": "To prepare",
        "sales_section": "Orders",
        "sales_row": "{ref} · {total}",
        "sales_empty": "✅ No pending order. You are up to date!\nNew paid orders land here automatically.",
        "not_vendor": "This button is for BelivaY sellers only.",
        "sale_title": "🏪 *Order {ref}* · {date}",
        "sale_buyer": "👤 Buyer {buyer} · {city}",
        "sale_relay": "🏪 Handover at a relay point",
        "sale_items": "📦 *To prepare*",
        "sale_item_line": "• {title} × {qty}",
        "sale_total": "💰 Your share: *{total}*",
        "sale_deadline": "🕓 To be ready before *{deadline}*",
        "sale_late": "⚠️ *Late* — the preparation deadline has passed.",
        "sale_code": "🔑 The handover code is in your app: give it to the courier in person.",
        "sale_actions": "What would you like to do?",
        "btn_ack": "✅ I confirm",
        "btn_ready": "📦 Parcel ready",
        "btn_sales": "🏪 To prepare",
        "sale_acknowledged": "✅ *Order {ref} confirmed.*\nPrepare the parcel, then tap « Parcel ready ».",
        "sale_ready": "📦 *Order {ref} is ready.*\nA courier will be assigned for the pickup. Thank you!",
        "sale_already": "✅ Order {ref} is already at this stage.",
        "sale_not_yours": "This order contains none of your items.",
        "sale_refused": "Order {ref} can no longer be handled here ({status}). Open your app.",
        "sale_inactive": "Your shop is not active at the moment. Contact support: {phone}.",
        "vendor_PAID_IN_ESCROW": "💰 Paid · to confirm",
        "vendor_VENDOR_ACKNOWLEDGED": "👍 Confirmed · to prepare",
        "vendor_PREPARING": "🛠️ Being prepared",
        "vendor_READY_FOR_PICKUP": "📦 Ready · waiting for a courier",
        "vendor_DRIVER_ASSIGNED": "🛵 Courier assigned",
        "vendor_PICKED_UP": "🚚 Picked up",
        "vendor_DELIVERED": "✅ Delivered",
        "vendor_CANCELLED": "❌ Cancelled",

        # ── Relay point ──
        "template_relay": "Parcel on its way {ref}",
        "parcels_body": "🏪 *{count} parcels to handle*\nTap one for the details.",
        "parcels_button": "My parcels",
        "parcels_section": "Parcels",
        "parcels_row_in": "📥 {ref}",
        "parcels_row_out": "📤 {ref}",
        "parcels_empty": "✅ Nothing to handle right now.\nParcels heading to your relay point are announced here automatically.",
        "not_relay": "This button is for BelivaY relay points only.",
        "parcel_title": "*Parcel {ref}* · {status}",
        "parcel_expected": "🚚 On its way to you · courier {courier}",
        "parcel_expected_plain": "🚚 On its way to you",
        "parcel_stored": "📥 Received on {date} · slot *{slot}*",
        "parcel_items": "Contents: {count} item{s}",
        "parcel_free_until": "🆓 Free storage until *{date}*",
        "parcel_deadline": "🕓 To be collected before *{date}*",
        "parcel_fee": "💰 Storage fees due: *{fee}*",
        "parcel_late": "⚠️ *Deadline passed* — the parcel must go back to the seller.",
        "parcel_capacity": "📊 Storage: {stored} parcels out of {capacity}",
        "parcel_privacy": "🔒 The customer tells you their code at the counter. Never share it by message.",
        "parcel_actions": "What would you like to do?",
        "btn_receive": "📥 Parcel received",
        "btn_handover": "📤 Hand over",
        "btn_parcels": "🏪 My parcels",
        "ask_code": "🔑 Type the *collection code* the customer gives you.\nType *cancel* to go back.",
        "code_cancelled": "Hand-over cancelled. Nothing changed.",
        "relay_received": "📥 *Parcel {ref} received.*\nSlot: *{slot}*. The customer has just been told they can come and collect it.",
        "relay_handed": "📤 *Hand-over confirmed* — {refs}.\nThe delivery is recorded. Thank you!",
        "relay_already_received": "✅ Parcel {ref} is already received.",
        "relay_already_handed": "✅ This code was already used: the parcel has been collected.",
        "relay_bad_code": "❌ No waiting parcel with that code here.\nCheck with the customer, then tap « Hand over » again.",
        "relay_full": "📊 Your storage is full. Hand over waiting parcels, or raise your capacity in the app.",
        "relay_needs_app": "👤 This parcel is collected by an authorised third party: the ID must be recorded in your app.",
        "relay_not_yours": "This parcel is not in your relay point.",
        "relay_refused": "This parcel can no longer be handled here. Open your app.",
        "relay_inactive": "Your relay point is not active at the moment. Contact support: {phone}.",
        "relay_EXPECTED": "🚚 Expected",
        "relay_RECEIVED": "📥 Received",
        "relay_STORED": "📦 Waiting for collection",
        "relay_PICKED_UP": "✅ Collected",
        "relay_REFUSED": "❌ Refused at check",
        "relay_RETURNED_TO_VENDOR": "↩️ Returned to the seller",
        "relay_RETURNED_TO_BELIVAY": "↩️ Returned to BelivaY",

        # ── Talk to a human ──
        "btn_human": "💬 An adviser",
        "human_ask": "💬 *Tell us everything.*\nWrite your question or your problem in one message. A BelivaY adviser will answer you right here.\n\nType *cancel* to go back.",
        "human_ask_email": "✉️ One last thing: your *email address*, so we can reach you even if WhatsApp fails.",
        "human_bad_email": "That address does not look valid. Try again, or type *cancel*.",
        "human_too_short": "Your message is a little short. Tell us what is happening in a few more words.",
        "human_cancelled": "Request cancelled. I am still here for you 🙂",
        "human_sent": "✅ *Your request has been sent* (no. {ref}).\nA BelivaY adviser will answer you here, in this conversation.\n\nI will step aside while they get back to you. Type *menu* if you would rather carry on with me.",
        "human_failed": "😕 I cannot pass your request on right now.\nCall us on {phone} or write to {email}.",
        "human_back": "👋 I am back! What would you like to do?",
    },
}

# Avant le choix de la langue, l'assistant parle les deux.
LANGUAGE_PROMPT = (
    "👋 Bienvenue chez *{assistant}* ! Choisissez votre langue.\n_Welcome to {assistant}! Please choose your language._"
)


def t(language: str, key: str, **values) -> str:
    table = TEXTS.get(language) or TEXTS["fr"]
    return table[key].format(**values)


def price(amount: int) -> str:
    """18500 → « 18 500 FCFA »."""
    return f"{amount:,}".replace(",", " ") + " FCFA"
