# Generated by Django 5.1.15 on 2026-10-04 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleFamille",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_id", models.PositiveBigIntegerField(unique=True)),
                ("poids_g", models.PositiveIntegerField(help_text="FAM-POIDS-MAX au plus")),
                ("actif", models.BooleanField(default=True)),
                ("ordre", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Article du panier famille",
                "verbose_name_plural": "Articles du panier famille",
                "ordering": ["ordre", "id"],
            },
        ),
        migrations.CreateModel(
            name="ModeleFamille",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nom", models.CharField(max_length=80)),
                ("articles", models.JSONField(help_text="[{id: product_id, qte}]")),
            ],
            options={
                "verbose_name": "Panier famille prêt",
                "verbose_name_plural": "Paniers famille prêts",
            },
        ),
        migrations.CreateModel(
            name="ModeleReprise",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=40, unique=True)),
                ("nom", models.CharField(max_length=120)),
                ("cote", models.PositiveIntegerField(help_text="cote du reconditionneur partenaire (TRC-PARTENAIRE)")),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Modèle repris",
                "verbose_name_plural": "Modèles repris",
            },
        ),
        migrations.CreateModel(
            name="OffreFlash",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_id", models.PositiveBigIntegerField()),
                ("prix", models.PositiveIntegerField(help_text="prix de l'offre")),
                ("avant", models.PositiveIntegerField(help_text="prix vraiment pratiqué avant l'offre")),
                ("debut", models.DateTimeField()),
                ("fin", models.DateTimeField()),
                ("stock", models.PositiveIntegerField(help_text="stock propre à l'offre")),
                ("vendus", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Vente flash",
                "verbose_name_plural": "Ventes flash",
                "ordering": ["fin"],
            },
        ),
        migrations.CreateModel(
            name="SaisonRentree",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("saison", models.CharField(help_text="« 2026-2027 »", max_length=9, unique=True)),
                ("ouverte", models.BooleanField(default=True)),
                ("rentree_le", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Saison de rentrée",
                "verbose_name_plural": "Saisons de rentrée",
                "ordering": ["-saison"],
            },
        ),
        migrations.CreateModel(
            name="Cotisation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=16, unique=True)),
                ("organisateur_nom", models.CharField(max_length=80)),
                ("nom", models.CharField(max_length=160)),
                ("occasion", models.CharField(blank=True, default="", max_length=40)),
                ("product_id", models.PositiveBigIntegerField()),
                ("titre", models.CharField(max_length=200)),
                ("prix", models.PositiveIntegerField(help_text="prix de l'article, figé à la création")),
                ("frais", models.PositiveIntegerField(help_text="livraison au relais du bénéficiaire, figée à la création")),
                ("prix_livre", models.PositiveIntegerField()),
                ("objectif", models.PositiveIntegerField()),
                (
                    "qui",
                    models.CharField(
                        default="payeur", help_text="qui paie la livraison : payeur (participants) | destinataire", max_length=12
                    ),
                ),
                ("beneficiaire", models.CharField(max_length=80)),
                ("relay_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("relais_nom", models.CharField(blank=True, default="", max_length=160)),
                ("jusqua", models.DateTimeField()),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("ouverte", "Ouverte"),
                            ("atteinte", "Objectif atteint, commande partie"),
                            ("hausse", "Objectif atteint, prix en hausse : l'organisateur choisit"),
                            ("echue", "Date dépassée"),
                            ("remboursee", "Remboursée"),
                        ],
                        default="ouverte",
                        max_length=10,
                    ),
                ),
                ("hausse_prix", models.PositiveIntegerField(blank=True, null=True)),
                ("hausse_ecart", models.PositiveIntegerField(blank=True, null=True)),
                ("order_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("fin", models.DateTimeField(blank=True, null=True)),
                (
                    "liste_code",
                    models.CharField(
                        blank=True, db_index=True, default="", help_text="née d'un article cher d'une liste d'envies", max_length=16
                    ),
                ),
                ("liste_product_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "beneficiaire_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cotisations_recues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cotisations_organisees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotisation",
                "verbose_name_plural": "Cotisations",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Ecole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nom", models.CharField(max_length=160)),
                ("quartier", models.CharField(blank=True, default="", max_length=80)),
                ("verifiee", models.BooleanField(default=False)),
                ("depuis", models.DateTimeField(auto_now_add=True)),
                ("gestionnaires", models.ManyToManyField(blank=True, related_name="ecoles_gerees", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "École",
                "verbose_name_plural": "Écoles",
            },
        ),
        migrations.CreateModel(
            name="ListeRentree",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("classe", models.CharField(max_length=40)),
                ("section", models.CharField(default="fr", max_length=2)),
                (
                    "statut",
                    models.CharField(choices=[("publiee", "Publiée"), ("brouillon", "Brouillon")], default="brouillon", max_length=10),
                ),
                ("publiee_le", models.DateTimeField(blank=True, null=True)),
                ("historique", models.JSONField(blank=True, default=list, help_text="[{le, texte}]")),
                ("ecole", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="listes", to="extras.ecole")),
                (
                    "saison",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="listes", to="extras.saisonrentree"),
                ),
            ],
            options={
                "verbose_name": "Liste de rentrée",
                "verbose_name_plural": "Listes de rentrée",
            },
        ),
        migrations.CreateModel(
            name="ArticleRentree",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titre", models.CharField(max_length=200)),
                ("groupe", models.CharField(blank=True, default="", max_length=80)),
                ("qte", models.PositiveIntegerField(default=1)),
                ("product_id", models.PositiveBigIntegerField(help_text="l'offre retenue (prix, boutique, zone lus dans le catalogue)")),
                ("consigne", models.CharField(blank=True, default="", max_length=200)),
                ("exigee", models.BooleanField(default=False, help_text="édition exigée : pas d'équivalent")),
                ("equivalent_product_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "liste",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="articles", to="extras.listerentree"),
                ),
            ],
            options={
                "verbose_name": "Article d'une liste de rentrée",
                "verbose_name_plural": "Articles des listes de rentrée",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MiseDeCote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("titre", models.CharField(max_length=200)),
                ("prix", models.PositiveIntegerField()),
                ("livraison", models.PositiveIntegerField()),
                ("prix_livre", models.PositiveIntegerField()),
                ("rythme", models.CharField(choices=[("2sem", "Toutes les 2 semaines"), ("mois", "Chaque mois")], max_length=4)),
                ("moyen", models.CharField(max_length=60)),
                ("numero_chiffre", models.BinaryField(blank=True, null=True)),
                ("relay_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "etat",
                    models.CharField(
                        choices=[("en_cours", "En cours"), ("payee", "Payée"), ("annulee", "Annulée")], default="en_cours", max_length=8
                    ),
                ),
                ("order_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("annulee_le", models.DateTimeField(blank=True, null=True)),
                ("rembourse", models.PositiveIntegerField(blank=True, null=True)),
                ("forfait", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "liste",
                    models.JSONField(
                        blank=True,
                        help_text="liste de rentrée entière : {id, classe, ecole, exclus, equivalents, articles, rentreeLe}",
                        null=True,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="mises_de_cote", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Mise de côté",
                "verbose_name_plural": "Mises de côté",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="PanierFamille",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nom", models.CharField(default="Panier famille", max_length=80)),
                ("destinataire_prenom", models.CharField(blank=True, default="", max_length=80)),
                ("destinataire_relais", models.CharField(blank=True, default="", max_length=160)),
                ("articles", models.JSONField(blank=True, default=list, help_text="[{id: product_id, qte}]")),
                ("mensuel", models.BooleanField(default=False)),
                ("jour", models.PositiveSmallIntegerField(default=21)),
                ("suspendu", models.BooleanField(default=False)),
                (
                    "carte",
                    models.CharField(
                        blank=True, default="", help_text="« Visa •••• 4242 » ; le jeton reste chez le prestataire", max_length=60
                    ),
                ),
                ("jeton_carte", models.CharField(blank=True, default="", max_length=120)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="paniers_famille", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Panier famille",
                "verbose_name_plural": "Paniers famille",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PaiementFamille",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("montant", models.PositiveIntegerField()),
                ("order_id", models.PositiveBigIntegerField()),
                ("reference", models.CharField(blank=True, default="", max_length=80)),
                ("le", models.DateTimeField(auto_now_add=True)),
                (
                    "panier",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="historique", to="extras.panierfamille"),
                ),
            ],
            options={
                "verbose_name": "Paiement d'un panier famille",
                "verbose_name_plural": "Paiements des paniers famille",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prenom", models.CharField(max_length=80)),
                ("montant", models.PositiveIntegerField(help_text="ce qui compte pour l'objectif")),
                ("frais", models.PositiveIntegerField(default=0, help_text="frais de carte payés en plus (rendus au remboursement)")),
                ("discret", models.BooleanField(default=False)),
                ("moyen", models.CharField(default="mobile", max_length=10)),
                ("moyen_affiche", models.CharField(blank=True, default="", max_length=60)),
                ("numero_chiffre", models.BinaryField(blank=True, null=True)),
                ("mot", models.CharField(blank=True, default="", max_length=200)),
                ("organisateur", models.BooleanField(default=False)),
                ("reference", models.CharField(blank=True, default="", max_length=80)),
                (
                    "etat_paiement",
                    models.CharField(
                        choices=[("attente", "En attente"), ("paye", "Payé"), ("rembourse", "Remboursé")], default="paye", max_length=10
                    ),
                ),
                ("le", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "cotisation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="participations", to="extras.cotisation"),
                ),
            ],
            options={
                "verbose_name": "Participation",
                "verbose_name_plural": "Participations",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Troc",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_id", models.PositiveBigIntegerField()),
                ("titre", models.CharField(max_length=200)),
                ("prix", models.PositiveIntegerField()),
                ("prix_livre", models.PositiveIntegerField()),
                ("declare", models.JSONField()),
                ("estimation_min", models.PositiveIntegerField()),
                ("estimation_max", models.PositiveIntegerField()),
                ("code_depot", models.CharField(max_length=6)),
                ("relay_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("relais_nom", models.CharField(blank=True, default="", max_length=160)),
                ("depose_le", models.DateTimeField(blank=True, null=True)),
                ("collecte_le", models.DateTimeField(blank=True, null=True)),
                ("recu_le", models.DateTimeField(blank=True, null=True)),
                ("inspecte_le", models.DateTimeField(blank=True, null=True)),
                ("valeur", models.PositiveIntegerField(blank=True, null=True)),
                ("contre_offre", models.JSONField(blank=True, null=True)),
                ("motif", models.JSONField(blank=True, null=True)),
                ("contestation", models.JSONField(blank=True, null=True)),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("depot", "À déposer au relais"),
                            ("depose", "Déposé"),
                            ("collecte", "Collecté"),
                            ("inspection", "En inspection"),
                            ("confirme", "Valeur confirmée"),
                            ("contre", "Contre-offre"),
                            ("refuse", "Refusé"),
                            ("paye", "Neuf payé"),
                            ("rendu", "Téléphone rendu"),
                            ("annule", "Annulé"),
                        ],
                        default="depot",
                        max_length=10,
                    ),
                ),
                ("order_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="trocs", to=settings.AUTH_USER_MODEL),
                ),
                ("modele", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="extras.modelereprise")),
            ],
            options={
                "verbose_name": "Reprise d'un téléphone",
                "verbose_name_plural": "Reprises de téléphones",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="DestinataireFamille",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prenom", models.CharField(max_length=80)),
                ("numero_chiffre", models.BinaryField()),
                ("numero_masque", models.CharField(max_length=40)),
                ("relay_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("relais_nom", models.CharField(max_length=160)),
                ("lie_le", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="destinataires_famille", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Destinataire d'un panier famille",
                "verbose_name_plural": "Destinataires des paniers famille",
                "constraints": [models.UniqueConstraint(fields=("client", "prenom"), name="extras_destinataire_unique")],
            },
        ),
        migrations.CreateModel(
            name="Versement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("n", models.PositiveSmallIntegerField()),
                ("du", models.PositiveIntegerField()),
                ("le", models.DateTimeField()),
                ("paye_le", models.DateTimeField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, default="", max_length=80)),
                ("mise", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="versements", to="extras.misedecote")),
            ],
            options={
                "verbose_name": "Versement",
                "verbose_name_plural": "Versements",
                "ordering": ["n"],
                "constraints": [models.UniqueConstraint(fields=("mise", "n"), name="extras_versement_unique")],
            },
        ),
    ]
