# Generated by Django 5.1.15 on 2026-10-05 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListePapier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("classe", models.CharField(max_length=40)),
                ("photo", models.FileField(upload_to="rentree/papier/%Y/%m/")),
                ("le", models.DateTimeField(auto_now_add=True)),
                ("pret_le", models.DateTimeField(help_text="saisie annoncée au parent")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="listes_papier", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "liste",
                    models.ForeignKey(
                        blank=True,
                        help_text="la liste saisie",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="extras.listerentree",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liste de rentrée sur papier",
                "verbose_name_plural": "Listes de rentrée sur papier",
                "ordering": ["-id"],
            },
        ),
    ]
