# Generated by Django 5.1.15 on 2026-10-04 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Abonnement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "palier",
                    models.CharField(
                        choices=[
                            ("plus", "Plus"),
                            ("prime", "Prime"),
                            ("duo", "Prime Duo"),
                            ("business", "Business"),
                            ("pass", "Pass 7 jours"),
                        ],
                        max_length=10,
                    ),
                ),
                ("formule", models.CharField(choices=[("mois", "Au mois"), ("an", "À l'année"), ("pass", "Pass")], max_length=5)),
                ("debut", models.DateTimeField()),
                (
                    "prochain",
                    models.DateTimeField(blank=True, help_text="prochain prélèvement (vide : Pass, offert ou résilié)", null=True),
                ),
                ("montant", models.PositiveIntegerField(help_text="montant du prochain prélèvement")),
                ("moyen", models.CharField(help_text="libellé affiché : « MTN MoMo · 6 77 ·· ·· 41 »", max_length=80)),
                (
                    "moyen_ref",
                    models.CharField(blank=True, default="", help_text="« compte », « m12 », « c3 » (apps.wallet)", max_length=20),
                ),
                ("essai", models.BooleanField(default=False, help_text="premier mois au prix d'essai")),
                ("resilie", models.DateTimeField(blank=True, null=True)),
                ("fin", models.DateTimeField(blank=True, help_text="fin de la période payée (résilié, Pass, offert)", null=True)),
                ("offert_par", models.CharField(blank=True, default="", max_length=80)),
                ("message_cadeau", models.CharField(blank=True, default="", max_length=300)),
                ("echec_le", models.DateTimeField(blank=True, null=True)),
                ("echec_moyen", models.CharField(blank=True, default="", max_length=80)),
                ("echec_montant", models.PositiveIntegerField(default=0)),
                ("echec_tentatives", models.PositiveSmallIntegerField(default=0)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="abonnements_client", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement client",
                "verbose_name_plural": "Abonnements clients",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="AbonnementOffert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero_chiffre", models.BinaryField()),
                ("numero_empreinte", models.CharField(db_index=True, max_length=64)),
                ("numero_masque", models.CharField(max_length=40)),
                ("prenom", models.CharField(max_length=80)),
                (
                    "palier",
                    models.CharField(
                        choices=[
                            ("plus", "Plus"),
                            ("prime", "Prime"),
                            ("duo", "Prime Duo"),
                            ("business", "Business"),
                            ("pass", "Pass 7 jours"),
                        ],
                        max_length=10,
                    ),
                ),
                ("mois", models.PositiveSmallIntegerField()),
                ("message", models.CharField(blank=True, default="", max_length=300)),
                ("montant", models.PositiveIntegerField()),
                ("frais_service", models.PositiveIntegerField()),
                ("carte", models.CharField(help_text="« Visa •••• 4242 »", max_length=60)),
                ("ref", models.CharField(help_text="CAD-…", max_length=20, unique=True)),
                ("paiement_ref", models.CharField(blank=True, default="", max_length=80)),
                ("le", models.DateTimeField(auto_now_add=True)),
                (
                    "abonnement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cadeau",
                        to="subscriptions.abonnement",
                    ),
                ),
                (
                    "beneficiaire",
                    models.ForeignKey(
                        blank=True,
                        help_text="vide : pas encore de compte",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="abonnements_recus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offrant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="abonnements_offerts", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement offert",
                "verbose_name_plural": "Abonnements offerts",
            },
        ),
        migrations.CreateModel(
            name="CodeParrainage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=12, unique=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="code_parrainage", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Code de parrainage",
                "verbose_name_plural": "Codes de parrainage",
            },
        ),
        migrations.CreateModel(
            name="CreditCagnotte",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_id", models.PositiveBigIntegerField(unique=True)),
                (
                    "palier",
                    models.CharField(
                        choices=[
                            ("plus", "Plus"),
                            ("prime", "Prime"),
                            ("duo", "Prime Duo"),
                            ("business", "Business"),
                            ("pass", "Pass 7 jours"),
                        ],
                        max_length=10,
                    ),
                ),
                ("base", models.PositiveIntegerField(help_text="sous-total produits des colis non annulés")),
                ("montant", models.PositiveIntegerField()),
                ("reste", models.PositiveIntegerField(help_text="encore à verser")),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("disponible", "Créditée, à verser (portefeuille fermé ou plein)"),
                            ("versee", "Versée"),
                            ("expiree", "Expirée (ABO-CAGNOTTE)"),
                        ],
                        default="disponible",
                        max_length=10,
                    ),
                ),
                ("credite_le", models.DateTimeField(auto_now_add=True)),
                ("expire_le", models.DateTimeField()),
                ("versee_le", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cagnottes", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Cagnotte d'une commande",
                "verbose_name_plural": "Cagnottes des commandes",
            },
        ),
        migrations.CreateModel(
            name="EssaiUtilise",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero_empreinte", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("le", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="essais_abonnement", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Essai Prime utilisé",
                "verbose_name_plural": "Essais Prime utilisés",
            },
        ),
        migrations.CreateModel(
            name="Parrainage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("inscrit_le", models.DateTimeField(auto_now_add=True)),
                ("retiree_le", models.DateTimeField(blank=True, help_text="première commande payée et retirée", null=True)),
                (
                    "recompense_le",
                    models.DateTimeField(blank=True, help_text="mois offert au parrain (ABO-PARRAIN : 3 par mois au plus)", null=True),
                ),
                ("mois_offerts", models.PositiveSmallIntegerField(default=0)),
                (
                    "filleul",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="parrainage", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "parrain",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="filleuls", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Parrainage",
                "verbose_name_plural": "Parrainages",
            },
        ),
        migrations.CreateModel(
            name="Prelevement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("montant", models.PositiveIntegerField()),
                ("moyen", models.CharField(max_length=80)),
                ("reference", models.CharField(max_length=60, unique=True)),
                (
                    "etat",
                    models.CharField(
                        choices=[("attente", "En attente de l'opérateur"), ("reussi", "Réussi"), ("refuse", "Refusé")],
                        default="attente",
                        max_length=8,
                    ),
                ),
                ("motif", models.CharField(blank=True, default="", max_length=60)),
                ("le", models.DateTimeField(auto_now_add=True)),
                (
                    "abonnement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="prelevements", to="subscriptions.abonnement"
                    ),
                ),
            ],
            options={
                "verbose_name": "Prélèvement d'abonnement",
                "verbose_name_plural": "Prélèvements d'abonnement",
            },
        ),
    ]
