# Generated by Django 5.1.15 on 2026-10-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="abonnementoffert",
            name="paiement",
            field=models.CharField(
                choices=[("paye", "Payé"), ("action", "3-D Secure à valider"), ("refuse", "Refusé par la banque")],
                default="paye",
                help_text="action : appliqué au retour de la banque (webhook)",
                max_length=8,
            ),
        ),
    ]
