# Generated by Django 5.1.15 on 2026-10-04 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangementLieu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_id", models.PositiveBigIntegerField(db_index=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("relais", "Autre relais"), ("adresse", "Autre adresse"), ("transfert", "Transfert d'un colis arrivé")],
                        max_length=10,
                    ),
                ),
                ("vers_relay_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("vers_adresse_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("transfert", models.PositiveIntegerField(default=0)),
                ("garde_due", models.PositiveIntegerField(default=0)),
                ("montant_du", models.PositiveIntegerField(default=0, help_text="une seule demande Mobile Money")),
                ("deux_codes", models.BooleanField(default=False)),
                ("trace", models.JSONField(blank=True, default=list)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Changement de lieu",
                "verbose_name_plural": "Changements de lieu",
            },
        ),
        migrations.CreateModel(
            name="GroupeRemise",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_id", models.PositiveBigIntegerField(db_index=True)),
                ("relay_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("code_chiffre", models.BinaryField(help_text="6 chiffres, chiffré (CAP-18, CAP-21)")),
                ("code_empreinte", models.CharField(max_length=64)),
                ("accuse_fort_le", models.DateTimeField(blank=True, help_text="premier accusé fort : fixe J0 (CAL-19)", null=True)),
                ("valeur", models.PositiveIntegerField(default=0, help_text="valeur des colis : plafond de la garde")),
                ("montant_paye", models.PositiveIntegerField(default=0, help_text="payé par le client : retenue au plus (DP-24)")),
                ("gros", models.BooleanField(default=False, help_text="au moins un carton C1 ou C2")),
                ("jours_suspendus", models.JSONField(blank=True, default=list, help_text="dates AAAA-MM-JJ : litige, groupage, transfert")),
                ("rappels_non_delivres", models.JSONField(blank=True, default=list, help_text="dates AAAA-MM-JJ (CSM-30)")),
                ("essais_faux", models.PositiveSmallIntegerField(default=0)),
                ("bloque_jusqua", models.DateTimeField(blank=True, null=True)),
                ("renvois", models.JSONField(blank=True, default=list, help_text="instants (ms) des renvois du code")),
                ("retire_le", models.DateTimeField(blank=True, null=True)),
                ("renvoye_le", models.DateTimeField(blank=True, help_text="renvoyé au vendeur après le 7e jour", null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Groupe de remise",
                "verbose_name_plural": "Groupes de remise",
            },
        ),
        migrations.CreateModel(
            name="HorairesRelais",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("relay_id", models.PositiveBigIntegerField(help_text="accounts.RelayPointProfile", unique=True)),
                ("ouverture", models.TimeField()),
                ("fermeture", models.TimeField()),
                ("jours_fermes", models.JSONField(blank=True, default=list, help_text="0 = lundi … 6 = dimanche")),
                ("fermetures", models.JSONField(blank=True, default=list, help_text="fermetures exceptionnelles, AAAA-MM-JJ")),
            ],
            options={
                "verbose_name": "Horaires d'un relais",
                "verbose_name_plural": "Horaires des relais",
            },
        ),
        migrations.CreateModel(
            name="CompteComptoir",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("refus", models.PositiveSmallIntegerField(default=0, help_text="refus sans motif d'une commande validée au comptoir")),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="compte_comptoir", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte comptoir",
                "verbose_name_plural": "Comptes comptoir",
            },
        ),
        migrations.CreateModel(
            name="MontantsCommande",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_id", models.PositiveBigIntegerField(help_text="orders.Order de relaya-marketplace", unique=True)),
                ("mode", models.CharField(choices=[("relais", "Relais"), ("domicile", "Domicile")], default="relais", max_length=10)),
                ("relay_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("adresse_id", models.PositiveBigIntegerField(blank=True, help_text="client_accounts.Adresse", null=True)),
                (
                    "lieu",
                    models.CharField(blank=True, default="", help_text="« Relais Mvog-Ada » ou « Maison · Mvog-Ada »", max_length=160),
                ),
                ("sous_total", models.PositiveIntegerField()),
                ("ramassages", models.PositiveIntegerField()),
                ("remises", models.PositiveIntegerField()),
                ("supplements", models.PositiveIntegerField(default=0)),
                ("offert", models.PositiveIntegerField(default=0)),
                ("total", models.PositiveIntegerField(help_text="S + Ram + Rem + Suppl − Off")),
                ("seuil", models.PositiveIntegerField(default=0)),
                ("frais_service", models.PositiveIntegerField(default=0, help_text="carte : PAY-CARTE-FRAIS (2 %)")),
                ("prime", models.PositiveIntegerField(default=0, help_text="remise de l'abonnement sur la livraison")),
                ("version_parametres", models.CharField(max_length=40)),
                ("moyen", models.CharField(help_text="mtn | orange | autre | wallet | carte | apple | google", max_length=10)),
                ("numero_masque", models.CharField(blank=True, default="", max_length=40)),
                ("comptoir", models.BooleanField(default=False)),
                ("avance", models.PositiveIntegerField(default=0, help_text="payé maintenant (comptoir : la livraison seule)")),
                ("du_au_retrait", models.PositiveIntegerField(default=0)),
                ("devise", models.CharField(default="XAF", max_length=3)),
                ("montant_devise", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("taux_devise", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                (
                    "etat_paiement",
                    models.CharField(
                        choices=[("attente", "En attente de validation"), ("payee", "Payée"), ("echec", "Échec")],
                        default="attente",
                        max_length=10,
                    ),
                ),
                ("cause_echec", models.CharField(blank=True, default="", help_text="expire | solde | carte", max_length=10)),
                ("expire_le", models.DateTimeField(blank=True, help_text="fin de la demande Mobile Money", null=True)),
                ("payee_le", models.DateTimeField(blank=True, null=True)),
                ("payeur", models.JSONField(blank=True, help_text="payé par un proche à l'étranger (PanierPartage.payeur)", null=True)),
                (
                    "tout_en_ordre_le",
                    models.DateTimeField(blank=True, help_text="« Tout est en ordre » : ferme la fenêtre de retour", null=True),
                ),
                ("rembourse", models.PositiveIntegerField(default=0)),
                ("service_reparti", models.PositiveIntegerField(default=0, help_text="frais de service déjà rendus ou acquis (CET-24)")),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="montants_commandes", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Montants figés d'une commande",
                "verbose_name_plural": "Montants figés des commandes",
            },
        ),
        migrations.CreateModel(
            name="SousCommande",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_id", models.PositiveBigIntegerField(db_index=True)),
                ("n", models.PositiveSmallIntegerField(help_text="numéro du colis dans la commande (1, 2…)")),
                ("vendor_id", models.PositiveBigIntegerField(blank=True, help_text="vendors.VendorProfile", null=True)),
                ("boutique", models.CharField(max_length=255)),
                ("zone", models.CharField(blank=True, default="", max_length=120)),
                (
                    "classe",
                    models.CharField(default="S", help_text="S, M, L, XL, HG : la plus grande classe de ses articles", max_length=2),
                ),
                ("sous_total", models.PositiveIntegerField()),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("payee", "Payée · pas encore confirmée"),
                            ("confirmee", "Confirmée · en préparation"),
                            ("prete", "Prête"),
                            ("collectee", "Collectée par le livreur"),
                            ("arrivee_relais", "Arrivée au relais"),
                            ("en_livraison_domicile", "En livraison à domicile"),
                            ("remise", "Remise au client"),
                            ("en_litige", "En litige"),
                            ("retour_en_cours", "Retour en cours"),
                            ("renvoyee_vendeur", "Renvoyée au vendeur"),
                            ("annulee", "Annulée"),
                        ],
                        default="payee",
                        max_length=24,
                    ),
                ),
                (
                    "relay_id",
                    models.PositiveBigIntegerField(blank=True, help_text="relais de destination (peut changer : transfert)", null=True),
                ),
                ("etagere", models.CharField(blank=True, default="", max_length=20)),
                ("gros", models.BooleanField(default=False, help_text="carton C1 ou C2 : + GARDE-GROS-AJOUT par jour")),
                ("collectee_le", models.DateTimeField(blank=True, null=True)),
                ("arrivee_le", models.DateTimeField(blank=True, null=True)),
                ("remise_le", models.DateTimeField(blank=True, help_text="retrait ou remise : ouvre la fenêtre de retour", null=True)),
                ("annulee_le", models.DateTimeField(blank=True, null=True)),
                (
                    "annulee_par",
                    models.CharField(
                        blank=True,
                        choices=[("toi", "Le client"), ("vendeur", "Le vendeur"), ("belivay", "BelivaY")],
                        default="",
                        max_length=10,
                    ),
                ),
                ("motif_annulation", models.CharField(blank=True, default="", max_length=255)),
                ("rembourse", models.PositiveIntegerField(default=0)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "groupe",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="colis", to="pickup.grouperemise"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sous-commande (colis)",
                "verbose_name_plural": "Sous-commandes (colis)",
                "ordering": ["order_id", "n"],
            },
        ),
        migrations.CreateModel(
            name="LigneSousCommande",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_id", models.PositiveBigIntegerField()),
                ("titre", models.CharField(max_length=200)),
                ("prix", models.PositiveIntegerField()),
                ("qte", models.PositiveIntegerField()),
                ("classe", models.CharField(default="S", max_length=2)),
                (
                    "sous_commande",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lignes", to="pickup.souscommande"),
                ),
            ],
            options={
                "verbose_name": "Ligne d'une sous-commande",
                "verbose_name_plural": "Lignes des sous-commandes",
            },
        ),
        migrations.AddConstraint(
            model_name="souscommande",
            constraint=models.UniqueConstraint(fields=("order_id", "n"), name="pickup_sous_commande_unique"),
        ),
    ]
