# Generated by Django 5.1.15 on 2026-04-14 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendorordernote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_xaf', models.PositiveIntegerField(verbose_name='Montant demandé (FCFA)')),
                ('fee_percent_snapshot', models.DecimalField(decimal_places=2, help_text='Snapshot du taux en vigueur au moment de la demande.', max_digits=4, verbose_name='Taux de frais appliqué (%)')),
                ('fee_amount_xaf', models.PositiveIntegerField(help_text='fee_percent_snapshot × amount_xaf / 100, arrondi.', verbose_name='Frais prélevés (FCFA)')),
                ('net_amount_xaf', models.PositiveIntegerField(help_text='amount_xaf - fee_amount_xaf.', verbose_name='Montant net versé (FCFA)')),
                ('operator', models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('MTN_MOMO', 'MTN Mobile Money')], max_length=20, verbose_name='Opérateur')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro Mobile Money')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé et versé'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé par le vendeur')], default='PENDING', max_length=10, verbose_name='Statut')),
                ('reference', models.CharField(blank=True, help_text='Générée automatiquement : BLV-WD-{année}-{id}.', max_length=30, unique=True, verbose_name='Référence')),
                ('admin_note', models.TextField(blank=True, default='', verbose_name='Note admin')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Demande de Retrait',
                'verbose_name_plural': 'Demandes de Retrait',
                'ordering': ['-created_at'],
            },
        ),
    ]
