# Generated by Django 5.1.15 on 2026-04-19 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def populate_shop_slugs(apps, schema_editor):
    VendorProfile = apps.get_model('vendors', 'VendorProfile')
    seen = set()
    for vp in VendorProfile.objects.all():
        base = slugify(vp.business_name) or f'boutique-{vp.id}'
        slug = base
        counter = 1
        while slug in seen:
            slug = f'{base}-{counter}'
            counter += 1
        seen.add(slug)
        vp.shop_slug = slug
        vp.save(update_fields=['shop_slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_shop_plans_certifications'),
        ('vendors', '0003_withdrawalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('FREE', 'Gratuit'), ('STARTER', 'Starter'), ('PRO', 'Pro'), ('BUSINESS', 'Business')], max_length=20, unique=True, verbose_name='Code plan')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du plan')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price_monthly_xaf', models.PositiveIntegerField(default=0, help_text='0 = plan gratuit', verbose_name='Prix mensuel (FCFA)')),
                ('price_annual_xaf', models.PositiveIntegerField(default=0, help_text='0 = plan gratuit. Typiquement prix_mensuel x 10 (2 mois offerts).', verbose_name='Prix annuel (FCFA)')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Taux de commission (%)')),
                ('max_products', models.PositiveIntegerField(blank=True, help_text='null = illimite', null=True, verbose_name='Produits maximum')),
                ('max_boosts_month', models.PositiveIntegerField(default=0, verbose_name='Boosts max/mois')),
                ('features', models.JSONField(default=list, help_text='Liste JSON. Ex: ["QR Code boutique", "Support prioritaire"]', verbose_name='Fonctionnalites')),
                ('is_active', models.BooleanField(default=True, verbose_name='Plan actif')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordre affichage')),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
                'ordering': ['display_order', 'price_monthly_xaf'],
            },
        ),
        migrations.AlterModelOptions(
            name='vendorordernote',
            options={'verbose_name': 'Note Interne Vendeur', 'verbose_name_plural': 'Notes Internes Vendeurs'},
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/banners/%Y/%m/', verbose_name='Banniere'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='certification_tier',
            field=models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Argent'), ('GOLD', 'Or'), ('DIAMOND', 'Diamant')], default='BRONZE', max_length=10, verbose_name='Niveau de certification'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='is_online',
            field=models.BooleanField(default=True, verbose_name='Boutique en ligne'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration du plan'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='preparation_delay',
            field=models.CharField(choices=[('24H', '24h ouvrables'), ('48H', '48h ouvrables'), ('72H', '72h ouvrables'), ('CUSTOM', 'Sur commande')], default='72H', max_length=10, verbose_name='Delai de preparation'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/photos/%Y/%m/', verbose_name='Photo de boutique'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='return_policy',
            field=models.TextField(blank=True, default='', verbose_name='Politique de retour'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='shop_slug',
            field=models.SlugField(blank=True, help_text='URL : belivay.com/boutique/{slug}. Auto-genere depuis le nom.', max_length=120, verbose_name='Slug URL'),
        ),
        migrations.RunPython(populate_shop_slugs, migrations.RunPython.noop),
        migrations.RunSQL(
            sql='ALTER TABLE vendors_vendorprofile ADD CONSTRAINT vendors_vendorprofile_shop_slug_uniq UNIQUE (shop_slug);',
            reverse_sql='ALTER TABLE vendors_vendorprofile DROP CONSTRAINT IF EXISTS vendors_vendorprofile_shop_slug_uniq;',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='total_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Points de certification (cache)'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telephone WhatsApp'),
        ),
        migrations.AlterField(
            model_name='vendorordernote',
            name='content',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='vendorordernote',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_notes', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='vendorordernote',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_notes', to='vendors.vendorprofile'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='business_description',
            field=models.TextField(verbose_name='Description de la boutique'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='business_name',
            field=models.CharField(max_length=255, verbose_name='Nom de la boutique'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ville principale'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='id_document',
            field=models.CharField(blank=True, max_length=255, verbose_name='Document identite'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telephone principal'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuve'), ('REJECTED', 'Rejete'), ('SUSPENDED', 'Suspendu')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='amount_xaf',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='fee_amount_xaf',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='fee_percent_snapshot',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='net_amount_xaf',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='operator',
            field=models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('MTN_MOMO', 'MTN MoMo')], max_length=15),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='reference',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuve'), ('REJECTED', 'Rejete'), ('CANCELLED', 'Annule')], default='PENDING', max_length=12),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='vendors.vendorprofile'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='current_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='vendors.subscriptionplan', verbose_name='Plan actuel'),
        ),
        migrations.CreateModel(
            name='VendorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Mensuel'), ('ANNUAL', 'Annuel')], default='MONTHLY', max_length=10)),
                ('amount_paid_xaf', models.PositiveIntegerField(default=0, verbose_name='Montant paye (FCFA)')),
                ('operator', models.CharField(blank=True, choices=[('ORANGE_MONEY', 'Orange Money'), ('MTN_MOMO', 'MTN MoMo')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Numero MoMo')),
                ('payment_reference', models.CharField(blank=True, help_text='Auto-genere : BLV-SUB-{year}-{id}', max_length=60)),
                ('sub_status', models.CharField(choices=[('PENDING', 'En attente de paiement'), ('ACTIVE', 'Actif'), ('EXPIRED', 'Expire'), ('CANCELLED', 'Annule')], default='PENDING', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='vendors.subscriptionplan')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'Abonnement Vendeur',
                'verbose_name_plural': 'Abonnements Vendeurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
