# Generated by Django 5.1.15 on 2026-04-19 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_shop_plans_certifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du document')),
                ('description', models.TextField(blank=True, verbose_name='Description / instructions')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de document requis',
                'verbose_name_plural': 'Types de documents requis',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='preparation_delay',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='return_policy',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_duration_days',
            field=models.PositiveIntegerField(default=30, help_text="Durée d'un abonnement mensuel en jours.", verbose_name='Durée du plan (jours)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.PositiveIntegerField(default=0, help_text="0 = pas d'essai. Activé quand le vendeur choisit le plan pour la première fois.", verbose_name="Jours d'essai gratuit"),
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='is_trial',
            field=models.BooleanField(default=False, help_text="Si True, c'est un essai gratuit — pas de paiement requis.", verbose_name='Essai gratuit'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='code',
            field=models.CharField(choices=[('FREE', 'Gratuit'), ('STARTER', 'Starter'), ('PRO', 'Pro'), ('BUSINESS', 'Business')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_boosts_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_products',
            field=models.PositiveIntegerField(blank=True, help_text='null = illimité', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_annual_xaf',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_monthly_xaf',
            field=models.PositiveIntegerField(default=0, help_text='0 = gratuit'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/banners/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='business_description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='certification_tier',
            field=models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Argent'), ('GOLD', 'Or'), ('DIAMOND', 'Diamant')], default='BRONZE', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='current_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='vendors.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='id_document',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='shop_slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('SUSPENDED', 'Suspendu')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorsubscription',
            name='amount_paid_xaf',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendorsubscription',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Mensuel'), ('ANNUAL', 'Annuel'), ('TRIAL', 'Essai gratuit')], default='MONTHLY', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendorsubscription',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='vendorsubscription',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorsubscription',
            name='sub_status',
            field=models.CharField(choices=[('PENDING', 'En attente de paiement'), ('ACTIVE', 'Actif'), ('EXPIRED', 'Expiré'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=12),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=12),
        ),
        migrations.CreateModel(
            name='ShopModificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields_requested', models.JSONField(help_text='Ex: {"business_name": "Nouveau Nom", "city": "Douala"}', verbose_name='Champs à modifier')),
                ('reason', models.TextField(verbose_name='Justification du vendeur')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('DOCS_REQUIRED', 'Documents requis'), ('DOCS_UPLOADED', 'Documents fournis'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=15)),
                ('admin_note', models.TextField(blank=True, verbose_name="Note de l'admin")),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_mod_requests', to=settings.AUTH_USER_MODEL)),
                ('required_docs', models.ManyToManyField(blank=True, to='vendors.requireddocumenttype', verbose_name="Documents requis par l'admin")),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modification_requests', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'Demande de modification',
                'verbose_name_plural': 'Demandes de modification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopModificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vendors/mod_docs/%Y/%m/', verbose_name='Fichier')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.requireddocumenttype', verbose_name='Type de document')),
                ('modification_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vendors.shopmodificationrequest')),
            ],
            options={
                'verbose_name': 'Document de modification',
                'verbose_name_plural': 'Documents de modification',
            },
        ),
        migrations.CreateModel(
            name='VendorLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'emplacement")),
                ('address', models.TextField(verbose_name='Adresse complète')),
                ('phone', models.CharField(max_length=20, verbose_name="Téléphone de l'emplacement")),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name="Email de l'emplacement")),
                ('representative_name', models.CharField(max_length=200, verbose_name='Nom du représentant')),
                ('representative_phone', models.CharField(max_length=20, verbose_name='Téléphone du représentant')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Ex: 3.848 (Yaoundé). Remplissez pour activer la carte.', max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Ex: 11.502 (Yaoundé)', max_digits=9, null=True, verbose_name='Longitude')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'Emplacement de boutique',
                'verbose_name_plural': 'Emplacements de boutique',
                'ordering': ['name'],
            },
        ),
    ]
