# Generated by Django 5.1.15 on 2026-04-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_locations_modrequests_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='default_withdrawal_operator',
            field=models.CharField(blank=True, choices=[('MTN_MOMO', 'MTN MoMo'), ('ORANGE_MONEY', 'Orange Money')], max_length=20, verbose_name='Opérateur Mobile Money préférentiel'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='default_withdrawal_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro Mobile Money préférentiel'),
        ),
    ]
