# Generated by Django 5.1.15 on 2026-05-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendor_default_withdrawal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur'), ('CRITICAL', 'Critique')], db_index=True, default='INFO', max_length=10)),
                ('service', models.CharField(choices=[('api', 'API Backend'), ('auth', 'Authentification'), ('payments', 'Paiements'), ('email', 'Email'), ('orders', 'Commandes'), ('catalog', 'Catalogue'), ('vendors', 'Vendeurs'), ('system', 'Système')], db_index=True, default='system', max_length=20)),
                ('message', models.TextField()),
                ('logger', models.CharField(blank=True, max_length=200)),
                ('pathname', models.CharField(blank=True, max_length=500)),
                ('lineno', models.IntegerField(blank=True, null=True)),
                ('exc_text', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Log Système',
                'verbose_name_plural': 'Logs Système',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'level'], name='vendors_sys_created_f6300d_idx'), models.Index(fields=['-created_at', 'service'], name='vendors_sys_created_4ed7e8_idx')],
            },
        ),
    ]
