# Generated by Django 5.1.15 on 2026-08-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_systemlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorlocation',
            options={'ordering': ['-is_main', 'name'], 'verbose_name': 'Emplacement de boutique', 'verbose_name_plural': 'Emplacements de boutique'},
        ),
        migrations.AddField(
            model_name='vendorlocation',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Un seul emplacement principal par vendeur — les autres sont secondaires.', verbose_name='Centre principal'),
        ),
    ]
