# Generated by Django 5.1.15 on 2026-09-02 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0014_zone_shipment_buyer_confirmed_at_and_more'),
        ('vendors', '0008_alter_vendorlocation_options_vendorlocation_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='shipping.zone', verbose_name='Zone de tarification'),
        ),
    ]
