# Generated by Django 5.1.15 on 2026-09-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_vendorprofile_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='closed_days',
            field=models.JSONField(blank=True, default=list, help_text="Jours de fermeture hebdomadaire du vendeur (0=lundi ... 6=dimanche). Dimanche est toujours ferme, pas besoin de l'ajouter."),
        ),
    ]
