# Generated by Django 5.1.15 on 2026-10-04 23:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EtatPortefeuille",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rembourse",
                    models.PositiveIntegerField(default=0, help_text="argent venu de remboursements et de la cagnotte : retiré sans frais"),
                ),
                (
                    "numero_change_le",
                    models.DateTimeField(blank=True, help_text="dernier changement du numéro du compte : WALLET-NUMERO-ATTENTE", null=True),
                ),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="portefeuille_client", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Portefeuille",
                "verbose_name_plural": "Portefeuilles",
            },
        ),
        migrations.CreateModel(
            name="CarteEnregistree",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("jeton_chiffre", models.BinaryField(help_text="jeton du prestataire (jamais le numéro de carte, CAP-24), chiffré")),
                ("marque", models.CharField(choices=[("Visa", "Visa"), ("Mastercard", "Mastercard")], max_length=12)),
                ("derniers", models.CharField(max_length=4)),
                ("expire", models.CharField(help_text="« 08/29 »", max_length=5)),
                ("titulaire", models.CharField(blank=True, default="", max_length=120)),
                ("pays", models.CharField(blank=True, default="", help_text="pays d'émission donné par le prestataire", max_length=80)),
                ("par_defaut", models.BooleanField(default=False)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cartes_client", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Carte enregistrée",
                "verbose_name_plural": "Cartes enregistrées",
                "ordering": ["cree_le", "pk"],
                "constraints": [models.UniqueConstraint(fields=("client", "marque", "derniers", "expire"), name="wallet_carte_unique")],
            },
        ),
        migrations.CreateModel(
            name="Mouvement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("recharge", "Recharge"),
                            ("remboursement", "Remboursement"),
                            ("paiement", "Paiement d'une commande"),
                            ("cagnotte", "Cagnotte de l'abonnement"),
                            ("retrait", "Retrait (ou retrait rendu)"),
                        ],
                        max_length=14,
                    ),
                ),
                ("montant", models.IntegerField(help_text="positif : crédit ; négatif : débit")),
                ("libelle", models.CharField(max_length=160)),
                (
                    "reference",
                    models.CharField(
                        blank=True, default="", help_text="recharge, retrait, commande… : rend l'écriture unique", max_length=60
                    ),
                ),
                ("le", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="mouvements_portefeuille", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement du portefeuille",
                "verbose_name_plural": "Mouvements du portefeuille",
                "ordering": ["-le", "-pk"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("reference", ""), _negated=True),
                        fields=("client", "type", "reference"),
                        name="wallet_mouvement_reference_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MoyenPaiement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("operateur", models.CharField(choices=[("MTN", "MTN MoMo"), ("Orange", "Orange Money")], max_length=10)),
                ("numero_chiffre", models.BinaryField(help_text="numéro local à 9 chiffres, chiffré (CAP-21)")),
                ("numero_empreinte", models.CharField(help_text="HMAC du numéro local : recherche sans déchiffrer", max_length=64)),
                ("numero_masque", models.CharField(help_text="« 6 77 ·· ·· 41 »", max_length=40)),
                ("verifie_le", models.DateTimeField(blank=True, help_text="vide tant que le code SMS n'est pas saisi", null=True)),
                ("par_defaut", models.BooleanField(default=False)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="moyens_mobile_money", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Moyen de paiement Mobile Money",
                "verbose_name_plural": "Moyens de paiement Mobile Money",
                "ordering": ["cree_le", "pk"],
                "constraints": [models.UniqueConstraint(fields=("client", "numero_empreinte"), name="wallet_moyen_unique")],
            },
        ),
        migrations.CreateModel(
            name="Recharge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("montant", models.PositiveIntegerField()),
                ("restant", models.PositiveIntegerField(default=0, help_text="ce qui reste de cette recharge dans le solde")),
                ("a_servi", models.BooleanField(default=False, help_text="a payé (en partie) une commande : retirable sans attendre")),
                ("reference", models.CharField(help_text="référence envoyée à l'agrégateur (RCH-…)", max_length=60, unique=True)),
                ("operateur", models.CharField(choices=[("MTN", "MTN MoMo"), ("Orange", "Orange Money")], max_length=10)),
                ("numero_chiffre", models.BinaryField(help_text="numéro local, chiffré (CAP-21) : pour rendre ou verser l'argent")),
                ("numero_masque", models.CharField(max_length=40)),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("attente", "Demande envoyée, en attente de l'opérateur"),
                            ("confirmee", "Confirmée (webhook signé, CWL-03) : créditée"),
                            ("echec", "Refusée ou expirée"),
                            ("rendue", "Encaissée mais refusée par les règles (plafond) : rendue au numéro"),
                        ],
                        default="attente",
                        max_length=10,
                    ),
                ),
                ("demandee_le", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "confirmee_le",
                    models.DateTimeField(blank=True, help_text="instant du crédit : départ de WALLET-RECHARGE-ATTENTE", null=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="recharges_portefeuille", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Recharge du portefeuille",
                "verbose_name_plural": "Recharges du portefeuille",
                "ordering": ["confirmee_le", "pk"],
                "indexes": [models.Index(fields=["client", "etat"], name="wallet_rech_client__11c2cf_idx")],
            },
        ),
        migrations.CreateModel(
            name="Retrait",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("montant", models.PositiveIntegerField(help_text="débité du solde")),
                (
                    "part_rechargee",
                    models.PositiveIntegerField(help_text="prise sur l'argent rechargé : compte pour le retrait gratuit du mois"),
                ),
                ("part_remboursee", models.PositiveIntegerField()),
                ("frais", models.PositiveIntegerField(default=0, help_text="WALLET-RETRAIT-FRAIS, retenus sur le montant versé")),
                ("prises", models.JSONField(blank=True, default=list, help_text="[{recharge: id, prise: F}] : pour rendre à l'identique")),
                ("reference", models.CharField(max_length=60, unique=True)),
                ("operateur", models.CharField(choices=[("MTN", "MTN MoMo"), ("Orange", "Orange Money")], max_length=10)),
                ("numero_chiffre", models.BinaryField(help_text="numéro local, chiffré (CAP-21) : pour rendre ou verser l'argent")),
                ("numero_masque", models.CharField(max_length=40)),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("en_cours", "Versement demandé"),
                            ("verse", "Versé"),
                            ("echec", "Versement refusé : rendu au portefeuille"),
                        ],
                        default="en_cours",
                        max_length=10,
                    ),
                ),
                ("le", models.DateTimeField(default=django.utils.timezone.now)),
                ("verse_au_plus_tard", models.DateTimeField(blank=True, help_text="WALLET-RETRAIT-H", null=True)),
                ("verse_le", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="retraits_portefeuille", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Retrait du portefeuille",
                "verbose_name_plural": "Retraits du portefeuille",
                "ordering": ["le", "pk"],
                "indexes": [models.Index(fields=["client", "le"], name="wallet_retr_client__876c38_idx")],
            },
        ),
    ]
