# Generated by Django 5.1.15 on 2026-10-04 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeOtp",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "objet",
                    models.CharField(
                        choices=[
                            ("verify", "Premier numéro"),
                            ("numero-ancien", "Changement de numéro : ancien"),
                            ("numero-nouveau", "Changement de numéro : nouveau"),
                            ("profil", "Profil"),
                            ("email-sms", "Changement d'e-mail : code par SMS"),
                            ("email-adresse", "Changement d'e-mail : code à la nouvelle adresse"),
                            ("moyen", "Nouveau numéro Mobile Money"),
                            ("suppression", "Suppression du compte"),
                            ("diaspora", "Inscription diaspora"),
                            ("cadeau", "Cadeau payé par carte (vérification renforcée)"),
                            ("diaspora-renforce", "Commande diaspora (vérification renforcée)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "canal",
                    models.CharField(choices=[("sms", "SMS"), ("whatsapp", "WhatsApp"), ("email", "E-mail")], default="sms", max_length=10),
                ),
                ("destination_empreinte", models.CharField(db_index=True, max_length=64)),
                ("destination_masquee", models.CharField(max_length=120)),
                ("code_empreinte", models.CharField(max_length=64)),
                ("essais", models.PositiveSmallIntegerField(default=0)),
                ("bloque_jusqua", models.DateTimeField(blank=True, null=True)),
                ("expire_le", models.DateTimeField()),
                ("utilise_le", models.DateTimeField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes_otp_client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Code à usage unique",
                "verbose_name_plural": "Codes à usage unique",
                "indexes": [models.Index(fields=["objet", "destination_empreinte", "cree_le"], name="otp_codeotp_objet_218021_idx")],
            },
        ),
        migrations.CreateModel(
            name="JetonMdp",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("jeton_empreinte", models.CharField(max_length=64, unique=True)),
                ("expire_le", models.DateTimeField()),
                ("utilise_le", models.DateTimeField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="jetons_mdp_client", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien de nouveau mot de passe",
                "verbose_name_plural": "Liens de nouveau mot de passe",
                "indexes": [models.Index(fields=["utilisateur", "cree_le"], name="otp_jetonmd_utilisa_f1db22_idx")],
            },
        ),
    ]
