# Generated by Django 5.2.10 on 2026-02-08 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_dispute_disputeevidence_disputemessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_fees', models.JSONField(default=dict)),
                ('platform_commission_percent', models.DecimalField(decimal_places=2, default=10.0, help_text='Commission prélevée sur chaque vente (en %)', max_digits=5)),
                ('minimum_order_amount_xaf', models.IntegerField(default=1000)),
                ('default_delivery_days', models.IntegerField(default=3)),
                ('mtn_momo_enabled', models.BooleanField(default=True)),
                ('orange_money_enabled', models.BooleanField(default=True)),
                ('admin_email', models.EmailField(default='admin@relaya.cm', max_length=254)),
                ('support_email', models.EmailField(default='support@relaya.cm', max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètres Plateforme',
                'verbose_name_plural': 'Paramètres Plateforme',
            },
        ),
    ]
