# Generated by Codex on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_platformsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("DELIVERY", "Livraison"),
                    ("PICKUP", "Retrait en boutique"),
                ],
                default="DELIVERY",
                max_length=20,
                verbose_name="Mode de reception",
            ),
        ),
    ]
