# Generated by Django 5.1.15 on 2026-04-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_rate_snapshot',
            field=models.DecimalField(decimal_places=2, default=12.0, help_text='Copie du taux en vigueur au moment de la commande.', max_digits=5, verbose_name='Taux de commission appliqué (%)'),
        ),
        migrations.AddField(
            model_name='order',
            name='escrow_status',
            field=models.CharField(choices=[('PENDING', 'En attente de paiement'), ('BLOCKED', 'Fonds sécurisés en escrow'), ('RELEASE_PENDING', 'Libération en cours (24h)'), ('RELEASED', 'Fonds libérés au vendeur'), ('REFUNDED', 'Remboursement total'), ('PARTIAL_REFUNDED', 'Remboursement partiel')], default='PENDING', max_length=20, verbose_name="Statut de l'escrow"),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_reply_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Délai de réponse vendeur'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='escrow_auto_confirm_h',
            field=models.PositiveIntegerField(default=48, help_text='Délai après livraison avant auto-confirmation sans litige.', verbose_name='Auto-confirmation escrow (h)'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='escrow_release_h',
            field=models.PositiveIntegerField(default=24, help_text='Délai entre confirmation et libération effective des fonds.', verbose_name='Délai libération escrow (h)'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='litige_window_days',
            field=models.PositiveIntegerField(default=7, help_text="Jours après livraison pendant lesquels l'acheteur peut ouvrir un litige.", verbose_name='Fenêtre litige (jours)'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='mobile_money_fee_percent',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Frais MTN/Orange négociés.', max_digits=4, verbose_name='Frais Mobile Money (%)'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='vendor_reply_h',
            field=models.PositiveIntegerField(default=72, verbose_name='Délai réponse vendeur (h)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('CREATED', 'Commande créée'), ('PAID_IN_ESCROW', 'Payée · Escrow bloqué'), ('VENDOR_ACKNOWLEDGED', 'Confirmée par le vendeur'), ('PREPARING', 'En préparation'), ('READY_FOR_PICKUP', 'Prête pour enlèvement'), ('DRIVER_ASSIGNED', 'Livreur assigné'), ('PICKED_UP', 'Pris en charge par le livreur'), ('OUT_FOR_DELIVERY', 'En cours de livraison'), ('DELIVERED', 'Livré'), ('BUYER_CONFIRMED', "Réception confirmée par l'acheteur"), ('AUTO_CONFIRMED', 'Confirmée automatiquement (48h)'), ('RELEASED_TO_VENDOR', 'Fonds libérés au vendeur'), ('DISPUTED', 'Litige ouvert'), ('CANCELLED', 'Annulée'), ('REFUNDED', 'Remboursée')], default='CREATED', max_length=30, verbose_name='Statut de livraison'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='admin_email',
            field=models.EmailField(default='admin@belivay.cm', max_length=254),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='default_delivery_days',
            field=models.IntegerField(default=3, verbose_name='Délai livraison par défaut (jours)'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='delivery_fees',
            field=models.JSONField(default=dict, help_text='Ex : {"Yaoundé": 1500, "Douala": 2000, "default": 2500}', verbose_name='Frais de livraison (FCFA/ville)'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='minimum_order_amount_xaf',
            field=models.IntegerField(default=5000, verbose_name='Montant minimum commande (FCFA)'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='mtn_momo_enabled',
            field=models.BooleanField(default=True, verbose_name='MTN MoMo activé'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='orange_money_enabled',
            field=models.BooleanField(default=True, verbose_name='Orange Money activé'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='platform_commission_percent',
            field=models.DecimalField(decimal_places=2, default=12.0, help_text="Ne s'applique qu'aux nouvelles commandes.", max_digits=5, verbose_name='Commission plateforme (%)'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='support_email',
            field=models.EmailField(default='support@belivay.cm', max_length=254),
        ),
    ]
