# Generated by Django 5.1.15 on 2026-04-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_commission_rate_snapshot_order_escrow_status_and_more'),
        ('orders', '0007_order_delivery_method'),
    ]

    operations = [
    ]
