# Generated by Django 5.1.15 on 2026-04-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_merge_20260410_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('DELIVERY', 'Livraison à domicile'), ('PICKUP', 'Retrait en boutique')], default='DELIVERY', max_length=20, verbose_name='Mode de réception'),
        ),
    ]
