# Generated by Django 5.1.15 on 2026-04-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_merge_20260414_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_method',
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='minimum_withdrawal_amount_xaf',
            field=models.IntegerField(default=1000, help_text="Montant minimum qu'un vendeur peut retirer en une seule demande. Configurable depuis l'interface admin.", verbose_name='Montant minimum de retrait (FCFA)'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='withdrawal_fee_percent',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text="Frais prélevés sur chaque demande de retrait Mobile Money. Taux préférentiel BelivaY (Orange/MTN). Configurable depuis l'interface admin.", max_digits=4, verbose_name='Frais de retrait MoMo (%)'),
        ),
    ]
