# Generated by Django 5.1.15 on 2026-04-14 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_platformsettings_withdrawal_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL, verbose_name='Admin en charge'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='vendor_contacted',
            field=models.BooleanField(default=False, help_text="Passe à True dès que l'admin envoie le premier message au vendeur.", verbose_name='Vendeur contacté'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='vendor_proposed_amount',
            field=models.IntegerField(blank=True, help_text='Rempli uniquement si vendor_reply_type = COMPROMISE.', null=True, verbose_name='Montant proposé par le vendeur (FCFA)'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='vendor_replied',
            field=models.BooleanField(default=False, verbose_name='Vendeur a répondu formellement'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='vendor_replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date réponse vendeur'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='vendor_reply_text',
            field=models.TextField(blank=True, default='', verbose_name='Explication vendeur'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='vendor_reply_type',
            field=models.CharField(blank=True, choices=[('ACCEPT', 'Accepter le remboursement'), ('CONTEST', 'Contester le litige'), ('COMPROMISE', 'Proposer un compromis')], max_length=12, null=True, verbose_name='Type de réponse vendeur'),
        ),
        migrations.AddField(
            model_name='disputemessage',
            name='sender_role',
            field=models.CharField(choices=[('VENDOR', 'Vendeur'), ('ADMIN', 'Admin BelivaY'), ('SYSTEM', 'Système')], default='ADMIN', max_length=10, verbose_name="Rôle de l'expéditeur"),
        ),
        migrations.AlterField(
            model_name='disputemessage',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='True = note interne admin uniquement, invisible pour le vendeur.'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='escrow_auto_confirm_h',
            field=models.IntegerField(default=48, help_text='Heures sans litige après livraison avant confirmation automatique.', verbose_name='Auto-confirmation escrow (h)'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='escrow_release_h',
            field=models.IntegerField(default=24, help_text='Heures après confirmation avant libération des fonds au vendeur.', verbose_name='Libération fonds post-confirmation (h)'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='litige_window_days',
            field=models.IntegerField(default=7, help_text="Jours après livraison pendant lesquels l'acheteur peut ouvrir un litige.", verbose_name='Fenêtre ouverture litige (jours)'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='vendor_reply_h',
            field=models.IntegerField(default=72, help_text="Heures accordées au vendeur pour répondre à un litige avant décision auto en faveur de l'acheteur.", verbose_name='Délai réponse vendeur (h)'),
        ),
    ]
