# Generated by Django 5.1.15 on 2026-04-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_dispute_vendor_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='default_stock_threshold',
            field=models.IntegerField(default=5, help_text="Quantité en dessous de laquelle un produit est signalé comme 'stock faible'. Chaque vendeur peut définir son propre seuil par produit ; si non renseigné, c'est ce seuil global qui s'applique.", verbose_name='Seuil alerte stock par défaut'),
        ),
    ]
