# Generated by Django 5.1.15 — fixed dependency
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0009_platformsettings_withdrawal_fields'),
        ('orders', '0011_platformsettings_stock_threshold'),
    ]
    operations = [
    ]
