# Generated by Django 5.1.15 on 2026-04-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_merge_20260410_0904'),
        ('orders', '0012_merge_20260419_1058'),
    ]

    operations = [
    ]
