# Generated by Django 5.1.15 on 2026-04-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_merge_20260419_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='escrow_auto_confirm_h',
            field=models.PositiveIntegerField(default=48, help_text='Délai après livraison avant auto-confirmation sans litige.', verbose_name='Auto-confirmation escrow (h)'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='escrow_release_h',
            field=models.PositiveIntegerField(default=24, help_text='Délai entre confirmation et libération effective des fonds.', verbose_name='Délai libération escrow (h)'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='litige_window_days',
            field=models.PositiveIntegerField(default=7, help_text="Jours après livraison pendant lesquels l'acheteur peut ouvrir un litige.", verbose_name='Fenêtre litige (jours)'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='vendor_reply_h',
            field=models.PositiveIntegerField(default=72, verbose_name='Délai réponse vendeur (h)'),
        ),
    ]
