# Generated by Django 5.1.15 on 2026-05-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_repair_missing_delivery_method_column'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='order',
                    name='delivery_method',
                    field=models.CharField(choices=[('DELIVERY', 'Livraison'), ('PICKUP', 'Retrait en boutique')], default='DELIVERY', max_length=20, verbose_name='Mode de livraison'),
                ),
            ],
        ),
    ]
