# Generated by Django 5.1.15 on 2026-06-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_merge_0016_dispute_can_reply_flags_0016_order_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='max_offers_displayed',
            field=models.PositiveIntegerField(default=7, help_text="Nombre maximum d'offres vendeurs visibles sur une fiche produit (côté acheteur).", verbose_name="Nombre d'offres affichées par fiche"),
        ),
    ]
