# Generated by Django 5.1.15 on 2026-07-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_disputemessage_client_courier_roles'),
        ('orders', '0018_platformsettings_max_offers_displayed'),
    ]

    operations = [
    ]
