# Generated by Django 5.1.15 on 2026-08-14 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_disputemessage_logistics_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeEvidenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_role', models.CharField(choices=[('CLIENT', 'Client'), ('VENDOR', 'Vendeur'), ('COURIER', 'Livreur'), ('LOGISTICS', 'Organisation logistique'), ('RELAY_POINT', 'Point relais')], max_length=20)),
                ('evidence_types', models.JSONField(blank=True, default=list)),
                ('instructions', models.TextField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUBMITTED', 'Reçue'), ('CANCELLED', 'Annulée'), ('EXPIRED', 'Expirée')], default='PENDING', max_length=12)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='dispute',
            new_name='orders_disp_order_i_89d953_idx',
            old_name='orders_disp_order_i_1bfe29_idx',
        ),
        migrations.AddField(
            model_name='disputeevidence',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='disputeevidence',
            name='evidence_type',
            field=models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Vidéo'), ('DOCUMENT', 'Document'), ('OTHER', 'Autre')], default='PHOTO', max_length=16),
        ),
        migrations.AddField(
            model_name='disputeevidence',
            name='sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='disputeevidence',
            name='size_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disputeevidence',
            name='uploader_role',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='reason',
            field=models.CharField(choices=[('NOT_RECEIVED', 'Commande non reçue'), ('DAMAGED', 'Article endommagé'), ('WRONG_ITEM', 'Mauvais article'), ('NOT_AS_DESCRIBED', 'Non conforme à la description'), ('COUNTERFEIT', 'Suspicion de contrefaçon'), ('REFUND_REQUEST', 'Demande de remboursement'), ('OTHER', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='disputemessage',
            name='sender_role',
            field=models.CharField(choices=[('VENDOR', 'Vendeur'), ('ADMIN', 'Admin BelivaY'), ('CLIENT', 'Client'), ('COURIER', 'Livreur'), ('LOGISTICS', 'Organisation logistique'), ('RELAY_POINT', 'Point relais'), ('SYSTEM', 'Système')], default='ADMIN', max_length=20, verbose_name="Rôle de l'expéditeur"),
        ),
        migrations.AddField(
            model_name='disputeevidencerequest',
            name='dispute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_requests', to='orders.dispute'),
        ),
        migrations.AddField(
            model_name='disputeevidencerequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_evidence_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputeevidencerequest',
            name='requested_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_evidence_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputeevidence',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='orders.disputeevidencerequest'),
        ),
        migrations.AddIndex(
            model_name='disputeevidencerequest',
            index=models.Index(fields=['requested_from', 'status'], name='orders_disp_request_8c68a8_idx'),
        ),
    ]
