# Generated by Django 5.1.15 on 2026-08-15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_disputeevidencerequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='evidence_retention_days',
            field=models.PositiveIntegerField(
                default=8,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name='Conservation des preuves colis (jours)',
                help_text=(
                    "Délai après lequel une preuve de livraison (ShipmentEvidence) sans litige "
                    "ouvert est purgée. Sans effet sur une preuve déjà gelée par un litige actif."
                ),
            ),
        ),
    ]
