# Generated by Django 5.1.15 on 2026-08-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_order_address_precision'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dispute',
            new_name='orders_disp_order_i_1bfe29_idx',
            old_name='orders_disp_order_i_89d953_idx',
        ),
    ]
