# Generated by Django 5.1.15 on 2026-08-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_rename_orders_disp_order_i_89d953_idx_orders_disp_order_i_1bfe29_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Position GPS donnée par le client au checkout, en complément de l'adresse.", max_digits=9, null=True, verbose_name='Latitude de livraison'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude de livraison'),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quartier'),
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(blank=True, max_length=50, verbose_name='Région'),
        ),
    ]
