# Generated by Django 5.1.15 on 2026-09-01 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_order_delivery_latitude_order_delivery_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputeevidence',
            name='message',
            field=models.ForeignKey(blank=True, help_text='Message du fil de discussion auquel cette photo était jointe, le cas échéant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='orders.disputemessage'),
        ),
        migrations.AddField(
            model_name='order',
            name='authorized_pickup_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Nom du tiers autorisé au retrait'),
        ),
        migrations.AddField(
            model_name='order',
            name='authorized_pickup_phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Téléphone du tiers autorisé au retrait'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='reason',
            field=models.CharField(choices=[('NOT_RECEIVED', 'Commande non reçue'), ('DAMAGED', 'Article endommagé'), ('WRONG_ITEM', 'Mauvais article'), ('NOT_AS_DESCRIBED', 'Non conforme à la description'), ('COUNTERFEIT', 'Suspicion de contrefaçon'), ('REFUND_REQUEST', 'Demande de remboursement'), ('PAYMENT_NOT_RECOGNIZED', 'Paiement non reconnu'), ('OTHER', 'Autre')], max_length=50),
        ),
    ]
