# Generated by Django 5.1.15 on 2026-09-02 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_relaypointprofile_latitude_and_more'),
        ('orders', '0027_disputeevidence_message_order_authorized_pickup_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='relay_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.relaypointprofile', verbose_name='Point relais choisi'),
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('DAMAGED', 'Article endommagé'), ('NOT_AS_DESCRIBED', 'Non conforme à la description'), ('WRONG_ITEM', 'Mauvais article reçu'), ('COUNTERFEIT', 'Suspicion de contrefaçon'), ('OTHER', 'Autre')], max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('REQUESTED', 'Demande de retour'), ('APPROVED', 'Retour approuvé'), ('REJECTED', 'Retour rejeté'), ('AWAITING_DROPOFF', 'En attente de dépôt/ramassage'), ('RECEIVED', 'Colis reçu — inspection en cours'), ('REFUNDED', 'Remboursé'), ('CLOSED_NO_REFUND', 'Clôturé sans remboursement')], default='REQUESTED', max_length=20)),
                ('transport_mode', models.CharField(choices=[('RELAY_DROPOFF', 'Dépôt en point relais'), ('COURIER_PICKUP', 'Ramassage à domicile')], default='RELAY_DROPOFF', help_text='Dépôt en point relais par défaut ; ramassage réservé aux colis encombrants.', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('inspection_passed', models.BooleanField(blank=True, null=True)),
                ('inspection_note', models.TextField(blank=True, default='')),
                ('refund_amount_xaf', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dropoff_relay_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_dropoffs', to='accounts.relaypointprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.orderitem')),
                ('received_by', models.ForeignKey(blank=True, help_text='Point relais ou admin ayant constaté la réception physique du colis retourné.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_returns', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_returns', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Vendeur ou admin ayant approuvé/rejeté la demande initiale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_returns', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, help_text='Vendeur du produit retourné, dérivé de order_item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retour',
                'verbose_name_plural': 'Retours',
                'ordering': ['-created_at'],
            },
        ),
    ]
