# Generated by Django 5.1.15 on 2026-09-02 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_order_relay_point_return'),
        ('shipping', '0014_zone_shipment_buyer_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Resolue depuis city+district au checkout (Zone.match). None si aucune zone ne couvre ce quartier.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shipping.zone', verbose_name='Zone de livraison'),
        ),
    ]
