# Generated by Django 5.1.15 on 2026-09-02 03:51

import apps.orders.models
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_apply_addendum_timing_decisions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # dispute_evidence_retention_days doit exister avant retain_until, dont le
        # defaut callable (dispute_evidence_retention_deadline) lit PlatformSettings.
        migrations.AddField(
            model_name='platformsettings',
            name='dispute_evidence_retention_days',
            field=models.PositiveIntegerField(default=60, help_text='Délai après lequel une preuve jointe à un litige (DisputeEvidence) est purgée automatiquement. Verrouillé à 60 jours — Addendum Décisions v1.0 §4.4.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Conservation des preuves de litige (jours)'),
        ),
        migrations.AddField(
            model_name='disputeevidence',
            name='litigation_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disputeevidence',
            name='purged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disputeevidence',
            name='retain_until',
            field=models.DateTimeField(default=apps.orders.models.dispute_evidence_retention_deadline),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='escrow_auto_confirm_h',
            field=models.PositiveIntegerField(default=96, help_text='Délai après remise avant auto-confirmation sans litige. Verrouillé à 4 jours (96h) — Addendum Décisions v1.0 §3.1.', verbose_name='Auto-confirmation escrow (h)'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='escrow_release_h',
            field=models.PositiveIntegerField(default=72, help_text='Délai entre clôture du droit de retour (confirmation ou auto-confirmation) et libération effective des fonds. Verrouillé à J+3 (72h) — Addendum Décisions v1.0 §3.1.', verbose_name='Délai libération escrow (h)'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='litige_window_days',
            field=models.PositiveIntegerField(default=4, help_text="Jours après la remise pendant lesquels l'acheteur peut ouvrir un litige. Verrouillé à 4 jours, calé sur l'auto-confirmation — Addendum Décisions v1.0 §4.4.", verbose_name='Fenêtre litige (jours)'),
        ),
        migrations.AddIndex(
            model_name='disputeevidence',
            index=models.Index(fields=['retain_until', 'litigation_hold', 'purged_at'], name='orders_disp_retain__c2e244_idx'),
        ),
    ]
