# Generated by Django 5.1.15 on 2026-09-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_disputeevidence_litigation_hold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prep_admin_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='prep_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Délai de préparation (bon de préparation)'),
        ),
        migrations.AddField(
            model_name='order',
            name='prep_reassignment_flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='prep_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
