# Generated by Django 5.1.15 on 2026-09-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_order_prep_admin_alert_sent_at_order_prep_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='silence_flagged_at',
            field=models.DateTimeField(blank=True, help_text="Le vendeur n'a pas répondu sous 48h : arbitrage BelivaY sur pièces, présomption favorable à l'acheteur (pas un gain automatique).", null=True, verbose_name='Signalé pour arbitrage sur silence'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='vendor_reply_deadline',
            field=models.DateTimeField(blank=True, help_text="Démarre au contact vendeur (vendor_contacted=True), pas à l'ouverture du litige.", null=True, verbose_name='Délai de réponse vendeur (48h)'),
        ),
    ]
