// Gestes repris du prototype sur les écrans construits (src/composants/interactions.ts, MenuProfil) :
// chaque geste répond sur place, comme dans le prototype, sans changer d'écran.
import { readFileSync } from 'node:fs'
import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
})

test('un interrupteur s’allume et s’éteint ; un interrupteur verrouillé ne bouge pas', async ({ page }) => {
  await page.goto('/notifs-reglages')
  const messages = page.locator('button.tg[aria-label="Messages"]').first()
  await expect(messages).toHaveAttribute('aria-checked', 'true')
  await messages.click()
  await expect(messages).toHaveAttribute('aria-checked', 'false')
  await expect(messages).not.toHaveClass(/\bon\b/)
  await messages.click()
  await expect(messages).toHaveAttribute('aria-checked', 'true')
  const verrou = page.locator('button.tg.lock').first()
  await verrou.click()
  await expect(verrou).toHaveAttribute('aria-checked', 'true')
})

test('un choix vers l’écran ouvert s’allume sur place, sans changer d’adresse', async ({ page }) => {
  // DP-54 : les choix sont des radios réels ; toucher l'un l'allume, éteint l'autre, l'adresse ne bouge pas.
  await page.goto('/changer-relais?ref=BLV-52107')
  const choix = page.locator('a.cl12-rc[role=radio]')
  await choix.nth(0).click()
  await expect(choix.nth(0)).toHaveAttribute('aria-checked', 'true')
  await choix.nth(1).click()
  await expect(choix.nth(1)).toHaveAttribute('aria-checked', 'true')
  await expect(choix.nth(0)).toHaveAttribute('aria-checked', 'false')
  await expect(page).toHaveURL(/\/changer-relais\?ref=BLV-52107$/)
})

test('l’avatar ouvre le menu du profil ; le voile le ferme', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('#av-pop')).toHaveCount(0)
  await page.locator('header.hd .hd-av').click()
  await expect(page.locator('#av-pop')).toBeVisible()
  await expect(page).toHaveURL(/pop=profil/)
  await expect(page.locator('#av-pop')).toContainText('Carine Mballa')
  await page.locator('#av-pop-veil').click({ position: { x: 20, y: 400 } })
  await expect(page.locator('#av-pop')).toHaveCount(0)
  await expect(page).not.toHaveURL(/pop=profil/)
})

test('le menu du profil s’ouvre aussi depuis un autre écran à en-tête racine', async ({ page }) => {
  await page.goto('/categories')
  await page.locator('header.hd .hd-av').click()
  await expect(page.locator('#av-pop')).toBeVisible()
  // Les entrées des modules suivent leur interrupteur (CCH-18) ; tous ouverts depuis DP-50.
  await expect(page.locator('#av-pop a[href="/ventes-flash"]')).toHaveCount(1)
  await expect(page.locator('#av-pop a[href="/wallet"]')).toHaveCount(1)
})

// DP-52 : l'œil de la carte du portefeuille masque le solde sur place, et le choix vaut partout.
test('l’œil du portefeuille masque le solde sur place, sans changer d’écran', async ({ page }) => {
  await page.goto('/compte')
  await expect(page.locator('.wl-bal')).toContainText('45')
  await page.locator('.wl-h [aria-label="Masquer le solde"]').click()
  await expect(page).toHaveURL(/\/compte$/)
  await expect(page.locator('.wl-bal')).toHaveText(/^•• •••\s*F$/)
  await expect(page.locator('.wl-sub')).toContainText('•• ••• F')
  await page.goto('/menu')
  await expect(page.locator('.wl-bal')).toHaveText(/^•• •••\s*F$/)
  await page.goto('/wallet')
  await page.locator('.wl-h [aria-label="Afficher le solde"]').click()
  await expect(page.locator('.wl-bal')).toContainText('45')
})

// DP-52 : modifier son profil, confirmé par un code par SMS (CIN-33, CIN-34).
test('le profil se modifie avec un code : prénom requis, code faux puis bon code, nom changé partout', async ({ page }) => {
  await page.goto('/compte')
  await page.locator('[aria-label="Modifier mon profil"]').click()
  await expect(page).toHaveURL(/\/profil$/)
  await page.fill('#pf-prenom', '')
  await page.getByRole('button', { name: 'Enregistrer' }).click()
  await expect(page.locator('.fld').first()).toContainText('Ton prénom est demandé')
  await expect(page).toHaveURL(/\/profil$/)
  await page.fill('#pf-prenom', 'Aïcha')
  await page.getByRole('button', { name: 'Enregistrer' }).click()
  await expect(page).toHaveURL(/\/profil\?st=code$/)
  await page.locator('.otp-saisie input').fill('000000')
  await page.getByRole('button', { name: 'Enregistrer mon profil' }).click()
  await expect(page.locator('.cl03-otpm')).toHaveText('Ce code ne correspond pas. Encore 4 essais.')
  await page.locator('.otp-saisie input').fill('503917')
  await page.getByRole('button', { name: 'Enregistrer mon profil' }).click()
  await expect(page).toHaveURL(/\/profil\?st=ok$/)
  await expect(page.locator('.card')).toContainText('Prénom')
  await page.getByRole('link', { name: 'Retour à mon compte' }).click()
  await expect(page.locator('.cl13-pf h1')).toHaveText('Aïcha Mballa')
  await page.reload()
  await expect(page.locator('.cl13-pf h1')).toHaveText('Aïcha Mballa')
})

test('l’e-mail change avec deux codes : un par SMS, un à la nouvelle adresse', async ({ page }) => {
  await page.goto('/profil-email')
  await page.fill('#pf-email', 'carine@gmail.com')
  await page.getByRole('button', { name: 'Continuer' }).click()
  await expect(page.locator('.fld .hint')).toHaveText('C’est déjà ton adresse e-mail.')
  await page.fill('#pf-email', 'carine.mballa@yahoo.fr')
  await page.getByRole('button', { name: 'Continuer' }).click()
  await expect(page).toHaveURL(/etape=2$/)
  await expect(page.locator('.pg-s')).toContainText('6 77')
  await page.locator('.otp-saisie input').fill('503917')
  await page.getByRole('button', { name: 'Continuer' }).click()
  await expect(page).toHaveURL(/etape=3$/)
  await expect(page.locator('.pg-s')).toContainText('c•••••@yahoo.fr')
  await expect(page.locator('.otp-saisie input')).toHaveValue('')
  await page.locator('.otp-saisie input').fill('284615')
  await page.getByRole('button', { name: 'Changer mon e-mail' }).click()
  await expect(page).toHaveURL(/st=ok$/)
  await page.goto('/compte')
  await expect(page.locator('.cl13-pf')).toContainText('c•••••@yahoo.fr')
})

// DP-53 : le compte suit ses données, la déconnexion ferme la session, les pages du compte demandent la connexion.
test('le compte suit ses données : compteurs à 0 masqués, solde, relais, messages', async ({ page }) => {
  await page.addInitScript(() => {
    if (sessionStorage.getItem('pose')) return
    sessionStorage.setItem('pose', '1')
    const e = {
      v: 1,
      compteurs: { commandes: 7, litiges: 0, messagesNonLus: 3, sauvegardes: 0, factures: 0 },
      portefeuille: { rembourse: 12500, recharges: [], cagnotteEnAttente: 0 },
      relais: { nom: 'Relais Bastos', gerant: 'M. Abena', horaires: '9 h – 20 h', acces: '1,2 km, 15 min à pied' },
      factures: { factures: [], annulees: [] },
    }
    localStorage.setItem('blv_demo_etat', JSON.stringify(e))
  })
  await page.goto('/compte')
  await expect(page.locator('a.cl13-tile[href="/commandes"] .n')).toHaveText('7')
  await expect(page.locator('a.cl13-tile[href="/litiges"] .n')).toHaveCount(0)
  await expect(page.locator('.wl-bal')).toContainText('12 500')
  await expect(page.locator('.cl13-relc')).toContainText('Relais Bastos')
  await expect(page.locator('a.li[href="/messagerie"]')).toContainText('1 message non lu')
  await expect(page.locator('a.li[href="/factures"]')).toContainText('Aucune facture pour l’instant')
})

test('se déconnecter puis se reconnecter : visiteur, connexion demandée, retour à la page', async ({ page }) => {
  await page.goto('/compte')
  await page.getByRole('button', { name: 'Se déconnecter' }).click()
  await page.locator('.sheet').getByRole('button', { name: 'Se déconnecter' }).click()
  await expect(page).toHaveURL(/\/$/)
  await expect(page.locator('header.hd .hd-av')).toHaveAttribute('aria-label', 'Se connecter')
  await page.goto('/adresses')
  await expect(page).toHaveURL(/\/connexion\?next=%2Fadresses$/)
  await page.goto('/aide')
  await expect(page).toHaveURL(/\/aide$/)
  await page.goto('/compte')
  await page.getByRole('link', { name: 'Continuer avec Google' }).click()
  await page.locator('.cl03-acct').first().click()
  await page.getByRole('link', { name: 'Ouvrir mon compte' }).click()
  await expect(page).toHaveURL(/\/compte$/)
  await expect(page.locator('.cl13-pf h1')).toHaveText('Carine Mballa')
})

// DP-53 : changer de numéro avec deux codes (CIN-39), numéro contrôlé (CIN-35), codes renouvelés (CIN-40).
test('changer de numéro : code à l’ancien, numéro contrôlé, code au nouveau, compte mis à jour', async ({ page }) => {
  await page.goto('/numero-changer?etape=3')
  await expect(page).toHaveURL(/\/numero-changer$/)
  await page.locator('.otp-saisie input').fill('503917')
  await page.getByRole('button', { name: 'Valider', exact: true }).click()
  await expect(page).toHaveURL(/etape=2$/)
  await page.fill('#nc-numero', '699000000')
  await page.getByRole('button', { name: 'Recevoir le code' }).click()
  await expect(page.locator('.fld [role=alert]')).toContainText('déjà vérifié sur un autre compte')
  await page.fill('#nc-numero', '655214708')
  await expect(page.locator('.cl03-op')).toHaveText('Orange Money')
  await page.getByRole('button', { name: 'Recevoir le code' }).click()
  await expect(page).toHaveURL(/etape=3$/)
  await expect(page.locator('.pg-s')).toContainText('6 55 ·· ·· 08 · Orange')
  await page.locator('.otp-saisie input').fill('503917')
  await page.getByRole('button', { name: 'Valider mon nouveau numéro' }).click()
  await expect(page).toHaveURL(/etape=4$/)
  await expect(page.locator('.cl03-done')).toContainText('6 55 ·· ·· 08')
  await expect(page.locator('.card').last()).toContainText('BLV-52018')
  await page.goto('/compte')
  await expect(page.locator('.cl13-pf')).toContainText('6 55 ·· ·· 08')
})

// DP-53 : adresses de livraison réelles (CCO-10, CCO-11) : champs vérifiés, zone servie, défaut, suppression.
test('adresses : ajout vérifié, hors zone refusé, adresse par défaut, suppression confirmée', async ({ page }) => {
  await page.goto('/adresses')
  await page.getByRole('link', { name: 'Ajouter une adresse' }).click()
  await expect(page).toHaveURL(/st=ajout$/)
  await page.locator('.btn.primary', { hasText: 'Enregistrer l’adresse' }).click()
  await expect(page.locator('.fld').first()).toContainText('Donne un nom à cette adresse')
  await page.fill('#ad-nom', 'Travail')
  await page.fill('#ad-quartier', 'Akwa, Douala')
  await expect(page.locator('main')).toContainText('BelivaY ne livre pas encore à Douala')
  await expect(page.locator('.btn.primary', { hasText: 'Enregistrer l’adresse' })).toHaveClass(/\boff\b/)
  await page.fill('#ad-quartier', 'Bastos')
  await expect(page.locator('.inp.ok .suf')).toHaveText('Zone servie')
  await page.fill('#ad-reperes', 'pharmacie du Golf, portail vert')
  await page.locator('button.cl13-map').click()
  await page.locator('.btn.primary', { hasText: 'Enregistrer l’adresse' }).click()
  await expect(page).toHaveURL(/\/adresses$/)
  await expect(page.locator('.card')).toHaveCount(2)
  await expect(page.locator('main')).toContainText('Bastos, pharmacie du Golf, portail vert')
  await page.getByRole('button', { name: 'Utiliser par défaut' }).click()
  await expect(page.locator('.card').first()).toContainText('Travail')
  await page.goto('/compte')
  await expect(page.locator('a.li[href="/adresses"]')).toContainText('Travail · Bastos, pharmacie du Golf')
  await page.goto('/adresses')
  await page.locator('.card').first().getByRole('link', { name: 'Modifier' }).click()
  await page.getByRole('button', { name: 'Supprimer cette adresse' }).click()
  await page.locator('.sheet').getByRole('button', { name: 'Supprimer' }).click()
  await expect(page).toHaveURL(/\/adresses$/)
  await expect(page.locator('.card')).toHaveCount(1)
  await expect(page.locator('.card')).toContainText('Maison')
})

// DP-53 : moyens de paiement réels (CCO-14, CCO-15, CIN-43).
test('moyens de paiement : ajout par code SMS, par défaut, retrait confirmé, numéro du compte gardé', async ({ page }) => {
  await page.goto('/moyens-paiement')
  await expect(page.locator('.cl13-pm')).toHaveCount(2)
  await page.getByRole('link', { name: 'Ajouter un numéro Mobile Money' }).click()
  await page.fill('#mp-numero', '655000008')
  await page.getByRole('button', { name: 'Recevoir le code' }).click()
  await expect(page.locator('.sheet [role=alert]')).toHaveText('Ce numéro est déjà dans tes moyens de paiement.')
  await page.fill('#mp-numero', '681234567')
  await expect(page.locator('.sheet .cl03-op')).toHaveText('MTN MoMo')
  await page.getByRole('button', { name: 'Recevoir le code' }).click()
  await page.locator('.sheet .otp-saisie input').fill('503917')
  await page.getByRole('button', { name: 'Ajouter ce numéro' }).click()
  await expect(page).toHaveURL(/\/moyens-paiement$/)
  await expect(page.locator('.cl13-pm')).toHaveCount(3)
  await expect(page.locator('.hint-l').first()).toContainText('Tous tes numéros sont vérifiés')
  await page.locator('.cl13-pm', { hasText: '6 81 ·· ·· 67' }).click()
  await page.getByRole('button', { name: 'Payer par défaut avec ce numéro' }).click()
  await expect(page.locator('.cl13-pm', { hasText: '6 81 ·· ·· 67' }).locator('.def')).toHaveText('par défaut')
  await page.locator('.cl13-pm', { hasText: '6 81 ·· ·· 67' }).click()
  await page.getByRole('button', { name: 'Retirer ce numéro' }).click()
  await page.locator('.sheet').getByRole('button', { name: 'Retirer', exact: true }).click()
  await expect(page.locator('.cl13-pm')).toHaveCount(2)
  await expect(page.locator('.cl13-pm', { hasText: '6 77 ·· ·· 41' }).locator('.def')).toHaveText('par défaut')
  await page.locator('.cl13-pm', { hasText: '6 77 ·· ·· 41' }).click()
  await expect(page.locator('.sheet')).not.toContainText('Retirer ce numéro')
  await expect(page.locator('.sheet').getByRole('link', { name: 'Changer de numéro' })).toBeVisible()
})

// DP-53 : portefeuille réel (moteurs/portefeuille.py) : recharge, retrait, 72 h, frais du 2e retrait du mois.
test('portefeuille : recharge créditée, retrait limité au retirable, frais du deuxième retrait', async ({ page }) => {
  // Horloge de la démonstration : le jeudi 24 sept. du jeu d'essai (src/demo/horloge.ts).
  await page.goto('/wallet')
  await expect(page.locator('.wl-bal')).toContainText('45 000')
  await page.getByRole('link', { name: 'Recharger' }).first().click()
  await page.locator('.wl-chips a', { hasText: '25 000' }).click()
  await page.locator('.sheet a.radio', { hasText: 'Orange Money' }).click()
  await page.getByRole('button', { name: 'Recharger 25 000 F' }).click()
  await expect(page).toHaveURL(/st=recharge/)
  await expect(page.locator('.note.green')).toContainText('rechargé de 25 000 F')
  await expect(page.locator('.note.green')).toContainText('nouveau solde 70 000 F')
  await expect(page.locator('.wl-hist .li').first()).toContainText('Recharge Orange Money')
  await page.goto('/wallet?st=retirer')
  await page.locator('.wl-big input').click()
  await page.locator('.wl-big input').fill('50000')
  await expect(page.locator('.sheet [role=alert]')).toContainText('Tu peux retirer 27 340 F maintenant. Une recharge non utilisée se retire 72 h après, dès ven. 25 sept. à 18 h 05.')
  await page.locator('.wl-big input').click()
  await page.locator('.wl-big input').fill('20000')
  await expect(page.locator('.sheet .t13').first()).toContainText('sans frais')
  await page.getByRole('button', { name: 'Retirer 20 000 F' }).click()
  await expect(page.locator('.note.green')).toContainText('Retrait de 20 000 F envoyé vers MTN MoMo')
  await expect(page.locator('.wl-bal')).toContainText('50 000')
  await page.goto('/wallet?st=retirer')
  await page.locator('.wl-chips a').filter({ hasText: /^5\s000$/ }).click()
  await expect(page.locator('.sheet .t13').first()).toContainText('frais 100 F')
  await page.getByRole('button', { name: 'Retirer 5 000 F' }).click()
  await expect(page.locator('.note.green')).toContainText('frais 100 F')
})

// DP-53 : factures réelles (CCO-20) : la bonne commande, un vrai PDF.
test('factures : l’aperçu montre la bonne commande et le PDF s’enregistre', async ({ page }) => {
  await page.goto('/factures')
  await page.locator('a.li', { hasText: 'BLV-51388' }).click()
  await expect(page).toHaveURL(/ref=BLV-51388/)
  await expect(page.locator('.sheet')).toContainText('Beurre de karité pur 500 g × 2')
  await expect(page.locator('.sheet')).toContainText('Huile de coco vierge 500 ml')
  await expect(page.locator('.sheet .price.big')).toContainText('12 700')
  const [telechargement] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'Enregistrer sur le téléphone' }).click()])
  expect(telechargement.suggestedFilename()).toBe('Facture-BLV-51388.pdf')
  const chemin = await telechargement.path()
  const contenu = (await import('node:fs')).readFileSync(chemin!, 'latin1')
  expect(contenu.startsWith('%PDF-1.4')).toBe(true)
  expect(contenu).toContain('Facture · BLV-51388')
  expect(contenu).toContain('%%EOF')
})

// DP-53 : avis réels (AVIS-FENETRE, DP-35) : deux notes, note basse, modification, fenêtre fermée.
test('avis : notes obligatoires, note basse puis feuille, récapitulatif, modification, fenêtres', async ({ page }) => {
  await page.goto('/avis-donner?ref=BLV-51702')
  const envoyer = page.getByRole('button', { name: 'Envoyer mes notes' })
  await expect(envoyer).toHaveClass(/\boff\b/)
  await page.getByRole('radiogroup', { name: 'Note du vendeur' }).getByRole('radio', { name: '2 sur 5' }).click()
  await expect(page.locator('.cl13-rt').first()).toContainText('2 sur 5 · Mauvais')
  await expect(page.locator('.cl13-rt').first()).toContainText('Un problème avec l’article')
  await page.getByRole('radiogroup', { name: 'Note du relais' }).getByRole('radio', { name: '5 sur 5' }).click()
  await page.getByLabel('Commentaire').fill('Le son grésille à gauche.')
  await expect(envoyer).not.toHaveClass(/\boff\b/)
  await envoyer.click()
  await expect(page).toHaveURL(/\/avis-bas\?ref=BLV-51702$/)
  await expect(page.locator('.sheet')).toContainText('Le vendeur : 2 sur 5 · Mme Ngo Bassong : 5 sur 5')
  await page.getByRole('link', { name: 'Non merci' }).click()
  await expect(page).toHaveURL(/st=envoye/)
  await expect(page.locator('main')).toContainText('Merci Carine, tes 2 notes sont envoyées')
  await expect(page.locator('.kv').first()).toContainText('2 sur 5 · Mauvais')
  await page.getByRole('link', { name: 'Modifier mes notes' }).click()
  await page.getByRole('radiogroup', { name: 'Note du vendeur' }).getByRole('radio', { name: '4 sur 5' }).click()
  await page.getByRole('button', { name: 'Enregistrer les changements' }).click()
  await expect(page.locator('.kv').first()).toContainText('4 sur 5 · Bien')
  await page.goto('/compte')
  await expect(page.locator('a.li', { hasText: 'Avis à donner' })).toContainText('Rien à noter pour l’instant')
  await page.goto('/avis-donner?ref=BLV-51388')
  await expect(page.locator('main')).toContainText('Notation fermée')
  await page.goto('/avis-donner?ref=BLV-52107')
  await expect(page.locator('main')).toContainText('Pas encore de note possible')
})

// DP-53 : messagerie réelle (CMS) : lecture, envoi, masquage des coordonnées, nouvelle demande au support.
test('messagerie : lue à l’ouverture, message envoyé, numéro et e-mail masqués, demande au support', async ({ page }) => {
  await page.goto('/messagerie')
  await expect(page.locator('a.li', { hasText: 'Dossier LIT-3042' }).locator('.badge-num')).toHaveText('1')
  await page.locator('a.li', { hasText: 'Dossier LIT-3042' }).click()
  await page.getByRole('textbox', { name: 'Ton message' }).fill('Mon numéro est le 677 58 32 41, appelez-moi.')
  await page.getByRole('button', { name: 'Envoyer' }).click()
  await expect(page.locator('.cl13-b.me').last()).toContainText('numéro masqué')
  await expect(page.locator('.cl13-b.me').last()).not.toContainText('677')
  await expect(page.locator('.cl13-sys').last()).toContainText('Un numéro a été retiré de ce message avant l’envoi.')
  await page.goto('/compte')
  await expect(page.locator('a.li[href="/messagerie"]')).toContainText('Aucun message non lu')
  await page.goto('/fil?id=support&st=nouveau')
  await page.locator('.chips a', { hasText: 'Paiement' }).first().click()
  await page.getByRole('button', { name: 'Envoyer' }).click()
  await expect(page.locator('.fld [role=alert]')).toContainText('10 caractères au moins')
  await page.fill('#fil-message', 'Mon paiement est parti deux fois, écrivez-moi à carine@exemple.cm')
  await page.getByRole('button', { name: 'Envoyer' }).click()
  await expect(page).toHaveURL(/fil\?id=support$/)
  await expect(page.locator('.pill.green')).toHaveCount(0)
  await expect(page.locator('.cl13-b.me').last()).toContainText('[Paiement · BLV-52018]')
  await expect(page.locator('.cl13-b.me').last()).toContainText('e-mail masqué')
  await expect(page.locator('.cl13-sys').last()).toContainText('sous 2 h, de 7 h à 21 h')
  await page.goto('/messagerie')
  await expect(page.locator('a.li').first()).toContainText('Support BelivaY')
})

// DP-53 : aide, questions fréquentes et rappel réels : recherche, compteurs lus dans les données, rappel demandé
// gardé jusqu'à son annulation.
test('aide : recherche dans la FAQ, compteurs, WhatsApp, rappel demandé puis annulé', async ({ page }) => {
  await page.goto('/aide')
  await expect(page.locator('a.li', { hasText: 'Mes conversations' })).toContainText('3 conversations · 1 non lue')
  await expect(page.locator('a.cl13-th', { hasText: 'Frais de garde' })).toContainText('5 questions')
  await page.locator('a.inp', { hasText: 'Code, garde' }).click()
  await expect(page).toHaveURL(/\/faq\?q=$/)
  const champ = page.getByRole('searchbox', { name: 'Chercher dans les questions fréquentes' })
  await expect(champ).toBeFocused()
  await page.keyboard.type('remboursé')
  await expect(page.locator('.sec h2')).toContainText('réponse')
  await expect(page.locator('details.more').first()).toHaveAttribute('open', '')
  await champ.fill('zzzz')
  await expect(page.locator('.empty h3')).toHaveText('Aucune réponse')
  await page.goto('/faq?t=garde')
  await expect(page.locator('.chips a.on')).toHaveText('Frais de garde')
  await page.locator('details.more summary', { hasText: 'Combien coûte la garde' }).click()
  await expect(page.locator('details.more').first()).toContainText('Au plus 2 000 F.')
  await page.goto('/aide')
  await page.locator('a.li', { hasText: 'WhatsApp' }).first().click()
  // Numéro officiel de BelivaY (config/coordonnees.ts) : « Ouvrir WhatsApp » ouvre wa.me dans un nouvel onglet.
  await expect(page.getByRole('button', { name: 'Ouvrir WhatsApp' })).toBeVisible()
  await expect(page.locator('.sheet')).toContainText('+237 689 002 812')
  await page.goto('/rappel?commande=BLV-52107')
  await expect(page.locator('.sheet .chips a.on', { hasText: 'BLV-52107' })).toHaveCount(1)
  await page.locator('.sheet .chips a', { hasText: 'Compte' }).click()
  await page.locator('.sheet .chips a', { hasText: '17 h – 21 h' }).click()
  await page.locator('.sheet a.btn', { hasText: 'Demander le rappel' }).click()
  await expect(page).toHaveURL(/rappel\?st=envoye$/)
  await expect(page.locator('.sheet')).toContainText('t’appelle aujourd’hui entre 17 h et 21 h sur le')
  await expect(page.locator('.sheet .kv').nth(0)).toContainText('Compte')
  await expect(page.locator('.sheet .kv').nth(1)).toContainText('BLV-52107')
  await page.goto('/rappel')
  await expect(page.locator('.sheet h3')).toHaveText('Rappel demandé')
  await page.locator('.sheet a', { hasText: 'Annuler le rappel' }).click()
  await expect(page).toHaveURL(/\/rappel$/)
  await expect(page.locator('.sheet h3')).toHaveText('Demander un rappel')
})

// DP-53 : pages légales réelles : le bon document pour chacun des huit liens, la langue choisie, le PDF.
test('pages légales : bon document, bonne langue, PDF, acceptation du compte', async ({ page }) => {
  await page.goto('/legal')
  await expect(page.locator('.note b')).toHaveText('2 août 2026')
  await page.locator('a.li', { hasText: 'Paiement au comptoir et par carte' }).click()
  await expect(page.locator('.pg-t')).toHaveText('Paiement au comptoir et par carte')
  await expect(page.locator('.cl13-doc li').nth(4)).toContainText('pour tous')
  await page.goBack()
  await page.locator('a.li', { hasText: 'Cookies et mesure' }).click()
  await expect(page.locator('.pg-t')).toHaveText('Cookies et mesure d’audience')
  await expect(page.locator('.meta .pill.green')).toHaveCount(0)
  await page.getByRole('link', { name: 'English' }).click()
  await expect(page).toHaveURL(/d=cookies&lang=en/)
  await expect(page.locator('.pg-t')).toHaveText('Cookies and audience measurement')
  const telechargement = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download the full text (PDF)' }).click()
  expect((await telechargement).suggestedFilename()).toBe('BelivaY-cookies-1.0-en.pdf')
  await expect(page.locator('[role=status]')).toHaveText('PDF saved on the phone.')
  await page.goto('/legal-doc?d=retours')
  await expect(page.locator('.cl13-doc li').nth(3)).toContainText('Portefeuille BelivaY')
  await expect(page.locator('.meta .pill.green')).toHaveText('Acceptée le 2 août 2026')
  // Interface anglaise : le document français reste en français.
  await page.evaluate(() => localStorage.setItem('blv_c_lang', 'en'))
  await page.goto('/legal-doc?d=garde&lang=fr')
  await expect(page.locator('.pg-t')).toHaveText('Politique de garde au relais')
  await expect(page.getByRole('link', { name: 'Français' })).toHaveAttribute('href', '/legal-doc?d=garde&lang=fr')
})

// DP-53 : réglages réels : thème automatique suivi en direct, choix gardés, mesure d'audience avec accord.
test('réglages : thème automatique comme le téléphone, mesure d’audience gardée', async ({ page }) => {
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.goto('/reglages')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.getByRole('button', { name: 'Automatique' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.getByRole('button', { name: 'Sombre' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  const mesure = page.getByRole('switch', { name: 'Mesure d’audience' })
  await expect(mesure).toHaveAttribute('aria-checked', 'false')
  await mesure.click()
  await expect(mesure).toHaveAttribute('aria-checked', 'true')
  await page.reload()
  await expect(page.getByRole('switch', { name: 'Mesure d’audience' })).toHaveAttribute('aria-checked', 'true')
  await expect(page.getByRole('button', { name: 'Sombre' })).toHaveClass(/\bon\b/)
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
})

// DP-53 : réglage des notifications réel : choix enregistrés sur le compte, alertes critiques expliquées.
test('notifications : choix enregistrés, alerte critique expliquée, numéro non vérifié', async ({ page }) => {
  await page.goto('/notifs-reglages?from=notifications')
  const suivi = page.getByRole('switch', { name: 'Suivi' })
  await suivi.click()
  await expect(suivi).toHaveAttribute('aria-checked', 'false')
  await expect(page.locator('.cl10-toast')).toHaveText('Enregistré sur ton compte : Suivi désactivé')
  await page.getByRole('switch', { name: 'Promotions' }).click()
  await expect(page.locator('.cl10-toast')).toHaveText('Enregistré sur ton compte : Promotions activées')
  await expect(page).toHaveURL(/notifs-reglages\?from=notifications$/)
  await page.reload()
  await expect(page.getByRole('switch', { name: 'Suivi' })).toHaveAttribute('aria-checked', 'false')
  await expect(page.getByRole('switch', { name: 'Promotions' })).toHaveAttribute('aria-checked', 'true')
  await page.getByRole('switch', { name: 'Paiement : toujours activé' }).click()
  await expect(page.locator('.sheet h3')).toHaveText('« Paiement » reste activé')
  await expect(page).toHaveURL(/st=verrou&k=paiement&from=notifications/)
  await page.getByRole('link', { name: 'Compris' }).click()
  await expect(page.locator('.sheet')).toHaveCount(0)
  await expect(page.getByRole('switch', { name: 'Paiement : toujours activé' })).toHaveAttribute('aria-checked', 'true')
  await page.goto('/notifs-reglages?st=nonverifie')
  await expect(page.locator('.cl10-num .v')).toHaveText('Aucun numéro vérifié')
})

// DP-53 : suppression du compte réelle : refusée pendant une commande, un litige ou avec un solde ; sinon code SMS.
test('supprimer mon compte : refus motivé, puis code SMS, compte effacé, retour en visiteur', async ({ page }) => {
  await page.goto('/supprimer')
  await expect(page.locator('.card').first()).toContainText('4 commandes sont en cours, dont une en litige.')
  await expect(page.locator('a.li[href="/wallet?st=retirer"]')).toContainText('Ton portefeuille : 45 000 F')
  await expect(page.getByRole('button', { name: 'Supprimer mon compte' })).toHaveAttribute('aria-disabled', 'true')
  // Plus rien en cours, portefeuille vidé.
  await page.goto('/notifs-reglages')
  await page.getByRole('switch', { name: 'Promotions' }).click()
  await expect(page.locator('.cl10-toast')).toBeVisible()
  await page.evaluate(() => {
    const e = JSON.parse(localStorage.getItem('blv_demo_etat')!)
    e.enCours = []
    e.portefeuille = { ...e.portefeuille, rembourse: 0, recharges: [] }
    localStorage.setItem('blv_demo_etat', JSON.stringify(e))
  })
  await page.goto('/supprimer')
  await expect(page.locator('.pg-t')).toHaveText('Supprimer ton compte ?')
  await page.getByRole('button', { name: 'Recevoir le code et supprimer' }).click()
  await page.locator('.otp-saisie input').fill('000000')
  await page.getByRole('button', { name: 'Supprimer mon compte' }).click()
  await expect(page.locator('.cl03-otpm')).toHaveText('Ce code ne correspond pas. Encore 4 essais.')
  await page.locator('.otp-saisie input').fill('503917')
  await page.getByRole('button', { name: 'Supprimer mon compte' }).click()
  await expect(page.locator('.empty h3')).toHaveText('Ton compte est supprimé')
  await page.getByRole('button', { name: 'Revenir à l’accueil' }).click()
  await expect(page).toHaveURL(/\/$/)
  await page.goto('/compte')
  await expect(page).toHaveURL(/\/connexion\?next=/)
})

// DP-53 : devenir vendeur réel : nom proposé puis contrôlé, boutique ouverte et gardée, lien copié.
test('devenir vendeur : nom contrôlé, boutique ouverte et gardée, étapes et lien', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.goto('/devenir-vendeur')
  const nom = page.getByLabel('Nom de la boutique')
  await expect(nom).toHaveValue('Carine Mode')
  await page.locator('.chips a', { hasText: 'Beauté & santé' }).click()
  await expect(nom).toHaveValue('Carine Beauté')
  await nom.fill('Bo')
  await page.locator('a.btn', { hasText: 'Ouvrir ma boutique' }).click()
  await expect(page.locator('.fld [role=alert]')).toHaveText('Donne un nom d’au moins 3 caractères à ta boutique.')
  await nom.fill('Boutique A')
  await page.locator('a.btn', { hasText: 'Ouvrir ma boutique' }).click()
  await expect(page.locator('.fld [role=alert]')).toHaveText('Ce nom est déjà pris : choisis-en un autre.')
  await nom.fill('Beauté de Carine')
  await page.locator('.seg a', { hasText: 'Entreprise' }).click()
  await page.locator('a.btn', { hasText: 'Ouvrir ma boutique' }).click()
  await expect(page.locator('.note.green')).toContainText('Ta boutique « Beauté de Carine » est ouverte.')
  await expect(page.locator('.vd-tl > div.ok')).toHaveCount(2)
  await page.getByRole('button', { name: 'Copier' }).click()
  await expect(page.getByRole('button', { name: 'Copié' })).toBeVisible()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('https://vendeur.belivay.com/b/CRN-4821')
  await page.reload()
  await expect(page.locator('.card .kick').first()).toHaveText('Ta boutique « Beauté de Carine »')
  await page.locator('a.btn', { hasText: 'Ouvrir mon espace vendeur' }).click()
  await expect(page.locator('.pg-s')).toContainText('vendeur.belivay.com/b/CRN-4821')
  await page.goto('/compte')
  await expect(page.locator('a.vd-ban')).toContainText('Ma boutique « Beauté de Carine »')
})

// DP-53 : connexion par e-mail réelle : compte retenu, mot de passe vérifié, essais comptés, inscription contrôlée.
test('connexion par e-mail : mot de passe faux puis bon, inscription contrôlée, lien de nouveau mot de passe', async ({ page }) => {
  await page.goto('/compte')
  await page.getByRole('button', { name: 'Se déconnecter' }).click()
  await page.locator('.sheet').getByRole('button', { name: 'Se déconnecter' }).click()
  await expect(page).toHaveURL(/\/$/)
  await page.goto('/connexion-email')
  await expect(page.locator('#cx-email')).toHaveValue('c•••••@gmail.com')
  await page.getByRole('button', { name: /Mot de passe enregistré/ }).click()
  await page.locator('#cx-mdp').fill('mauvais1')
  await page.locator('a.btn', { hasText: 'Se connecter' }).click()
  await expect(page.locator('.note.red')).toContainText('E-mail ou mot de passe incorrect.')
  await page.getByRole('button', { name: 'Afficher le mot de passe' }).click()
  await expect(page.locator('#cx-mdp')).toHaveAttribute('type', 'text')
  await page.locator('#cx-mdp').fill('Belivay2026')
  await page.locator('a.btn', { hasText: 'Se connecter' }).click()
  await expect(page).toHaveURL(/\/$/)
  await page.goto('/compte')
  await expect(page).toHaveURL(/\/compte$/)
  await page.getByRole('button', { name: 'Se déconnecter' }).click()
  await page.locator('.sheet').getByRole('button', { name: 'Se déconnecter' }).click()
  await expect(page).toHaveURL(/\/$/)
  await page.goto('/connexion-email?st=inscription')
  await page.locator('#cx-prenom').fill('Aïcha')
  await page.locator('#cx-email').focus()
  await page.locator('#cx-email').fill('aicha@exemple')
  await page.locator('a.btn', { hasText: 'Créer mon compte' }).click()
  await expect(page.locator('[role=alert]')).toContainText('ne semble pas complète')
  await page.locator('#cx-email').fill('carine@gmail.com')
  await page.locator('a.btn', { hasText: 'Créer mon compte' }).click()
  await expect(page.locator('.note.or')).toContainText('Cette adresse a déjà un compte BelivaY.')
  await page.goto('/mdp-oublie')
  await page.locator('#mdp-email').focus()
  await page.locator('#mdp-email').fill('aicha@exemple.cm')
  await page.locator('a.btn', { hasText: 'Recevoir le lien' }).click()
  await expect(page.locator('.pg-s')).toHaveText('Si a•••••@exemple.cm a un compte BelivaY, un lien vient de partir. Il marche 30 minutes.')
})

// DP-53 : « Numéro et connexion » : méthodes liées et déliées (au moins une), mot de passe, appareils.
test('numéro et connexion : lier, délier, mot de passe, appareils déconnectés', async ({ page }) => {
  await page.goto('/compte')
  await page.locator('a.li', { hasText: 'Numéro et connexion' }).click()
  await expect(page).toHaveURL(/\/securite$/)
  await expect(page.locator('main')).toContainText('6 77 ·· ·· 41 · MTN')
  await page.locator('.li', { hasText: 'Apple' }).getByRole('button', { name: 'Lier' }).click()
  await expect(page.locator('.note.green')).toContainText('Ton compte Apple est lié.')
  await page.locator('.li', { hasText: 'E-mail et mot de passe' }).getByRole('button', { name: 'Changer' }).click()
  await page.fill('#sec-ancien', 'faux')
  await page.fill('#sec-nouveau', 'Nouveau2026')
  await page.locator('.sheet').getByRole('button', { name: 'Enregistrer' }).click()
  await expect(page.locator('.sheet [role=alert]')).toHaveText('Ton mot de passe actuel ne correspond pas.')
  await page.fill('#sec-ancien', 'Belivay2026')
  await page.locator('.sheet').getByRole('button', { name: 'Enregistrer' }).click()
  await expect(page.locator('.note.green')).toContainText('Tes autres appareils sont déconnectés.')
  await expect(page.locator('.li', { hasText: 'Chrome sur ordinateur' })).toHaveCount(1) // reste dans l'historique seulement
})

// DP-53 : « Ton numéro » réel : pays, numéro contrôlé, opérateur reconnu, canal, code, numéro déjà pris.
test('ton numéro : contrôle, pays, code faux puis bon, numéro vérifié', async ({ page }) => {
  await page.goto('/numero?from=panier')
  const champ = page.getByRole('textbox', { name: 'Ton numéro de téléphone' })
  await champ.fill('')
  await champ.pressSequentially('69900')
  await page.locator('a.btn', { hasText: 'Recevoir le code par SMS' }).click()
  await expect(page.locator('.fld [role=alert]')).toHaveText('Un numéro mobile du Cameroun a 9 chiffres et commence par 6.')
  await champ.pressSequentially('1234')
  await expect(champ).toHaveText('6 99 00 12 34')
  await expect(page.locator('.cl03-op')).toHaveText('Orange Money')
  await page.locator('a', { hasText: 'Numéro d’un autre pays' }).click()
  await page.getByRole('searchbox', { name: 'Rechercher un pays' }).pressSequentially('fran')
  await page.locator('.ax-cl a', { hasText: 'France' }).click()
  await expect(page.locator('.ax-ch a.on')).toContainText('WhatsApp')
  await page.locator('.cl03-cc').click()
  await page.locator('.ax-cl a', { hasText: 'Cameroun' }).click()
  await champ.pressSequentially('677112233')
  await page.locator('a.btn', { hasText: 'Recevoir le code par SMS' }).click()
  await page.locator('.otp-saisie input').fill('000000')
  await page.getByRole('button', { name: 'Valider mon numéro' }).click()
  await expect(page.locator('.cl03-otpm')).toHaveText('Ce code ne correspond pas. Encore 4 essais.')
  await page.locator('.otp-saisie input').fill('503917')
  await page.getByRole('button', { name: 'Valider mon numéro' }).click()
  await expect(page.locator('.cl03-done')).toContainText('6 77 ·· ·· 33')
  await page.locator('a.btn', { hasText: 'Continuer' }).click()
  await expect(page).toHaveURL(/premiere-commande/)
})

// DP-54 : adresses avec la vraie position (GPS, OpenStreetMap) et les informations pour le livreur.
test('adresses : position réelle, quartier trouvé, carte OpenStreetMap, instructions et moment', async ({ page, context }) => {
  await context.grantPermissions(['geolocation'])
  await context.setGeolocation({ latitude: 3.8636, longitude: 11.5262, accuracy: 18 })
  await page.goto('/adresses?st=ajout')
  await page.fill('#ad-nom', 'Chez Tantine')
  await page.locator('a', { hasText: 'Utiliser ma position réelle' }).click()
  await expect(page.locator('#ad-quartier')).toHaveValue('Mvog-Ada')
  await expect(page.locator('iframe[title="Carte de ta position"]')).toHaveAttribute('src', /openstreetmap\.org\/export\/embed\.html.*marker=3\.863600,11\.526200/)
  await expect(page.locator('main')).toContainText('Position précise à 18 m près')
  await page.fill('#ad-reperes', 'Derrière la boulangerie, maison jaune')
  await page.fill('#ad-instructions', 'Sonner deux fois')
  await page.locator('.chips a', { hasText: 'Soir' }).click()
  await page.getByRole('button', { name: 'Enregistrer l’adresse' }).click()
  await expect(page).toHaveURL(/\/adresses$/)
  const carte = page.locator('.card', { hasText: 'Chez Tantine' })
  await expect(carte).toContainText('Sonner deux fois · Le soir')
  await expect(carte.locator('iframe')).toHaveCount(1)
  await expect(carte.getByRole('link', { name: 'Ouvrir dans les cartes' })).toHaveAttribute('href', /openstreetmap\.org\/\?mlat=3\.863600/)
})

// DP-54 : moyens de paiement complets : carte contrôlée (marque, Luhn, date), portefeuille, comptoir.
test('moyens de paiement : carte ajoutée après contrôle, par défaut, retirée ; portefeuille et comptoir', async ({ page }) => {
  await page.goto('/moyens-paiement')
  await expect(page.locator('main')).toContainText('Ton plafond : 50 000 F par commande.')
  await page.getByRole('button', { name: 'Ajouter une carte' }).click()
  await page.fill('#cb-numero', '4242424242424241')
  await page.fill('#cb-exp', '0120')
  await page.locator('.sheet').getByRole('button', { name: 'Enregistrer la carte' }).click()
  await expect(page.locator('.sheet [role=alert]').first()).toHaveText('Ce numéro de carte semble mal tapé.')
  await page.fill('#cb-numero', '4242424242424242')
  await expect(page.locator('#cb-numero')).toHaveValue('4242 4242 4242 4242')
  await page.fill('#cb-exp', '0830')
  await page.fill('#cb-cvc', '123')
  await page.fill('#cb-nom', 'Carine Mballa')
  await page.locator('.sheet').getByRole('button', { name: 'Enregistrer la carte' }).click()
  await expect(page.locator('.cl13-pm', { hasText: 'Visa ·••• 4242' })).toContainText('Expire fin 08/30 · CARINE MBALLA')
  await page.locator('.cl13-pm', { hasText: 'Visa ·••• 4242' }).click()
  await page.getByRole('button', { name: 'Retirer cette carte' }).click()
  await page.getByRole('button', { name: 'Oui, retirer' }).click()
  await expect(page.locator('.cl13-pm', { hasText: 'Visa' })).toHaveCount(0)
  await page.getByRole('link', { name: 'Ouvrir' }).click()
  await expect(page).toHaveURL(/\/wallet$/)
})

// DP-54 : confidentialité et données : choix gardés, nom au retrait, historique effacé, export des données.
test('confidentialité : suggestions, nom au retrait, historique, téléchargement des données', async ({ page }) => {
  await page.goto('/compte')
  await page.locator('a.li', { hasText: 'Confidentialité et données' }).click()
  await expect(page).toHaveURL(/\/confidentialite$/)
  const sugg = page.getByRole('switch', { name: 'Suggestions pour toi' })
  await sugg.click()
  await expect(sugg).toHaveAttribute('aria-checked', 'false')
  await expect(page.getByRole('switch', { name: 'Publicité d’autres entreprises' })).toHaveAttribute('aria-checked', 'false')
  await page.locator('.li', { hasText: 'Nom donné au retrait' }).getByRole('button', { name: 'Changer' }).click()
  await page.fill('#cf-nom', 'Carine M.')
  await page.locator('.sheet').getByRole('button', { name: 'Enregistrer' }).click()
  await expect(page.locator('main')).toContainText('« Carine M. » à la place de ton nom complet')
  await page.locator('.li', { hasText: 'Historique' }).getByRole('button', { name: 'Effacer' }).click()
  await page.getByRole('button', { name: 'Tout effacer' }).click()
  await expect(page.locator('main')).toContainText('0 recherches · 0 produits vus')
  const fichier = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Télécharger', exact: true }).click()
  const d = await fichier
  expect(d.suggestedFilename()).toBe('BelivaY-mes-donnees.json')
  const contenu = JSON.parse(readFileSync(await d.path(), 'utf-8'))
  expect(contenu.confidentialite.nomRetrait).toBe('Carine M.')
  expect(contenu.profil.prenom).toBe('Carine')
  await page.reload()
  await expect(page.getByRole('switch', { name: 'Suggestions pour toi' })).toHaveAttribute('aria-checked', 'false')
})

// DP-54 : WhatsApp disponible (accord demandé), heures calmes réglées, message d'essai.
test('notifications : WhatsApp choisi après accord, retour au SMS, heures calmes', async ({ page }) => {
  await page.goto('/notifs-reglages')
  await page.getByRole('radio', { name: 'WhatsApp' }).click()
  await expect(page.locator('.sheet h3')).toHaveText('Recevoir les messages sur WhatsApp ?')
  await page.getByRole('button', { name: 'J’accepte : utiliser WhatsApp' }).click()
  await expect(page.getByRole('radio', { name: 'WhatsApp' })).toHaveAttribute('aria-checked', 'true')
  await page.getByRole('button', { name: 'M’envoyer un message d’essai' }).click()
  await expect(page.locator('.cl10-toast')).toHaveText('Message d’essai envoyé sur WhatsApp au 6 77 ·· ·· 41')
  await page.locator('.chips a', { hasText: '22 h – 6 h' }).click()
  await expect(page.locator('main')).toContainText('De 22 h à 6 h')
  await page.reload()
  await expect(page.getByRole('radio', { name: 'WhatsApp' })).toHaveAttribute('aria-checked', 'true')
  await page.getByRole('radio', { name: 'SMS' }).click()
  await expect(page.getByRole('radio', { name: 'SMS' })).toHaveAttribute('aria-checked', 'true')
  await page.getByRole('switch', { name: 'Sans son la nuit' }).click()
  await expect(page.locator('.chips a', { hasText: '22 h – 6 h' })).toHaveCount(0)
})

// DP-54 : taille du texte sur une barre (8 crans), gardée ; animations réduites.
test('réglages : barre de taille du texte, crans plus petits et intermédiaires, animations réduites', async ({ page }) => {
  await page.goto('/reglages')
  const barre = page.getByRole('slider', { name: 'Taille du texte' })
  await expect(barre).toHaveValue('2')
  await barre.fill('0')
  await expect(page.locator('html')).toHaveAttribute('data-echelle', '85')
  await expect(page.locator('main')).toContainText('Très petite · 85 %')
  await barre.fill('3')
  await expect(page.locator('html')).toHaveAttribute('data-echelle', '108')
  await barre.fill('4')
  await expect(page.locator('html')).toHaveAttribute('data-text', 'grande')
  await page.reload()
  await expect(page.getByRole('slider', { name: 'Taille du texte' })).toHaveValue('4')
  await page.getByRole('link', { name: 'Revenir à la taille normale' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-text', 'normale')
  await page.getByRole('switch', { name: 'Réduire les animations' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-anim', 'reduites')
})

// DP-54 : aide (services, arnaque), messagerie (recherche, filtres, tout lu), pages légales (acceptations, actions).
test('aide, messagerie et pages légales : services, arnaque, filtres, acceptations', async ({ page }) => {
  await page.goto('/aide')
  await expect(page.locator('main')).toContainText('Tout fonctionne')
  await page.getByRole('link', { name: 'Signaler une arnaque' }).click()
  await expect(page.locator('.chips a.on').first()).toHaveText('Arnaque')
  await page.goto('/messagerie')
  await page.locator('.chips a', { hasText: 'Support' }).click()
  await expect(page.locator('.card.tight a.li')).toHaveCount(1)
  await page.locator('.chips a', { hasText: 'Toutes' }).click()
  await page.getByRole('searchbox', { name: 'Chercher une conversation' }).fill('fer à repasser')
  await expect(page.locator('.card.tight a.li')).toHaveCount(1)
  await page.getByRole('searchbox', { name: 'Chercher une conversation' }).fill('')
  await page.getByRole('link', { name: 'Tout marquer comme lu' }).click()
  await expect(page.locator('.badge-num')).toHaveCount(0)
  await page.goto('/legal')
  await expect(page.locator('main')).toContainText('Version 1.0 · acceptée le 2 août 2026')
  await page.goto('/legal-doc?d=cgv')
  await page.locator('a', { hasText: 'Par e-mail' }).click()
  await expect(page.locator('[role=status]')).toHaveText('Envoyé à ton adresse e-mail.')
})

// DP-54 : une question au vendeur crée une conversation visible dans la messagerie (filtre Vendeurs).
test('question au vendeur : envoyée, numéro masqué, visible dans la messagerie', async ({ page }) => {
  await page.goto('/question?p=galaxya15')
  await page.locator('.chips a', { hasText: 'Le chargeur est-il fourni' }).click()
  await expect(page.locator('#q-texte')).toHaveValue(/^Bonjour, le chargeur est-il fourni\s\?$/)
  await page.locator('#q-texte').fill('Bonjour, le chargeur est fourni ? Appelez-moi au 677 58 32 41')
  await page.getByRole('button', { name: 'Envoyer ma question' }).click()
  await expect(page.locator('.note.amber')).toContainText('Coordonnées masquées automatiquement')
  await page.goto('/messagerie')
  await page.locator('.chips a', { hasText: 'Vendeurs' }).click()
  await expect(page.locator('a.li', { hasText: 'Samsung Galaxy A15' })).toBeVisible()
  await page.locator('a.li', { hasText: 'Samsung Galaxy A15' }).click()
  await expect(page.locator('.cl13-b.me').last()).toContainText('numéro masqué')
})

// DP-54 : litige réel : colis, problème, photo, souhait, dossier ouvert, suivi, retrait ; liste à jour.
test('litige : ouvert avec une photo, confirmé, suivi, retiré ; la liste suit', async ({ page }) => {
  await page.goto('/litiges')
  await expect(page.locator('.ost').first()).toContainText('En litige · réponse sous')
  await page.goto('/litige?ref=BLV-52018')
  await page.locator('.cl11-it', { hasText: 'Colis 2' }).click()
  await page.locator('.cl11-it', { hasText: 'Abîmé' }).click()
  await expect(page.locator('button.btn.primary')).toHaveClass(/\boff\b/)
  await page.locator('input[type=file][multiple]').setInputFiles('tests/fichiers/photo.png')
  await expect(page.locator('.cl11-pic img')).toHaveCount(1)
  await page.locator('textarea').fill('La bride gauche est décousue.')
  await page.getByRole('button', { name: 'Continuer' }).click()
  await page.locator('.cl11-it', { hasText: 'Être remboursé' }).click()
  await expect(page).toHaveURL(/litige-confirme\?id=LIT-3044/)
  await expect(page.locator('.cl11-money')).toContainText('14 500 F en attente de la décision.')
  await page.getByRole('link', { name: 'Suivre mon litige' }).click()
  await expect(page.locator('.hero .big')).toHaveText('48 h')
  await expect(page.locator('.kv', { hasText: 'Problème' })).toContainText('Abîmé')
  await page.getByRole('link', { name: 'Retirer mon signalement' }).click()
  await page.locator('.sheet').getByRole('button', { name: 'Retirer' }).click()
  await expect(page.locator('.hero')).toContainText('Signalement retiré')
  await page.goto('/litiges')
  await expect(page.locator('a.card', { hasText: 'LIT-3044' })).toContainText('Retiré par toi')
  await page.goto('/messagerie')
  await expect(page.locator('a.li', { hasText: 'LIT-3044' })).toBeVisible()
})

// DP-54 : « Favoris » (ex-Sauvegardés) : nom en français et en anglais, alertes, retrait annulable, panier.
test('favoris : renommés, alertes, retrait annulé, mise au panier, filtres', async ({ page }) => {
  await page.goto('/sauvegardes')
  await expect(page.locator('.pg-t')).toHaveText('Favoris')
  await expect(page.locator('nav, .dock').getByText('Favoris')).toBeVisible()
  const prix = page.locator('.cl07-fv', { hasText: 'Montre' }).getByRole('switch', { name: 'Baisse de prix' })
  await prix.click()
  await expect(prix).toHaveAttribute('aria-checked', 'false')
  await page.locator('.cl07-fv', { hasText: 'Montre' }).getByRole('button', { name: 'Retirer des favoris' }).click()
  await expect(page.locator('.cl07-fv')).toHaveCount(1)
  await page.locator('.cl10-toast').getByRole('button', { name: 'Annuler' }).click()
  await expect(page.locator('.cl07-fv')).toHaveCount(2)
  await page.locator('.chips a', { hasText: 'Prix en baisse' }).click()
  await expect(page.locator('.cl07-fv')).toHaveCount(1)
  await page.locator('.chips a', { hasText: 'Tous' }).click()
  await page.locator('.cl07-fv', { hasText: 'Baskets' }).getByRole('button', { name: 'Mettre au panier' }).click()
  await expect(page.locator('.note.green')).toContainText('« Baskets running » est dans ton panier.')
  await expect(page.locator('.cl07-fv')).toHaveCount(1)
  await page.evaluate(() => localStorage.setItem('blv_c_lang', 'en'))
  await page.reload()
  await expect(page.locator('.pg-t')).toHaveText('Favourites')
})

// DP-54 : panier (photo du porteur) : paramètres, autres vendeurs, quantités, retrait annulable, comptoir, commande.
test('panier : paramètres, autres vendeurs, quantité, retrait annulé, frais, commande', async ({ page }) => {
  await page.goto('/panier')
  const payer = page.locator('.cl07-bar .btn.primary')
  await expect(payer).toHaveText('Passer commande · 273 379 F')
  const camon = page.locator('.blk', { hasText: 'Tecno Camon 30' }).first()
  await camon.getByRole('link', { name: 'Plus' }).click()
  await expect(payer).toHaveText('Passer commande · 424 078 F')
  await camon.getByRole('link', { name: 'Moins' }).click()
  await camon.getByRole('link', { name: 'Modifier' }).click()
  await camon.locator('.chip', { hasText: '128 Go' }).click()
  await expect(camon.locator('.cv')).toHaveText('Gris titane · 128 Go')
  await expect(payer).toHaveText('Passer commande · 262 580 F')
  await expect(camon.locator('.chip.off', { hasText: '512 Go' })).toHaveAttribute('aria-disabled', 'true')
  await camon.getByRole('link', { name: 'Autres vendeurs (3)' }).click()
  await expect(camon.locator('.pan-vd .mini', { hasText: 'Essos' })).toContainText('Le plus proche')
  await camon.locator('.pan-vd .mini', { hasText: 'Essos' }).getByRole('button', { name: 'Choisir' }).click()
  await expect(page.locator('.note.green').first()).toContainText('Vendeur changé : Boutique E (Essos).')
  await expect(page.locator('section', { hasText: 'Boutique E' })).toContainText('zone différente')
  const mixeur = page.locator('.blk', { hasText: 'Mixeur' }).first()
  await mixeur.getByRole('button', { name: 'Voir ce vendeur' }).click()
  await mixeur.locator('.pan-vd .mini', { hasText: 'Mvog-Ada' }).getByRole('button', { name: 'Choisir' }).click()
  await expect(page.locator('section', { hasText: 'Boutique D' })).toBeVisible()
  const sac = page.locator('.blk', { hasText: 'Sac cuir artisanal' }).first()
  await sac.getByRole('link', { name: 'Retirer l’article' }).click()
  await expect(page.locator('.cl10-toast')).toContainText('« Sac cuir artisanal » retiré du panier.')
  await page.locator('.cl10-toast').getByRole('button', { name: 'Annuler' }).click()
  await expect(page.locator('.blk', { hasText: 'Sac cuir artisanal' })).toHaveCount(1)
  await expect(page.locator('.cl07-why')).toContainText('Paiement au comptoir non proposé')
  await payer.click()
  await expect(page).toHaveURL(/\/paiement-moyen/)
})

// DP-54 : achat réel : relais ou domicile choisi à l'achat, moyen, validation Mobile Money, confirmation.
test('achat : livraison choisie à l’achat, MTN validé, confirmation, panier vidé', async ({ page }) => {
  await page.goto('/panier')
  await page.locator('.cl07-bar .btn.primary').click()
  await expect(page).toHaveURL(/\/paiement-moyen$/)
  await page.locator('.cl08-row', { hasText: 'À domicile' }).click()
  await expect(page.locator('.cl07-r', { hasText: 'Livraison à domicile' })).toBeVisible()
  await expect(page.locator('.cl08-row', { hasText: 'Au retrait, au comptoir du relais' })).toContainText('Pas pour une livraison à domicile.')
  await page.locator('.cl08-row', { hasText: 'Au relais' }).click()
  await expect(page.locator('.cl08-row', { hasText: 'Portefeuille BelivaY' })).toHaveAttribute('aria-disabled', 'true')
  await page.locator('.cl08-row', { hasText: 'Autre numéro Mobile Money' }).click()
  await page.getByLabel('Numéro Mobile Money').fill('600')
  await page.locator('button.btn.primary', { hasText: 'Payer' }).click()
  await expect(page.locator('.note.red')).toContainText('9 chiffres')
  await page.locator('.cl08-row', { hasText: 'MTN MoMo' }).first().click()
  await expect(page.locator('button.btn.primary', { hasText: 'Payer' })).toHaveText('Payer 273 379 F avec MTN MoMo')
  await page.locator('button.btn.primary', { hasText: 'Payer' }).click()
  await expect(page).toHaveURL(/paiement-attente\?ref=BLV-52108/)
  await expect(page.locator('.cl08-lead')).toContainText('273 379 F')
  await page.getByRole('button', { name: 'J’ai validé sur mon téléphone' }).click()
  await expect(page).toHaveURL(/confirmee\?ref=BLV-52108/)
  await expect(page.locator('.cl08-amt')).toHaveText('273 379 F')
  await page.goto('/panier')
  await expect(page.locator('.empty h3')).toHaveText('Ton panier est vide')
})

test('achat : Apple Pay passe par la feuille du téléphone ; échec puis nouvelle tentative', async ({ page }) => {
  await page.goto('/paiement-moyen')
  await page.locator('.cl08-row', { hasText: 'Apple Pay' }).click()
  await expect(page.locator('.cl07-r', { hasText: 'Frais de service carte (2 %)' })).toBeVisible()
  await expect(page.locator('.note.red, button.btn.primary.off')).toHaveCount(1)
  await page.locator('.cl08-row', { hasText: 'MTN MoMo' }).first().click()
  await page.locator('button.btn.primary', { hasText: 'Payer' }).click()
  await page.getByRole('button', { name: 'Mon solde est insuffisant' }).click()
  await expect(page).toHaveURL(/paiement-echec\?ref=.*cause=solde/)
  await expect(page.locator('.cl08-lead')).toContainText('insuffisant')
  await page.getByRole('button', { name: /Réessayer/ }).click()
  await expect(page).toHaveURL(/paiement-attente\?ref=BLV-52109/)
})

// DP-54 : fiche d'après la photo du porteur : variantes, autres vendeurs, quantité, favori, panier ; galerie ; avis.
test('fiche : variante, autre vendeur, quantité, favori, ajout et achat ; galerie et avis', async ({ page }) => {
  await page.goto('/fiche?p=camon30')
  await expect(page.locator('.fp-t')).toHaveText('Tecno Camon 30')
  await expect(page.locator('.fp-p')).toHaveText('150 699 F')
  await page.locator('.fp-opt .chip', { hasText: '128 Go' }).click()
  await expect(page.locator('.fp-p')).toHaveText('139 000 F')
  await expect(page.locator('.fp-opt .chip', { hasText: '512 Go' })).toHaveAttribute('aria-disabled', 'true')
  await page.locator('.fp-av', { hasText: 'Essos' }).getByRole('button', { name: 'Choisir' }).click()
  await expect(page.locator('.fp-p')).toHaveText('147 500 F')
  await page.getByRole('button', { name: 'Plus' }).click()
  await expect(page.locator('.fp-sub')).toHaveText('295 000 F')
  await page.getByRole('button', { name: 'Ajouter aux favoris' }).click()
  await expect(page.locator('.note.green')).toContainText('Ajouté à tes favoris.')
  await page.locator('.fp-bar').getByRole('button', { name: 'Ajouter' }).click()
  await expect(page.locator('.note.green')).toContainText('« Tecno Camon 30 » ajouté au panier.')
  await page.goto('/panier')
  await expect(page.locator('section', { hasText: 'Boutique E' })).toContainText('Tecno Camon 30')
  await page.goto('/galerie?p=camon30')
  await page.getByRole('button', { name: 'Photo suivante' }).click()
  await expect(page.locator('.cl06-n')).toHaveText(/^2 \//)
  await page.goto('/avis?p=camon30')
  await page.locator('.cl06-fl .chip', { hasText: '2 ★' }).click()
  await expect(page.locator('.cl06-rv')).toHaveCount(1)
  await expect(page.locator('.cl06-rv')).toContainText('Réponse du vendeur')
  const utile = page.locator('.cl06-rv a', { hasText: 'Utile' })
  const avant = await utile.textContent()
  await utile.click()
  await expect(utile).not.toHaveText(avant!)
})

// DP-54 : catalogue et recherche : univers, liste triée et filtrée, recherche tolérante, filtres, rien trouvé, relais.
test('catalogue : univers, tri, filtres, recherche, rien trouvé, relais', async ({ page }) => {
  await page.goto('/categories?u=elec')
  await expect(page.locator('.cl04-ban2 h2')).toHaveText('Électronique')
  await page.locator('.cl04-sub3', { hasText: 'TV & vidéo' }).click()
  await expect(page).toHaveURL(/liste\?cat=elec&sub=TV/)
  await expect(page.locator('.pcard')).toHaveCount(1)
  await page.goto('/liste?cat=tel')
  await page.locator('.cl04-lchips .chip', { hasText: 'Prix croissant' }).click()
  await expect(page.locator('.pcard .pc-t').first()).toHaveText('Chargeur rapide 33 W USB-C')
  await page.locator('.pcard', { hasText: 'itel AC52' }).getByRole('button', { name: /Ajouter au panier/ }).click()
  await expect(page.locator('.note.green')).toContainText('« itel AC52 · noir » ajouté au panier.')
  await page.goto('/recherche-saisie')
  await page.getByRole('searchbox', { name: 'Chercher un produit' }).fill('chargeur tekno')
  await page.getByRole('searchbox', { name: 'Chercher un produit' }).press('Enter')
  await expect(page).toHaveURL(/recherche-resultats\?q=chargeur\+tekno/)
  await expect(page.locator('.cl05-row').first()).toContainText('Chargeur')
  await page.locator('.cl05-chr a', { hasText: 'Filtres' }).click()
  await page.locator('.chip', { hasText: '1 km' }).click()
  await expect(page.getByRole('button', { name: /Voir/ })).toBeVisible()
  await page.getByRole('button', { name: /Voir/ }).click()
  await expect(page).toHaveURL(/recherche-resultats\?.*km=1/)
  await expect(page.locator('.chips .chip.on', { hasText: 'à 1 km au plus' })).toBeVisible()
  await page.goto('/recherche-resultats?q=climatiseur+split')
  await expect(page.locator('.cl05-blk h3')).toHaveText('Tu cherchais autre chose ?')
  await page.getByRole('button', { name: 'Préviens-moi quand ça arrive' }).click()
  await expect(page.locator('.note.green')).toContainText('Alerte créée.')
  await page.goto('/relais-selecteur?retour=liste%3Fcat%3Dtel')
  await page.locator('.radio', { hasText: 'Relais Essos' }).click()
  await expect(page).toHaveURL(/\/liste\?cat=tel/)
  await expect(page.locator('.cl04-org')).toContainText('Relais Essos')
})

// DP-54 : commandes en données : liste et filtres, code caché puis montré, retrait confié, paiement et remise au
// comptoir, garde calculée, notifications lues, SMS et lien court.
test('commandes : liste, code, retrait confié, comptoir, garde, notifications', async ({ page }) => {
  await page.goto('/commandes')
  await page.locator('.c9-chips a', { hasText: 'À retirer' }).click()
  await expect(page.locator('.c9-oc .ti b')).toHaveText(['BLV-52018', 'BLV-51940'])
  await page.locator('.c9-chips a', { hasText: 'En litige' }).click()
  await expect(page.locator('.c9-oc .ti b', { hasText: 'BLV-51877' })).toBeVisible()
  await expect(page.locator('.c9-oc .ti b', { hasText: 'BLV-52018' })).toHaveCount(0)
  await page.locator('.c9-tabs a', { hasText: 'Terminées' }).click()
  await page.locator('.c9-oc', { hasText: 'BLV-51702' }).getByRole('link', { name: 'Racheter' }).click()
  await expect(page.locator('.note.green')).toContainText('remis au panier')
  await page.goto('/code?ref=BLV-52018')
  await expect(page.locator('.code6.mask')).toBeVisible()
  await page.getByRole('button', { name: 'Afficher le code' }).click()
  await expect(page.getByRole('img', { name: 'QR' })).toBeVisible()
  await page.goto('/code-partage?ref=BLV-52018')
  await page.getByLabel('Son prénom').fill('Paul')
  await page.getByLabel('Son numéro').fill('677112233')
  await page.getByRole('button', { name: 'Envoyer son code par SMS' }).click()
  await expect(page.getByText('Paul peut retirer ta commande')).toBeVisible()
  await page.goto('/comptoir-payer?ref=BLV-51940')
  await page.getByRole('button', { name: /^Payer/ }).click()
  await page.getByRole('button', { name: 'J’ai validé sur mon téléphone' }).click()
  await expect(page.getByText('Ton code de retrait est débloqué : montre-le au gérant.')).toBeVisible()
  await page.goto('/comptoir?ref=BLV-51940')
  await page.getByRole('button', { name: 'Le gérant m’a remis mes colis' }).click()
  await page.getByRole('button', { name: 'Tout est en ordre' }).click()
  await expect(page.getByRole('heading', { name: 'Tout est en ordre' })).toBeVisible()
  await page.goto('/commande?ref=BLV-51940')
  await expect(page.locator('.c9-st').first()).toHaveText('Retirée')
  await page.goto('/lien-court?ref=BLV-51940')
  await expect(page.locator('.note.ink')).toContainText('Ce lien ne sert plus')
  await page.goto('/garde?ref=BLV-52018')
  await expect(page.getByText('La grille, par commande')).toBeVisible()
  await page.goto('/notifications')
  const nonLues = page.getByLabel('Non lue')
  await expect(nonLues.first()).toBeVisible()
  await page.getByRole('button', { name: 'Tout marquer comme lu' }).click()
  await expect(nonLues).toHaveCount(0)
  await page.goto('/sms')
  await expect(page.locator('main')).toContainText('Code de retrait 604318')
})

// DP-54 : suites d'un litige en données : retour par le relais, remplacement par un autre vendeur ou
// remboursement, constat au comptoir, remboursement immédiat ; les liens du suivi y mènent.
test('litiges : retour déposé, remplacement choisi, constat au comptoir, remboursement immédiat', async ({ page }) => {
  await page.goto('/litige-suivi?id=LIT-3039')
  await page.getByRole('link', { name: 'Rapporter l’article au relais' }).click()
  await expect(page).toHaveURL(/retour\?id=LIT-3039/)
  await page.getByRole('button', { name: 'J’ai déposé le colis au relais' }).click()
  await expect(page.locator('.cl11-lead')).toContainText('La suite se fait sans toi')
  await page.goto('/litige-suivi?id=LIT-3041')
  await page.getByRole('link', { name: 'Suivre le remplacement' }).click()
  await expect(page.locator('.hero')).toContainText('Le vendeur n’a plus cet article')
  await page.getByRole('button', { name: 'Accepter ce vendeur' }).click()
  await expect(page.locator('.hero')).toContainText('Nouvel article en route')
  await page.goto('/litige-comptoir?ref=BLV-52018')
  await expect(page.locator('button.btn.primary')).toHaveClass(/\boff\b/)
  await page.locator('.cl11-it', { hasText: 'Colis 2' }).click()
  await page.locator('.chip', { hasText: 'Abîmé' }).click()
  await page.getByRole('button', { name: 'Ouvrir le litige au comptoir' }).click()
  await expect(page.locator('.hero')).toContainText('Ouvert au comptoir')
  await expect(page.locator('.cl11-row', { hasText: 'Colis 1' })).toContainText('en ordre')
  await page.goto('/commande?ref=BLV-52018')
  await expect(page.locator('.c9-st').first()).toContainText('En litige')
  await page.goto('/litiges')
  await page.locator('a.card', { hasText: 'LIT-2987' }).click()
  await expect(page).toHaveURL(/litige-auto\?id=LIT-2987/)
  await expect(page.locator('main')).toContainText('Réglé tout de suite')
  await page.goto('/litige-arrangement')
  await expect(page.locator('.empty h3')).toHaveText('Aucun arrangement en attente')
})

// DP-54 : modifier une commande en données : annuler une boutique (frais recalculés, remboursement), changer de
// relais, payer depuis l'étranger (panier envoyé, carte contrôlée, 3-D Secure, suivi du cadeau).
test('commande modifiée : boutique annulée, relais changé, panier payé depuis l’étranger', async ({ page }) => {
  await page.goto('/annuler?ref=BLV-52107')
  await page.locator('.chip', { hasText: 'Délai trop long' }).click()
  await page.locator('.card', { hasText: 'Boutique C · Colis 3' }).getByRole('link', { name: 'Annuler cette boutique' }).click()
  await expect(page).toHaveURL(/annuler-confirmer\?ref=BLV-52107&n=3/)
  await expect(page.locator('.cl12-st-t')).toHaveText(/Tu récupères/)
  await page.getByRole('button', { name: 'Annuler la Boutique C' }).click()
  await expect(page.locator('.hero')).toContainText('Boutique C annulée')
  await page.goto('/commande?ref=BLV-52107')
  await expect(page.locator('main')).toContainText('annulée,')
  await page.goto('/changer-relais?ref=BLV-52107')
  await page.locator('a.cl12-rc', { hasText: 'Relais Essos' }).click()
  await page.getByRole('button', { name: 'Confirmer le Relais Essos' }).click()
  await expect(page.locator('.hero')).toContainText('iront au Relais Essos')
  await page.goto('/fiche?p=mixeur')
  await page.locator('.fp-bar').getByRole('button', { name: 'Ajouter', exact: true }).click()
  await page.goto('/diaspora')
  await expect(page.getByRole('checkbox', { name: /Mixeur/ })).toBeVisible()
  await page.getByRole('button', { name: /Envoyer mon panier à un proche/ }).click()
  await page.getByRole('link', { name: 'Voir la page qu’il reçoit' }).click()
  await expect(page.locator('.pg-s')).toContainText('Carine')
  await page.getByLabel('Ton prénom').fill('Hervé')
  await page.getByLabel('Ton e-mail').fill('herve@exemple.fr')
  await page.getByLabel('Numéro de carte').fill('4242 4242 4242 4241')
  await page.getByLabel('Expiration').fill('08/29')
  await page.getByLabel('Code (CVC)').fill('123')
  await page.getByRole('button', { name: /^Payer/ }).click()
  await expect(page.getByText('Ce numéro de carte semble mal tapé.')).toBeVisible()
  await page.getByLabel('Numéro de carte').fill('4242 4242 4242 4242')
  await page.getByRole('button', { name: /^Payer/ }).click()
  await page.getByLabel('Code reçu par SMS de ta banque').fill('1234')
  await page.getByRole('button', { name: 'Valider' }).click()
  await expect(page).toHaveURL(/payeur-preuve\?id=PP-/)
  await expect(page.locator('main')).toContainText('Carine reçoit son code de retrait')
  await page.goto('/commandes')
  await expect(page.locator('.c9-oc .ti b', { hasText: 'BLV-52124' })).toBeVisible()
})

// DP-54 : arrivée réelle : intérêts gardés (catégories rangées), relais choisi, conditions acceptées par version,
// Face ID réglé, première commande en liste, notifications proposées.
test('arrivée : intérêts, relais, conditions, Face ID, première commande, notifications', async ({ page }) => {
  await page.goto('/interets')
  await page.getByRole('checkbox', { name: /Sport & loisirs/ }).click()
  await page.getByRole('button', { name: 'Continuer · 1 choisie' }).click()
  await expect(page).toHaveURL(/connexion\?lancement=1/)
  await page.goto('/categories')
  await expect(page.locator('.cl04-ban2 h2')).toHaveText('Sport & loisirs')
  await page.goto('/relais-choix?retour=premiere-commande')
  await page.locator('a.cl03-rr', { hasText: 'Relais Essos' }).click()
  await page.getByRole('button', { name: 'Choisir le Relais Essos' }).click()
  await expect(page).toHaveURL(/premiere-commande$/)
  await expect(page.locator('.card.or', { hasText: 'Ton relais' })).toContainText('Relais Essos')
  await page.goto('/legal')
  await page.locator('a.card', { hasText: 'Version 2.0' }).click()
  await page.getByRole('button', { name: 'J’accepte et je continue' }).click()
  await expect(page.locator('.note.green')).toContainText('Version 2.0 acceptée')
  await page.goto('/faceid?nouveau=1&next=%2Fcompte')
  await expect(page.getByText('Déjà activé sur ce compte.')).toBeVisible()
  await page.getByRole('link', { name: 'Continuer' }).click()
  await expect(page).toHaveURL(/\/compte$/)
  await page.goto('/notifs-proposition')
  await expect(page.getByRole('heading', { name: 'On te prévient quand tes colis arrivent ?' })).toBeVisible()
  await page.locator('a.cl03-link', { hasText: 'Plus tard' }).click()
  await page.getByRole('link', { name: 'Compris' }).click()
  await expect(page).toHaveURL(/\/commandes$/)
})

// DP-54 : connexion et données : données économes (les images attendent un toucher), codes gardés.
test('connexion et données : données économes, image au toucher, code gardé', async ({ page }) => {
  await page.goto('/reseau')
  await expect(page.locator('.note[role=status]')).toContainText('En ligne.')
  const eco = page.getByRole('switch', { name: 'Données économes' })
  await eco.click()
  await expect(eco).toHaveAttribute('aria-checked', 'true')
  await expect(page.locator('a.li', { hasText: 'BLV-52018' })).toBeVisible()
  await page.goto('/liste?cat=tel')
  await expect(page.locator('.dessin-eco').first()).toBeVisible()
  await page.locator('.dessin-eco').first().click()
  await expect(page).toHaveURL(/liste\?cat=tel/)
  await expect(page.locator('.pcard svg').first()).toBeVisible()
})

// DP-54 : Prime en données : mon abonnement, résilier puis reprendre, cagnotte, parrainage,
// Pass 7 jours souscrit, abonnement offert depuis l'étranger.
test('Prime : résiliation et reprise, cagnotte, parrainage, Pass, offert', async ({ page }) => {
  await page.goto('/mon-abonnement')
  await expect(page.locator('.hero')).toContainText('Prochain prélèvement : 4 000 F')
  await page.getByRole('link', { name: 'Résilier Prime' }).click()
  await page.getByRole('button', { name: 'Résilier Prime' }).click()
  await page.getByRole('button', { name: 'Reprendre Prime' }).click()
  await expect(page.locator('.hero')).toContainText('Prime · actif')
  await page.goto('/cagnotte')
  await expect(page.locator('.card:not(.vedette)', { hasText: 'En attente' })).toContainText('BLV-52107')
  await page.goto('/parrainage')
  await expect(page.locator('.cl14-mv', { hasText: 'Aline' })).toBeVisible()
  await page.goto('/abonnements')
  await page.getByRole('radio', { name: 'Choisir Plus' }).click()
  await expect(page.getByRole('radio', { name: 'Choisir Plus' })).toHaveAttribute('aria-checked', 'true')
  await page.getByRole('radio', { name: 'Mensuel' }).click()
  await expect(page).toHaveURL(/per=mois&palier=plus/)
  await expect(page.getByRole('link', { name: 'Prendre Plus · 2 500 F / mois' })).toBeVisible()
  await page.goto('/abonnement-souscrire?palier=pass&formule=pass')
  await page.getByRole('button', { name: /Payer 1 500 F/ }).click()
  await page.getByRole('button', { name: 'J’ai validé sur mon téléphone' }).click()
  await expect(page).toHaveURL(/mon-abonnement$/)
  await expect(page.locator('.hero')).toContainText('Pass 7 jours')
  await page.goto('/abonnement-offrir')
  await page.getByLabel('Son numéro BelivaY').fill('677 11 22 41')
  await page.getByLabel('Ton prénom (il le verra)').fill('Hervé')
  await page.getByLabel('Numéro de carte').fill('4242 4242 4242 4242')
  await page.getByLabel('Expiration').fill('08/29')
  await page.getByLabel('Code (CVC)').fill('123')
  await page.getByRole('button', { name: /Offrir · payer/ }).click()
  await page.getByLabel('Code reçu par SMS de ta banque').fill('1234')
  await page.getByRole('button', { name: 'Valider' }).click()
  await expect(page.locator('.cl14-center')).toContainText('Prime pour 12 mois')
  await page.getByRole('link', { name: 'Voir l’abonnement' }).click()
  await expect(page.locator('.hero')).toContainText('Offert par Hervé')
})

// DP-54 : listes d'envies en données : créer, ajouter, envoyer, la page des proches, offrir, la liste à jour.
test('listes : créer, ajouter, envoyer, offrir depuis le lien, article offert verrouillé', async ({ page }) => {
  await page.goto('/liste-creer')
  await page.getByLabel('Nom de la liste').fill('Ma crémaillère')
  await page.getByRole('button', { name: 'Créer la liste' }).click()
  await expect(page).toHaveURL(/liste-envies\?id=/)
  await page.getByRole('button', { name: 'Ajouter des articles' }).click()
  await page.getByRole('searchbox', { name: 'Chercher un produit' }).fill('marmite')
  await page.getByRole('button', { name: /Ajouter : Marmite/ }).click()
  await expect(page.locator('.note.green')).toContainText('ajouté à la liste')
  await page.keyboard.press('Escape')
  await page.getByRole('link', { name: 'Envoyer ma liste' }).click()
  await page.getByRole('button', { name: 'Partager le lien' }).click()
  await page.getByRole('link', { name: 'Voir ce que reçoivent tes proches' }).click()
  await expect(page.locator('.pg-s')).toContainText('Ma crémaillère')
  await page.locator('.card', { hasText: 'Marmite' }).getByRole('link', { name: 'Offrir' }).click()
  await page.getByLabel(/^Ton prénom/).fill('Mireille')
  await page.getByLabel('Ton e-mail, pour suivre le cadeau').fill('mireille@exemple.cm')
  await page.getByLabel('Ton numéro MTN ou Orange').fill('699112233')
  await page.getByRole('button', { name: /Offrir · payer/ }).click()
  await page.getByRole('button', { name: 'J’ai validé sur mon téléphone' }).click()
  await expect(page.locator('.pg-t')).toContainText('C’est offert, Mireille !')
  await page.getByRole('link', { name: /Voir la liste de/ }).click()
  await expect(page.locator('.card', { hasText: 'Marmite' })).toContainText('Déjà offert')
  await page.goto('/listes')
  await page.locator('a.card', { hasText: 'Ma crémaillère' }).click()
  await expect(page.locator('main')).toContainText('Offert par Mireille')
  await page.goto('/liste-envies?id=anniv')
  await page.getByRole('button', { name: 'Démarrer la livraison maintenant' }).click()
  await page.getByRole('button', { name: 'Démarrer maintenant' }).click()
  await expect(page.locator('main')).toContainText('Livraison démarrée')
})

// DP-54 : ventes flash et assistant en données.
test('ventes flash, promotions et assistant : prix de l’offre au panier, réponses, annulation confirmée', async ({ page }) => {
  await page.goto('/ventes-flash')
  await expect(page.locator('.fd-cd .h')).toHaveText(/^\d{2}$/)
  await page.locator('.fd-rail .fd-c', { hasText: 'Cartable' }).click()
  await expect(page).toHaveURL(/offre=cartable/)
  await page.locator('.sheet').getByRole('button', { name: /Ajouter au panier/ }).click()
  await expect(page.locator('.note.green')).toContainText('à 10 900 F')
  await page.goto('/promotions')
  await page.locator('.pm-sort a', { hasText: 'Prix le plus bas' }).click()
  await expect(page).toHaveURL(/tri=prix/)
  await page.locator('.fd-g', { hasText: 'Baskets' }).getByRole('link', { name: /Ajouter au panier/ }).click()
  await expect(page.locator('.note.green')).toContainText('« Baskets running » ajouté au panier.')
  await page.goto('/assistant')
  await page.getByLabel('Écris ta question').fill('Je peux retirer BLV-52018 quand ?')
  await page.getByLabel('Envoyer').click()
  await expect(page.locator('main')).toContainText('Tu peux les retirer maintenant')
  await expect(page.locator('main')).not.toContainText('604318')
  await page.locator('.chip', { hasText: 'Annuler un colis' }).click()
  await page.getByRole('link', { name: 'Voir la proposition' }).click()
  await page.getByRole('button', { name: 'Confirmer l’annulation' }).click()
  await expect(page.locator('.cl14-chat')).toContainText('Confirmé par toi')
})

// DP-54 : mise de côté en données : plan calculé, acompte, versements jusqu'à la commande, annulation chiffrée.
test('mise de côté : plan, acompte, versements, commande créée ; annulation avec forfait', async ({ page }) => {
  await page.goto('/cote?p=camon30')
  await expect(page.locator('.cl15-sum')).toContainText('30 140 F')
  await page.getByRole('link', { name: 'Voir le plan' }).click()
  await expect(page.locator('main')).toContainText('Total des 5 versements')
  await page.getByRole('button', { name: /Payer l’acompte/ }).click()
  await page.getByRole('button', { name: 'J’ai validé sur mon téléphone' }).click()
  await expect(page).toHaveURL(/cote-suivre\?id=MC-/)
  await expect(page.locator('.cl15-pc')).toContainText('1 versement sur 5')
  await page.goto('/cote-suivre?id=MC-118')
  await page.getByRole('link', { name: 'Payer 10 240 F' }).click()
  await page.getByRole('button', { name: 'Valider 10 240 F' }).click()
  await page.getByRole('button', { name: 'J’ai validé sur mon téléphone' }).click()
  await page.getByRole('link', { name: 'Payer le dernier versement' }).click()
  await expect(page.locator('main')).toContainText('C’est le dernier versement')
  await page.getByRole('button', { name: 'Valider 10 240 F' }).click()
  await page.getByRole('button', { name: 'J’ai validé sur mon téléphone' }).click()
  await expect(page).toHaveURL(/cote-fini\?id=MC-118/)
  await expect(page.locator('.cl15-dn')).toContainText('25 600 F')
  await page.goto('/cote')
  await page.locator('a.card', { hasText: 'Tecno Camon 30' }).click()
  await page.getByRole('link', { name: 'Annuler la mise de côté' }).click()
  await expect(page.locator('.cl15-sum')).toContainText('−5 000 F')
  await page.getByRole('button', { name: /Annuler et récupérer 25 140 F/ }).click()
  await expect(page.locator('.cl15-dn')).toContainText('25 140 F')
})

// DP-54 : cotisation en données : créer, participer (montant contrôlé, discret), objectif atteint, commande.
test('cotisation : créer, participer depuis le lien, compléter, commande passée toute seule', async ({ page }) => {
  await page.goto('/cotisation-participer?c=7KQ2M')
  await expect(page.locator('main')).toContainText('Il manque 3 968 F')
  await expect(page.locator('main')).toContainText('1 participation discrète')
  await page.getByLabel('Autre montant (F)').fill('500')
  await page.getByLabel('Ton prénom').fill('Odile')
  await page.getByLabel('Ton numéro MTN ou Orange').fill('677998877')
  await page.getByRole('button', { name: /Participer · / }).click()
  await expect(page.locator('[role=alert]').first()).toContainText('Entre 1 000 F et 3 968 F')
  await page.locator('.chip', { hasText: 'Compléter' }).click()
  await page.getByRole('button', { name: 'Participer · 3 968 F' }).click()
  await page.getByRole('button', { name: 'J’ai validé sur mon téléphone' }).click()
  await expect(page.locator('.note.green')).toContainText('L’objectif est atteint')
  await page.goto('/cotisation-atteinte?id=COT-77')
  await expect(page.locator('.cl15-dn')).toContainText('28 968 F')
  await expect(page.getByRole('link', { name: 'Faire retirer par Junior' })).toBeVisible()
  await page.goto('/cotisation?p=mixeur')
  await page.getByLabel('Nom de la cotisation').fill('Départ de Paul')
  await page.getByLabel('Prénom du bénéficiaire').fill('Paul')
  await page.getByRole('button', { name: 'Changer', exact: true }).click()
  await page.getByLabel('Relais du bénéficiaire').selectOption('Relais Essos')
  await page.getByLabel('Date limite').fill('2026-10-10')
  await page.getByRole('button', { name: 'Créer la cotisation' }).click()
  await expect(page).toHaveURL(/cotisation-partager\?id=COT-/)
  await page.getByRole('link', { name: 'Suivre la cotisation' }).click()
  await expect(page.locator('main')).toContainText('Personne n’a encore participé')
})

// DP-54 : panier famille en données : panier prêt, article trop lourd refusé, destinataire, paiement, mensuel.
test('panier famille : modèle, article trop lourd, destinataire, paiement, suspendre, preuve', async ({ page }) => {
  await page.goto('/famille')
  await expect(page.locator('.card.cl15-sum')).toContainText('34 400 F')
  await page.getByRole('button', { name: 'Ajouter un article' }).click()
  await page.getByRole('button', { name: 'Ajouter : Riz parfumé 25 kg' }).click()
  await page.getByRole('button', { name: /Ajouter Riz parfumé 5 kg/ }).click()
  await expect(page.locator('.card.cl15-sum')).toContainText('38 600 F')
  await page.getByRole('button', { name: /Continuer · / }).click()
  await page.getByRole('button', { name: 'Continuer vers le paiement' }).click()
  await expect(page.locator('.pg-t')).toContainText('Odile M.')
  await page.getByLabel('Ton e-mail, pour la preuve de retrait').fill('moi@exemple.fr')
  await page.getByLabel('Numéro de carte').fill('4242 4242 4242 4242')
  await page.getByLabel('Expiration').fill('08/29')
  await page.getByLabel('Code (CVC)').fill('123')
  await page.getByRole('button', { name: /^Payer/ }).click()
  await page.getByLabel('Code reçu par SMS de ta banque').fill('4812')
  await page.getByRole('button', { name: 'Valider' }).click()
  await expect(page).toHaveURL(/famille-mensuel\?panier=PF-/)
  await page.getByRole('button', { name: 'Suspendre en un geste' }).click()
  await expect(page.locator('.cl15-pc', { hasText: 'suspendu' })).toBeVisible()
  await page.goto('/famille-preuve?panier=PF-1&ref=BLV-52041')
  await expect(page.locator('.cl15-dn')).toContainText('Odile M. a retiré le panier')
})

// DP-54 : rentrée en données : école, classe, liste recalculée (déjà possédé, équivalent), panier, commande groupée.
test('rentrée : école, classe, décocher, équivalent, payer, suivi ; liste papier ; publier', async ({ page }) => {
  await page.goto('/rentree')
  await page.locator('a.cl15-op', { hasText: 'Les Flamboyants' }).click()
  await page.locator('a.cl15-op', { hasText: 'CE1' }).click()
  const total = page.locator('.card.cl15-sum .cl15-tot')
  const avant = await total.textContent()
  await page.getByRole('checkbox', { name: /Cartable scolaire/ }).click()
  await expect(total).not.toHaveText(avant!)
  await page.locator('a.cl15-eq').click()
  await page.getByRole('button', { name: /^Remplacer/ }).click()
  await expect(page.getByRole('checkbox', { name: /autre fabricant/ })).toBeVisible()
  await page.getByRole('button', { name: /Tout mettre au panier/ }).click()
  await expect(page.locator('.pg-t')).toContainText('Liste CE1 · 14 articles')
  await page.getByRole('button', { name: /Passer commande/ }).click()
  await page.getByRole('button', { name: 'J’ai validé sur mon téléphone' }).click()
  await expect(page).toHaveURL(/rentree-suivi\?ref=BLV-/)
  await page.goto('/rentree-liste-papier')
  await page.locator('.chip', { hasText: 'CM1' }).click()
  await page.locator('input[type=file]').setInputFiles('tests/fichiers/photo.png')
  await page.getByRole('button', { name: 'Envoyer ma liste' }).click()
  await expect(page.locator('.cl15-dn')).toContainText('Saisie avant le')
  await page.goto('/ecole')
  await page.getByRole('button', { name: 'Publier la liste Class 6' }).click()
  await expect(page.locator('.li', { hasText: 'Class 6' })).toContainText('publiée le')
})

// DP-54 : reprise en données : estimation, dépôt, contre-offre acceptée, paiement de la différence.
test('reprise : estimation, code de dépôt, contre-offre acceptée, différence payée', async ({ page }) => {
  await page.goto('/troc?p=camon30')
  await expect(page.getByRole('button', { name: 'Estimer ma reprise' })).toHaveClass(/\boff\b/)
  await page.getByRole('checkbox', { name: 'Compte Google retiré du téléphone' }).click()
  await page.getByRole('checkbox', { name: 'Code de verrouillage retiré' }).click()
  await page.getByRole('button', { name: 'Estimer ma reprise' }).click()
  await expect(page.locator('.card.cl15-pc')).toContainText('32 000 à 41 000')
  await page.getByRole('button', { name: 'Déposer mon téléphone' }).click()
  await expect(page.locator('.hero')).toContainText('Code de dépôt')
  await page.goto('/troc-contre-offre?id=TR-21')
  await page.getByRole('button', { name: 'Accepter 27 000 F' }).click()
  await expect(page.locator('.card.cl15-sum')).toContainText('123 699 F')
  await page.getByRole('button', { name: /Payer 123 699 F/ }).click()
  await page.getByRole('button', { name: 'J’ai validé sur mon téléphone' }).click()
  await expect(page.locator('.note.green')).toContainText('Commande BLV-')
})

// DP-54 : commande par WhatsApp : accord, proposition d'après la dernière commande, OUI, paiement dans BelivaY.
test('WhatsApp : accord, proposition, OUI, lien de paiement, commande payée', async ({ page }) => {
  await page.goto('/wa')
  await page.locator('.chip', { hasText: 'OK' }).click()
  await expect(page).toHaveURL(/\/wa-proposition$/)
  await expect(page.locator('main')).toContainText('Ma proposition')
  await page.locator('.chip', { hasText: 'C’est bon' }).click()
  await expect(page).toHaveURL(/\/wa-confirmer$/)
  await page.locator('.chip', { hasText: 'OUI' }).click()
  await expect(page).toHaveURL(/\/wa-lien$/)
  await page.getByRole('link', { name: 'Ouvrir le paiement dans BelivaY' }).click()
  await page.getByRole('button', { name: 'J’ai validé sur mon téléphone' }).click()
  await expect(page).toHaveURL(/confirmee/)
  await page.goto('/wa')
  await expect(page).toHaveURL(/\/wa-suite$/)
  await expect(page.locator('main')).toContainText('Paiement reçu')
  await expect(page.locator('main')).toContainText('jamais ici')
})

// DP-54 (CAL-11) : prix vérifiés avant de payer : une offre flash finie fait monter le prix, montré et accepté.
test('prix vérifiés au paiement : hausse montrée, acceptée, puis paiement', async ({ page }) => {
  await page.goto('/fiche?p=mixeur')
  await page.locator('.fp-bar').getByRole('button', { name: 'Ajouter', exact: true }).click()
  await page.evaluate(() => {
    const e = JSON.parse(localStorage.getItem('blv_demo_etat')!)
    const l = e.panier.lignes.find((x: { p: string }) => x.p === 'mixeur')
    l.prix = 30000
    l.flash = 1 // l'offre flash est finie
    localStorage.setItem('blv_demo_etat', JSON.stringify(e))
  })
  await page.goto('/paiement-moyen')
  await expect(page).toHaveURL(/\/prix-change$/)
  await expect(page.locator('main')).toContainText('Un prix a augmenté')
  await expect(page.locator('main')).toContainText('Écart+')
  await page.getByRole('button', { name: 'Accepter et continuer vers le paiement' }).click()
  await expect(page).toHaveURL(/\/paiement-moyen$/)
})

// DP-54 : diaspora : côté Cameroun (accepter une demande, code famille) ; côté diaspora (inscription, lien par
// code, commande pour le proche, plafond) ; le numéro et l'adresse du proche ne sont jamais montrés.
test('diaspora : accepter une demande, s’inscrire depuis l’étranger, relier par code, commander pour un proche', async ({ page }) => {
  await page.goto('/proches')
  await expect(page.locator('main')).toContainText('Hervé')
  await page.getByRole('button', { name: 'Accepter' }).click()
  await expect(page.locator('.note.green')).toContainText('Hervé peut maintenant commander pour toi.')
  await page.getByRole('button', { name: 'Créer mon code famille' }).click()
  await expect(page.locator('main')).toContainText(/FAM-[A-Z0-9]{4}/)
  await page.goto('/inscription-diaspora')
  await page.getByRole('link', { name: 'Avec mon e-mail' }).click()
  await page.getByLabel('Prénom').fill('Hervé')
  await page.getByLabel('Nom', { exact: true }).fill('Mbarga')
  await page.getByLabel('E-mail').fill('herve.mbarga@exemple.fr')
  await page.getByLabel('Pays où tu vis').selectOption('France')
  await page.getByLabel('Ville').fill('Lyon')
  await page.getByLabel('Date de naissance').fill('1990-05-14')
  await page.getByLabel('Ton numéro de téléphone').fill('612345678')
  await page.getByLabel('Mot de passe').fill('Belivay2026')
  await page.getByRole('checkbox', { name: /J’achète pour mes proches/ }).click()
  await page.getByRole('button', { name: 'Recevoir mes codes (SMS et e-mail)' }).click()
  await page.getByLabel('Code reçu par SMS').fill('503917')
  await page.getByLabel('Code reçu par e-mail').fill('284615')
  await page.getByRole('button', { name: 'Créer mon compte diaspora' }).click()
  await expect(page).toHaveURL(/\/proches$/)
  await expect(page.locator('main')).toContainText('Compte diaspora · Lyon, France')
  await page.getByLabel('Code famille').fill('FAM-4821')
  await page.getByRole('button', { name: 'Relier' }).click()
  await expect(page.locator('.note.green')).toContainText('Odile est relié à ton compte.')
  await expect(page.locator('main')).not.toContainText('699')
  await page.goto('/fiche?p=mixeur')
  await page.locator('.fp-bar').getByRole('button', { name: 'Ajouter', exact: true }).click()
  await page.goto('/proches')
  await page.getByRole('link', { name: 'Commander pour Odile' }).click()
  await expect(page.locator('main')).toContainText('Retrait au relais de Mvog-Ada')
  await page.getByLabel('Numéro de carte').fill('4242 4242 4242 4242')
  await page.getByLabel('Expiration').fill('08/29')
  await page.getByLabel('Code (CVC)').fill('123')
  await page.getByRole('button', { name: /^Payer/ }).click()
  await page.getByLabel('Code reçu par SMS de ta banque').fill('1234')
  await page.getByRole('button', { name: 'Valider' }).click()
  await expect(page.locator('.hero')).toContainText('part vers Odile')
})
