# Generated by Django 5.1.15 on 2026-10-04 23:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EtatService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nom", models.CharField(max_length=60)),
                ("ok", models.BooleanField(default=True)),
                ("detail", models.CharField(blank=True, default="", max_length=160)),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                ("actif", models.BooleanField(default=True, help_text="affiché dans l'aide")),
            ],
            options={
                "verbose_name": "État d'un service",
                "verbose_name_plural": "États des services",
                "ordering": ["ordre", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cle", models.CharField(help_text="identifiant exposé au site : support, LIT-12, q-345", max_length=40)),
                (
                    "type",
                    models.CharField(
                        choices=[("dossier", "Dossier (litige)"), ("vendeur", "Question à un vendeur"), ("support", "Support BelivaY")],
                        max_length=10,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("entete", models.JSONField(blank=True, default=dict, help_text="{titre, sous, dessin?, bloque?, lien?}")),
                ("resolue", models.BooleanField(default=False)),
                ("placeholder", models.CharField(blank=True, default="", max_length=120)),
                ("pied", models.CharField(blank=True, default="", max_length=200)),
                ("product_id", models.PositiveBigIntegerField(blank=True, help_text="catalog.Product (question au vendeur)", null=True)),
                ("vendor_id", models.PositiveBigIntegerField(blank=True, help_text="vendors.VendorProfile", null=True)),
                ("litige_id", models.CharField(blank=True, default="", help_text="aftersales.Litige : LIT-12", max_length=20)),
                ("lu_le", models.DateTimeField(blank=True, help_text="dernière lecture par le client", null=True)),
                ("maj_le", models.DateTimeField(default=django.utils.timezone.now, help_text="dernier échange : tri de la messagerie")),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="conversations_client", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
            },
        ),
        migrations.CreateModel(
            name="DemandeRappel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sujet", models.CharField(max_length=120)),
                ("commande", models.CharField(blank=True, default="", help_text="BLV-52018", max_length=20)),
                ("creneau", models.CharField(max_length=40)),
                ("precision", models.CharField(blank=True, default="", max_length=200)),
                ("date_appel", models.DateField(help_text="jour de l'appel, heure de Yaoundé (« aujourdhui » ou « demain » à la lecture)")),
                ("annule_le", models.DateTimeField(blank=True, null=True)),
                ("appele_le", models.DateTimeField(blank=True, help_text="rempli par le support après l'appel", null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rappels_support", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de rappel",
                "verbose_name_plural": "Demandes de rappel",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "de",
                    models.CharField(
                        choices=[
                            ("moi", "Le client"),
                            ("eux", "Le support ou le vendeur"),
                            ("systeme", "Ligne système"),
                            ("photo", "Photo du client"),
                        ],
                        max_length=8,
                    ),
                ),
                ("qui", models.CharField(blank=True, default="", help_text="« Support BelivaY », « Le vendeur »", max_length=80)),
                ("texte", models.TextField(blank=True, default="", help_text="déjà masqué : {{numero}}, {{email}}, {{lien}}")),
                ("photo", models.FileField(blank=True, default="", upload_to="messagerie/%Y/%m/")),
                ("systeme", models.CharField(blank=True, default="", help_text="ligne système jointe à une photo", max_length=200)),
                ("masques", models.JSONField(blank=True, default=list)),
                ("cree_le", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "conversation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="messaging.conversation"),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["cree_le", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ThemeFaq",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cle", models.SlugField(max_length=40)),
                ("langue", models.CharField(default="fr", max_length=5)),
                ("titre", models.CharField(max_length=120)),
                ("icone", models.CharField(blank=True, default="", max_length=40)),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Thème des questions fréquentes",
                "verbose_name_plural": "Thèmes des questions fréquentes",
                "ordering": ["langue", "ordre", "pk"],
                "constraints": [models.UniqueConstraint(fields=("cle", "langue"), name="messaging_theme_faq_unique")],
            },
        ),
        migrations.CreateModel(
            name="QuestionFaq",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                ("question", models.CharField(max_length=255)),
                ("reponse", models.TextField()),
                ("lien_texte", models.CharField(blank=True, default="", max_length=120)),
                ("lien_vers", models.CharField(blank=True, default="", max_length=255)),
                ("module_ff", models.CharField(blank=True, default="", help_text="interrupteur FF-… (vide : toujours)", max_length=40)),
                (
                    "module_ouvert",
                    models.BooleanField(blank=True, help_text="la question vaut quand l'interrupteur est dans cet état", null=True),
                ),
                (
                    "theme",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="messaging.themefaq"),
                ),
            ],
            options={
                "verbose_name": "Question fréquente",
                "verbose_name_plural": "Questions fréquentes",
                "ordering": ["theme", "ordre", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["client", "-maj_le"], name="messaging_c_client__8399a8_idx"),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(fields=("client", "cle"), name="messaging_conversation_unique"),
        ),
    ]
