# Generated by Django 5.1.15 on 2026-10-04 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListeEnvies",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nom", models.CharField(max_length=120)),
                ("favoris", models.BooleanField(default=False, help_text="la liste par défaut, faite des favoris")),
                (
                    "mode",
                    models.CharField(
                        choices=[("fil", "Au fil de l'eau (chaque cadeau son code)"), ("groupe", "Groupée (tous ensemble à une date)")],
                        default="fil",
                        max_length=6,
                    ),
                ),
                ("remise_le", models.DateTimeField(blank=True, null=True)),
                ("surprise", models.BooleanField(default=False)),
                (
                    "destination",
                    models.CharField(
                        choices=[("moi", "Mon relais"), ("offrant", "Choisi par celui qui offre"), ("tiers", "Une autre personne")],
                        default="moi",
                        max_length=8,
                    ),
                ),
                (
                    "relay_id",
                    models.PositiveBigIntegerField(blank=True, help_text="vide et destination « moi » : le relais habituel", null=True),
                ),
                ("tiers_prenom", models.CharField(blank=True, default="", max_length=80)),
                (
                    "domicile",
                    models.BooleanField(default=False, help_text="livraison à domicile acceptée (l'adresse n'est jamais montrée)"),
                ),
                ("demarree", models.BooleanField(default=False)),
                ("code", models.CharField(blank=True, help_text="lien court /l/<code> (CAP-11)", max_length=16, null=True, unique=True)),
                ("partage_le", models.DateTimeField(blank=True, null=True)),
                ("partage_jusqua", models.DateTimeField(blank=True, null=True)),
                ("prix_partage", models.JSONField(blank=True, default=dict, help_text="{product_id: prix} relevés au partage (CLE-39)")),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="listes_envies", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Liste d'envies",
                "verbose_name_plural": "Listes d'envies",
                "ordering": ["-favoris", "id"],
            },
        ),
        migrations.CreateModel(
            name="ColisEchange",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "origine",
                    models.CharField(
                        choices=[("liste", "Cadeau d'une liste"), ("cotisation", "Cotisation"), ("panier", "Panier payé pour un proche")],
                        max_length=10,
                    ),
                ),
                ("payeur_prenom", models.CharField(max_length=80)),
                ("payeur_email_chiffre", models.BinaryField(blank=True, null=True)),
                ("payeur_email_empreinte", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("destinataire_prenom", models.CharField(max_length=80)),
                ("code_liste", models.CharField(blank=True, db_index=True, default="", max_length=16)),
                ("product_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("titre", models.CharField(max_length=200)),
                ("surprise", models.BooleanField(default=False)),
                ("articles", models.PositiveIntegerField(help_text="valeur des articles, payée et bloquée")),
                ("frais", models.PositiveIntegerField(help_text="livraison (relais ou domicile)")),
                (
                    "qui",
                    models.CharField(
                        choices=[("payeur", "Le payeur"), ("destinataire", "Le destinataire, à la remise")], default="payeur", max_length=12
                    ),
                ),
                ("livraison", models.CharField(default="relais", help_text="relais | domicile", max_length=8)),
                ("relay_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("relais_nom", models.CharField(blank=True, default="", max_length=160)),
                ("mot", models.CharField(blank=True, default="", max_length=200)),
                ("moyen", models.CharField(default="mobile", help_text="mobile | carte | apple | google", max_length=10)),
                (
                    "moyen_affiche",
                    models.CharField(blank=True, default="", help_text="« Visa •••• 4242 », « 6 77 ·· ·· 41 »", max_length=60),
                ),
                ("numero_chiffre", models.BinaryField(blank=True, help_text="Mobile Money du payeur : remboursement", null=True)),
                ("devise", models.CharField(default="XAF", max_length=3)),
                ("montant_devise", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("frais_service", models.PositiveIntegerField(default=0)),
                ("total", models.PositiveIntegerField(help_text="payé maintenant par le payeur")),
                ("pays_carte", models.CharField(blank=True, default="", max_length=60)),
                ("reference_paiement", models.CharField(blank=True, default="", max_length=80)),
                (
                    "etat_paiement",
                    models.CharField(
                        choices=[
                            ("attente", "En attente (Mobile Money)"),
                            ("action", "3-D Secure à valider"),
                            ("paye", "Payé"),
                            ("refuse", "Refusé"),
                        ],
                        default="attente",
                        max_length=8,
                    ),
                ),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("a_accepter", "À accepter par le destinataire"),
                            ("accepte", "Accepté"),
                            ("refuse", "Refusé"),
                            ("retire", "Retiré"),
                        ],
                        default="accepte",
                        max_length=10,
                    ),
                ),
                ("order_id", models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ("retenue", models.PositiveIntegerField(blank=True, null=True)),
                ("rembourse", models.PositiveIntegerField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("paye_le", models.DateTimeField(blank=True, null=True)),
                (
                    "destinataire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="colis_recus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payeur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="colis_payes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liste",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cadeaux",
                        to="wishlists.listeenvies",
                    ),
                ),
            ],
            options={
                "verbose_name": "Colis payé pour un autre",
                "verbose_name_plural": "Colis payés pour un autre",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ArticleListe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_id", models.PositiveBigIntegerField()),
                ("ajoute_le", models.DateTimeField(auto_now_add=True)),
                (
                    "liste",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="articles", to="wishlists.listeenvies"),
                ),
            ],
            options={
                "verbose_name": "Article d'une liste",
                "verbose_name_plural": "Articles des listes",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ListeSuivie",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rappel", models.PositiveSmallIntegerField(blank=True, help_text="jours avant la remise", null=True)),
                ("depuis", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="listes_suivies", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "liste",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="suiveurs", to="wishlists.listeenvies"),
                ),
            ],
            options={
                "verbose_name": "Liste suivie",
                "verbose_name_plural": "Listes suivies",
            },
        ),
        migrations.CreateModel(
            name="Merci",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ref", models.CharField(max_length=40)),
                ("pour", models.CharField(max_length=80)),
                ("texte", models.CharField(max_length=500)),
                ("le", models.DateTimeField(auto_now=True)),
                (
                    "auteur",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mercis", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Remerciement",
                "verbose_name_plural": "Remerciements",
            },
        ),
        migrations.CreateModel(
            name="MiseEnStatut",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("partage", "Partage du téléphone"),
                            ("image", "Image enregistrée"),
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                            ("lien", "Lien copié"),
                            ("texte", "Texte copié"),
                        ],
                        max_length=10,
                    ),
                ),
                ("le", models.DateTimeField(auto_now_add=True)),
                (
                    "liste",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="statuts", to="wishlists.listeenvies"),
                ),
            ],
            options={
                "verbose_name": "Mise en statut",
                "verbose_name_plural": "Mises en statut",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ProcheConnu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero_masque", models.CharField(blank=True, default="", max_length=40)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="proches_connus", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("proche", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Proche trouvé par son numéro",
                "verbose_name_plural": "Proches trouvés par leur numéro",
            },
        ),
        migrations.CreateModel(
            name="RechercheProche",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Recherche d'un proche",
                "verbose_name_plural": "Recherches de proches",
            },
        ),
        migrations.CreateModel(
            name="EnvoiEchange",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("objet", models.CharField(choices=[("liste", "Liste d'envies"), ("cotisation", "Cotisation")], max_length=10)),
                ("objet_id", models.CharField(max_length=40)),
                ("le", models.DateTimeField(auto_now_add=True)),
                ("rappele_le", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="envois_echange", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("proche", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Envoi à un proche",
                "verbose_name_plural": "Envois aux proches",
                "ordering": ["id"],
                "constraints": [models.UniqueConstraint(fields=("client", "objet", "objet_id", "proche"), name="wishlists_envoi_unique")],
            },
        ),
        migrations.AddConstraint(
            model_name="listeenvies",
            constraint=models.UniqueConstraint(condition=models.Q(("favoris", True)), fields=("client",), name="wishlists_un_seul_favoris"),
        ),
        migrations.AddConstraint(
            model_name="articleliste",
            constraint=models.UniqueConstraint(fields=("liste", "product_id"), name="wishlists_article_unique"),
        ),
        migrations.AddConstraint(
            model_name="listesuivie",
            constraint=models.UniqueConstraint(fields=("client", "liste"), name="wishlists_suivie_unique"),
        ),
        migrations.AddConstraint(
            model_name="merci",
            constraint=models.UniqueConstraint(fields=("auteur", "ref"), name="wishlists_merci_unique"),
        ),
        migrations.AddConstraint(
            model_name="procheconnu",
            constraint=models.UniqueConstraint(fields=("client", "proche"), name="wishlists_proche_unique"),
        ),
    ]
