# Generated by Django 5.1.15 on 2026-10-05 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishlists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listeenvies",
            name="cagnotte_objectif",
            field=models.PositiveIntegerField(blank=True, help_text="objectif en francs ; vide : pas de cagnotte", null=True),
        ),
        migrations.AddField(
            model_name="listeenvies",
            name="cagnotte_titre",
            field=models.CharField(blank=True, default="", help_text="cagnotte de la liste (« Voyage de noces »)", max_length=80),
        ),
        migrations.AddField(
            model_name="listeenvies",
            name="hotes",
            field=models.JSONField(blank=True, default=list, help_text="le couple, les parents, les hôtes (prénoms)"),
        ),
        migrations.AddField(
            model_name="listeenvies",
            name="occasion",
            field=models.CharField(blank=True, default="", help_text="OccasionListe du site (anniversaire, mariage, dot…)", max_length=20),
        ),
        migrations.CreateModel(
            name="ParticipationCagnotte",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prenom", models.CharField(max_length=80)),
                ("montant", models.PositiveIntegerField()),
                ("mot", models.CharField(blank=True, default="", max_length=200)),
                ("discret", models.BooleanField(default=False)),
                ("moyen", models.CharField(default="mobile", max_length=10)),
                ("moyen_affiche", models.CharField(blank=True, default="", max_length=60)),
                ("reference_paiement", models.CharField(blank=True, default="", max_length=80)),
                (
                    "etat_paiement",
                    models.CharField(
                        choices=[("attente", "En attente de validation"), ("paye", "Payé"), ("refuse", "Refusé")],
                        default="attente",
                        max_length=8,
                    ),
                ),
                ("le", models.DateTimeField(auto_now_add=True)),
                (
                    "liste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="participations", to="wishlists.listeenvies"
                    ),
                ),
            ],
            options={
                "verbose_name": "Participation à une cagnotte de liste",
                "verbose_name_plural": "Participations aux cagnottes de liste",
                "ordering": ["id"],
            },
        ),
    ]
