# backend/apps/accounts/urls.py

from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from .views import (
    health,
    bootstrap_admin,
    bootstrap_demo_accounts,
    admin_create_courier,
    admin_create_user,
    admin_delete_courier,
    admin_list_delivery_organizations,
    admin_list_relay_points,
    admin_list_couriers,
    admin_sos_alerts,
    admin_resolve_sos,
    admin_update_courier,
    delivery_organization_couriers,
    delivery_organization_summary,
    delivery_organization_active_missions,
    delivery_organization_mission_queue,
    delivery_organization_assign_mission,
    delivery_organization_open_disputes,
    delivery_organization_profile,
    delivery_organization_update_courier,
    delivery_organization_vehicles,
    delivery_organization_dispute_reply,
    relay_point_profile,
    relay_point_open_disputes,
    relay_point_training,
    ComplianceDocumentListCreateView,
    RegisterView,
    RewardAccountsView,
    CurrentTrustScoreView,
    me,
    profile,
    update_profile,
    AvatarUploadView,
    CourierApplicationView,
    PayoutAccountListCreateView,
    PayoutAccountVerifyView,
    PhoneValidationView,
    UserCartView,
    FavoritesListCreateView,
    FavoriteDestroyView,
    NotificationsListView,
    NotificationMarkReadView,
    NotificationDeleteView,
    NotificationMarkAllReadView,
    TwoFactorTokenObtainPairView,
    logout_view,
    change_password,
    list_sessions,
    revoke_session,
    revoke_all_sessions,
    get_2fa_status,
    send_2fa_code,
    enable_2fa,
    disable_2fa,
    verify_2fa_login,
    google_login,
)

urlpatterns = [
    # ── Santé ─────────────────────────────────────────────────────────────────
    path("health/", health, name="auth-health"),
    path("trust-score/", CurrentTrustScoreView.as_view(), name="auth-trust-score"),
    path("bootstrap/admin/", bootstrap_admin, name="auth-bootstrap-admin"),
    path("bootstrap/demo-accounts/", bootstrap_demo_accounts, name="auth-bootstrap-demo-accounts"),
    path("admin/couriers/", admin_list_couriers, name="auth-admin-list-couriers"),
    path("admin/delivery-organizations/", admin_list_delivery_organizations, name="auth-admin-delivery-organizations"),
    path("admin/relay-points/", admin_list_relay_points, name="auth-admin-relay-points"),
    path("admin/couriers/create/", admin_create_courier, name="auth-admin-create-courier"),
    path("admin/users/create/", admin_create_user, name="auth-admin-create-user"),
    path("admin/couriers/<int:pk>/update/", admin_update_courier, name="auth-admin-update-courier"),
    path("admin/couriers/<int:pk>/", admin_delete_courier, name="auth-admin-delete-courier"),
    path("admin/couriers/sos/",             admin_sos_alerts,   name="auth-admin-sos-alerts"),
    path("admin/couriers/sos/<int:pk>/",    admin_resolve_sos,  name="auth-admin-resolve-sos"),

    # ── Authentification ──────────────────────────────────────────────────────
    path("register/",       RegisterView.as_view(),                name="auth-register"),
    path("login/",          TwoFactorTokenObtainPairView.as_view(), name="auth-login"),   # 2FA aware
    path("google/",         google_login,                           name="auth-google"),
    path("logout/",         logout_view,                           name="auth-logout"),
    path("refresh/",        TokenRefreshView.as_view(),            name="auth-refresh"),

    # ── Profil ────────────────────────────────────────────────────────────────
    path("me/",                  me,                                name="auth-me"),
    path("profile/",             profile,                           name="auth-profile"),
    path("profile/update/",      update_profile,                    name="auth-profile-update"),
    path("change-password/",     change_password,                   name="auth-change-password"),
    path("profile/avatar/",      AvatarUploadView.as_view(),        name="auth-profile-avatar"),
    path("phone/validate/",      PhoneValidationView.as_view(),      name="auth-phone-validate"),
    path("payout-accounts/",     PayoutAccountListCreateView.as_view(), name="auth-payout-accounts"),
    path("payout-accounts/<int:pk>/verify/", PayoutAccountVerifyView.as_view(), name="auth-payout-account-verify"),
    path("courier/application/", CourierApplicationView.as_view(),   name="courier-application"),
    path("delivery-organization/couriers/", delivery_organization_couriers, name="delivery-organization-couriers"),
    path("delivery-organization/summary/", delivery_organization_summary, name="delivery-organization-summary"),
    path("delivery-organization/missions/active/", delivery_organization_active_missions, name="delivery-organization-active-missions"),
    path("delivery-organization/missions/queue/", delivery_organization_mission_queue, name="delivery-organization-mission-queue"),
    path("delivery-organization/missions/<int:shipment_id>/assign/", delivery_organization_assign_mission, name="delivery-organization-assign-mission"),
    path("delivery-organization/disputes/open/", delivery_organization_open_disputes, name="delivery-organization-open-disputes"),
    path("delivery-organization/profile/", delivery_organization_profile, name="delivery-organization-profile"),
    path("delivery-organization/couriers/<int:courier_id>/", delivery_organization_update_courier, name="delivery-organization-update-courier"),
    path("delivery-organization/vehicles/", delivery_organization_vehicles, name="delivery-organization-vehicles"),
    path("delivery-organization/disputes/<int:dispute_id>/reply/", delivery_organization_dispute_reply, name="delivery-organization-dispute-reply"),
    path("relay-point/profile/", relay_point_profile, name="relay-point-profile"),
    path("relay-point/disputes/open/", relay_point_open_disputes, name="relay-point-open-disputes"),
    path("relay-point/training/", relay_point_training, name="relay-point-training"),
    path("compliance-documents/", ComplianceDocumentListCreateView.as_view(), name="compliance-documents"),

    # ── Sessions / Appareils ──────────────────────────────────────────────────
    path("sessions/",                   list_sessions,      name="auth-sessions-list"),
    path("sessions/<str:jti>/revoke/",  revoke_session,     name="auth-session-revoke"),
    path("sessions/revoke-all/",        revoke_all_sessions,name="auth-sessions-revoke-all"),

    # ── Double authentification (2FA) ─────────────────────────────────────────
    path("2fa/status/",       get_2fa_status,   name="auth-2fa-status"),
    path("2fa/send-code/",    send_2fa_code,    name="auth-2fa-send-code"),
    path("2fa/enable/",       enable_2fa,       name="auth-2fa-enable"),
    path("2fa/disable/",      disable_2fa,      name="auth-2fa-disable"),
    path("2fa/verify-login/", verify_2fa_login, name="auth-2fa-verify-login"),

    # ── Client (favoris, notifications) ──────────────────────────────────────
    path("cart/",                     UserCartView.as_view(),         name="client-cart"),
    path("favorites/",                FavoritesListCreateView.as_view(), name="client-favorites"),
    path("favorites/<int:pk>/",       FavoriteDestroyView.as_view(),     name="client-favorite-delete"),
    path("notifications/",            NotificationsListView.as_view(),   name="client-notifications"),
    path("notifications/<int:id>/read/",   NotificationMarkReadView.as_view(),    name="client-notification-read"),
    path("notifications/<int:id>/",        NotificationDeleteView.as_view(),      name="client-notification-delete"),
    path("notifications/read-all/",        NotificationMarkAllReadView.as_view(), name="client-notifications-read-all"),
    path("rewards/",                  RewardAccountsView.as_view(),      name="client-rewards"),
]
