# Generated by Django 5.1.15 on 2026-10-04 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FicheLogistique",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_id", models.PositiveBigIntegerField(help_text="catalog.Product de relaya", unique=True)),
                (
                    "classe",
                    models.CharField(
                        choices=[
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL (domicile seulement)"),
                            ("HG", "Hors gabarit (domicile seulement)"),
                        ],
                        max_length=2,
                    ),
                ),
                ("poids_g", models.PositiveIntegerField(blank=True, null=True)),
                ("gros", models.BooleanField(default=False, help_text="carton C1 ou C2 : garde majorée (GARDE-GROS-AJOUT)")),
            ],
            options={
                "verbose_name": "Fiche logistique d'un produit",
                "verbose_name_plural": "Fiches logistiques des produits",
            },
        ),
        migrations.CreateModel(
            name="Panier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "mode",
                    models.CharField(
                        choices=[("relais", "Retrait au relais"), ("domicile", "Livraison à domicile")], default="relais", max_length=10
                    ),
                ),
                ("relay_id", models.PositiveBigIntegerField(blank=True, help_text="vide : le relais habituel du compte", null=True)),
                (
                    "adresse_id",
                    models.PositiveBigIntegerField(
                        blank=True, help_text="client_accounts.Adresse ; vide : l'adresse principale", null=True
                    ),
                ),
                ("mis_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="panier_client", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Panier",
                "verbose_name_plural": "Paniers",
            },
        ),
        migrations.CreateModel(
            name="LignePanier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "product_id",
                    models.PositiveBigIntegerField(help_text="l'offre choisie (un Product de relaya = une offre d'une boutique)"),
                ),
                ("vendor_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("variante", models.CharField(blank=True, default="", max_length=160)),
                ("options", models.JSONField(blank=True, default=dict, help_text="{nom: valeur} : couleur, capacité, taille")),
                ("qte", models.PositiveIntegerField(default=1)),
                ("prix_vu", models.PositiveIntegerField(help_text="prix affiché au client à l'ajout ou à sa dernière acceptation")),
                ("flash", models.BooleanField(default=False)),
                ("position", models.PositiveIntegerField(default=0)),
                ("retiree_le", models.DateTimeField(blank=True, help_text="retrait annulable (« Annuler »)", null=True)),
                ("reservee_pour", models.PositiveBigIntegerField(blank=True, help_text="commande en attente de paiement", null=True)),
                ("ajoutee_le", models.DateTimeField(auto_now_add=True)),
                ("panier", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lignes", to="cart.panier")),
            ],
            options={
                "verbose_name": "Ligne de panier",
                "verbose_name_plural": "Lignes de panier",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="PanierPartage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "token",
                    models.CharField(help_text="8 caractères base32 majuscules (CAP-11, LIEN-COURT-LONG)", max_length=16, unique=True),
                ),
                ("mode", models.CharField(default="relais", max_length=10)),
                ("relay_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("lignes", models.JSONField(help_text="lignes figées : titre, dessin, qte, prix, boutique, product_id, classe, zone")),
                ("sous_total", models.PositiveIntegerField()),
                ("livraison", models.PositiveIntegerField()),
                ("frais", models.PositiveIntegerField(help_text="frais de service carte (PAY-CARTE-FRAIS)")),
                ("total", models.PositiveIntegerField()),
                ("version_parametres", models.CharField(max_length=40)),
                ("order_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("payeur", models.JSONField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="paniers_partages", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Panier partagé",
                "verbose_name_plural": "Paniers partagés",
                "ordering": ["-cree_le"],
            },
        ),
    ]
