# Generated by Django 5.1.15 on 2026-09-15 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(help_text='Format international sans « + » (ex : 2376XXXXXXXX), tel que fourni par WhatsApp.', max_length=32, unique=True, verbose_name='Numéro WhatsApp')),
                ('profile_name', models.CharField(blank=True, max_length=120, verbose_name='Nom du profil')),
                ('language', models.CharField(blank=True, choices=[('fr', 'Français'), ('en', 'English')], help_text="Vide tant que le client ne l'a pas choisie.", max_length=2, verbose_name='Langue')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='Premier message')),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier message reçu')),
            ],
            options={
                'verbose_name': 'Contact WhatsApp',
                'verbose_name_plural': 'Contacts WhatsApp',
                'ordering': ['-last_inbound_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'Reçu'), ('OUT', 'Envoyé')], max_length=3)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('message_type', models.CharField(blank=True, max_length=32)),
                ('text', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, help_text="Motif d'échec d'un envoi, le cas échéant.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_assistant.whatsappcontact')),
            ],
            options={
                'verbose_name': 'Message WhatsApp',
                'verbose_name_plural': 'Messages WhatsApp',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('direction', 'IN'), models.Q(('provider_message_id', ''), _negated=True)), fields=('provider_message_id',), name='whatsapp_inbound_message_unique')],
            },
        ),
    ]
