# Generated by Django 5.1.15 on 2026-09-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='context',
            field=models.JSONField(blank=True, default=dict, verbose_name='Contexte'),
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='state',
            field=models.CharField(blank=True, max_length=32, verbose_name='Étape en cours'),
        ),
    ]
