# Generated by Django 5.1.15 on 2026-09-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_assistant', '0002_conversation_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(help_text='Chemin du fichier dans le stockage Belivay.', max_length=255, unique=True)),
                ('media_id', models.CharField(max_length=128)),
                ('uploaded_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Média déposé chez WhatsApp',
                'verbose_name_plural': 'Médias déposés chez WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Titre (interne)')),
                ('image', models.ImageField(help_text='JPG, PNG ou WEBP, 5 Mo max. Format carré ou portrait conseillé (ex : 1080 × 1350).', upload_to='whatsapp/posters/', verbose_name='Affiche')),
                ('caption_fr', models.TextField(blank=True, verbose_name='Légende (français)')),
                ('caption_en', models.TextField(blank=True, verbose_name='Légende (anglais)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Début de campagne')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin de campagne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Affiche WhatsApp',
                'verbose_name_plural': 'Affiches WhatsApp',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
