# Generated by Django 5.1.15 on 2026-09-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_assistant', '0003_posters_and_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappposter',
            name='placement',
            field=models.CharField(choices=[('welcome', 'Accueil (salutation, premier message)'), ('search', "Recherche d'un article")], default='welcome', help_text="Quand l'assistant envoie cette affiche.", max_length=16, verbose_name='Moment'),
        ),
    ]
