# Generated by Django 5.1.15 on 2026-09-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_assistant', '0004_poster_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappposter',
            name='placement',
            field=models.CharField(choices=[('welcome', 'Accueil (salutation, premier message)'), ('shop', 'Bouton « Acheter » (catalogue)'), ('search', "Recherche d'un article")], default='welcome', help_text="Quand l'assistant envoie cette affiche.", max_length=16, verbose_name='Moment'),
        ),
    ]
