# Generated by Django 5.1.15 on 2026-09-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_assistant', '0005_poster_shop_placement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mission', 'Nouvelle mission (un colis)'), ('tour_recap', 'Récapitulatif de tournée')], max_length=16, verbose_name='Type')),
                ('shipment_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Colis n°')),
                ('tournee_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Tournée n°')),
                ('courier_id', models.PositiveBigIntegerField(verbose_name='Livreur n°')),
                ('assignment_ref', models.CharField(blank=True, max_length=40, verbose_name='Assignation')),
                ('recipient', models.CharField(blank=True, max_length=32, verbose_name='Envoyé au')),
                ('language', models.CharField(blank=True, max_length=2, verbose_name='Langue')),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('error', models.TextField(blank=True, verbose_name='Erreur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
            ],
            options={
                'verbose_name': 'Message livreur',
                'verbose_name_plural': 'Messages livreurs',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'mission')), fields=('shipment_id', 'courier_id', 'assignment_ref'), name='whatsapp_courier_mission_unique'), models.UniqueConstraint(condition=models.Q(('kind', 'tour_recap')), fields=('tournee_id', 'courier_id'), name='whatsapp_courier_tour_recap_unique')],
            },
        ),
    ]
