# Generated by Django 5.1.15 on 2026-09-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_assistant', '0006_couriernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('new_order', 'Nouvelle commande payee')], default='new_order', max_length=16, verbose_name='Type')),
                ('order_id', models.PositiveBigIntegerField(verbose_name='Commande n°')),
                ('vendor_id', models.PositiveBigIntegerField(verbose_name='Vendeur n°')),
                ('recipient', models.CharField(blank=True, max_length=32, verbose_name='Envoyé au')),
                ('language', models.CharField(blank=True, max_length=2, verbose_name='Langue')),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('error', models.TextField(blank=True, verbose_name='Erreur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
            ],
            options={
                'verbose_name': 'Message vendeur',
                'verbose_name_plural': 'Messages vendeurs',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('order_id', 'vendor_id', 'kind'), name='whatsapp_vendor_order_unique')],
            },
        ),
    ]
