# Generated by Django 5.1.15 on 2026-09-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_assistant', '0007_vendornotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('on_the_way', 'Colis en route vers le relais')], default='on_the_way', max_length=16, verbose_name='Type')),
                ('parcel_id', models.PositiveBigIntegerField(verbose_name='Colis relais n°')),
                ('relay_id', models.PositiveBigIntegerField(verbose_name='Point relais n°')),
                ('recipient', models.CharField(blank=True, max_length=32, verbose_name='Envoyé au')),
                ('language', models.CharField(blank=True, max_length=2, verbose_name='Langue')),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('error', models.TextField(blank=True, verbose_name='Erreur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
            ],
            options={
                'verbose_name': 'Message point relais',
                'verbose_name_plural': 'Messages points relais',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('parcel_id', 'relay_id', 'kind'), name='whatsapp_relay_parcel_unique')],
            },
        ),
    ]
