# Generated by Django 5.1.15 on 2026-09-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_assistant', '0008_relaynotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('picked_up', 'Colis parti de chez le vendeur'), ('at_relay', 'Colis arrive au point relais'), ('out_for_delivery', 'Le livreur arrive'), ('delivered', 'Livre')], max_length=20, verbose_name='Etape')),
                ('order_id', models.PositiveBigIntegerField(verbose_name='Commande n°')),
                ('shipment_id', models.PositiveBigIntegerField(verbose_name='Colis n°')),
                ('recipient', models.CharField(blank=True, max_length=32, verbose_name='Envoyé au')),
                ('language', models.CharField(blank=True, max_length=2, verbose_name='Langue')),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('error', models.TextField(blank=True, verbose_name='Erreur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
            ],
            options={
                'verbose_name': 'Message client',
                'verbose_name_plural': 'Messages clients',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('shipment_id', 'kind'), name='whatsapp_customer_step_unique')],
            },
        ),
    ]
