# Generated by Django 5.1.15 on 2026-04-14 04:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AddField(
            model_name='product',
            name='compare_at_price',
            field=models.PositiveIntegerField(blank=True, help_text='Prix barré (avant promotion). Si renseigné, affiché rayé. Doit être > price_xaf.', null=True, verbose_name='Prix barré (FCFA)'),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_end_date',
            field=models.DateField(blank=True, help_text='Date de fin de promotion. Le frontend affiche un timer countdown.', null=True, verbose_name='Fin de promotion'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='', help_text='Auto-généré : BLV-{CAT}-{id}. Modifiable manuellement.', max_length=60, verbose_name='SKU / Référence'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_threshold',
            field=models.PositiveIntegerField(blank=True, help_text="Quantité en dessous de laquelle une alerte stock s'affiche pour ce produit. Si vide → on utilise le seuil global de PlatformSettings.", null=True, verbose_name='Seuil alerte stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0, help_text='Réduction en % (0-100). Utiliser compare_at_price de préférence.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_xaf',
            field=models.PositiveIntegerField(help_text='Prix de vente en FCFA (XAF)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Description courte pour la page produit et les aperçus.', max_length=300),
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'attribut")),
                ('attribute_type', models.CharField(choices=[('SIZE', 'Taille'), ('COLOR', 'Couleur'), ('MATERIAL', 'Matière'), ('OTHER', 'Autre')], default='OTHER', max_length=10, verbose_name='Type')),
                ('values', models.JSONField(default=list, help_text='Liste JSON. Ex: ["S", "M", "L"] ou ["Rouge", "Bleu"]', verbose_name='Valeurs disponibles')),
                ('is_required', models.BooleanField(default=False, verbose_name='Obligatoire')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Attribut Produit',
                'verbose_name_plural': 'Attributs Produit',
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_values', models.JSONField(default=list, help_text='Valeurs sélectionnées parmi ProductAttribute.values.')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='catalog.productattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Valeur Attribut Produit',
                'verbose_name_plural': 'Valeurs Attributs Produit',
                'unique_together': {('product', 'attribute')},
            },
        ),
    ]
