# Generated by Django 5.1.15 on 2026-06-06 12:54

from django.db import migrations
from django.utils.text import slugify


def attach_offers_to_masters(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    MasterProduct = apps.get_model("catalog", "MasterProduct")

    used_slugs = set(MasterProduct.objects.values_list("slug", flat=True))

    # Tous les produits existants (y compris soft-deleted) sans fiche → 1 fiche chacun.
    for product in Product.objects.filter(master__isnull=True).iterator():
        base = slugify(product.title) or "fiche"
        slug = base
        counter = 1
        while slug in used_slugs:
            slug = f"{base}-{counter}"
            counter += 1
        used_slugs.add(slug)

        master = MasterProduct.objects.create(
            title=product.title,
            slug=slug,
            description=product.description or "",
            brand="",
            category_id=product.category_id,
        )
        product.master = master
        product.save(update_fields=["master"])


def detach_offers_from_masters(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    MasterProduct = apps.get_model("catalog", "MasterProduct")
    Product.objects.update(master=None)
    MasterProduct.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_masterproduct_product_master'),
    ]

    operations = [
        migrations.RunPython(attach_offers_to_masters, detach_offers_from_masters),
    ]
