# Generated by Django 5.1.15 on 2026-06-06 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_attach_offers_to_masters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='masterproduct',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_masterproducts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Validé'), ('REJECTED', 'Rejeté')], db_index=True, default='PENDING', max_length=10, verbose_name='Statut de modération'),
        ),
        migrations.AddField(
            model_name='product',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Validé'), ('REJECTED', 'Rejeté')], db_index=True, default='PENDING', max_length=10, verbose_name='Statut de modération'),
        ),
    ]
