# Generated by Django 5.1.15 on 2026-06-06 13:57

from django.db import migrations


def approve_existing(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    MasterProduct = apps.get_model("catalog", "MasterProduct")
    Product.objects.update(moderation_status="APPROVED")
    MasterProduct.objects.update(moderation_status="APPROVED")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_masterproduct_moderated_at_and_more'),
    ]

    operations = [
        migrations.RunPython(approve_existing, migrations.RunPython.noop),
    ]
