# Generated by Django 5.1.15 on 2026-06-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_approve_existing_offers_and_masters'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moderation_reason',
            field=models.TextField(blank=True, default='', verbose_name='Motif de modération'),
        ),
    ]
