# Generated by Django 5.1.15 on 2026-06-10 11:06

from django.db import migrations

DEFAULTS = ["Neuf", "Comme neuf", "Bon état", "Neuf en boîte"]


def seed(apps, schema_editor):
    PC = apps.get_model("catalog", "ProductCondition")
    for i, name in enumerate(DEFAULTS):
        PC.objects.get_or_create(name=name, defaults={"display_order": i})


def unseed(apps, schema_editor):
    PC = apps.get_model("catalog", "ProductCondition")
    PC.objects.filter(name__in=DEFAULTS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_productcondition'),
    ]

    operations = [
        migrations.RunPython(seed, unseed)
    ]
