# Generated by Django 5.1.15 on 2026-06-10 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_seed_default_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.productcondition', verbose_name='État'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_note',
            field=models.TextField(blank=True, default='', verbose_name='Note du vendeur'),
        ),
        migrations.CreateModel(
            name='MasterProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='masters/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.masterproduct')),
            ],
            options={
                'verbose_name': 'Image fiche',
                'verbose_name_plural': 'Images fiche',
                'ordering': ['order', '-is_primary', '-created_at'],
            },
        ),
    ]
