# Generated by Django 5.1.15 on 2026-06-10 11:38

from django.db import migrations


def copy_images_to_fiches(apps, schema_editor):
    ProductImage       = apps.get_model("catalog", "ProductImage")
    MasterProductImage = apps.get_model("catalog", "MasterProductImage")
    for pi in ProductImage.objects.select_related('product').iterator():
        product = pi.product
        if not product.master_id or not pi.image:
            continue
        MasterProductImage.objects.get_or_create(
            master_id=product.master_id,
            image=pi.image.name,
            defaults={'is_primary': pi.is_primary, 'order': pi.order},
        )


def reverse(apps, schema_editor):
    MasterProductImage = apps.get_model("catalog", "MasterProductImage")
    MasterProductImage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_product_condition_product_seller_note_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_images_to_fiches, reverse)
    ]
