# Generated by Django 5.1.15 on 2026-07-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_promotioncampaign'),
        ('catalog', '0017_copy_offer_images_to_fiches'),
    ]

    operations = [
    ]
