# Generated by Django 5.1.15 on 2026-07-07 19:32

from django.conf import settings
from django.db import migrations, models

def recompute_levels(apps, schema_editor):
    """
    Recalcule le champ `level` pour toutes les catégories existantes.
    Nécessaire parce que le champ vient d'être ajouté avec default=0,
    ce qui est faux pour les catégories qui ont un parent.
    """
    Category = apps.get_model("catalog", "Category")
    # Racines : level=0 (déjà bon par défaut, mais on force pour être safe)
    Category.objects.filter(parent__isnull=True).update(level=0)
    # Propagation par vagues (jusqu'à 10 niveaux, largement suffisant)
    for current_level in range(0, 10):
        children = Category.objects.filter(parent__level=current_level)
        if not children.exists():
            break
        children.update(level=current_level + 1)


def reverse_noop(apps, schema_editor):
    """Le rollback n'a rien à faire — level sera supprimé par RemoveField."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_merge_20260707_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['level', 'display_order', 'name'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Une phrase affichée en dessous du titre catégorie.', max_length=280, verbose_name='Description courte'),
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Ordre dans les listes frontend (0 = premier).', verbose_name="Ordre d'affichage"),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_name',
            field=models.CharField(blank=True, default='', help_text="Nom exact d'un composant lucide-react. Ex : Smartphone, Monitor, Headphones, Gamepad2. Vide = pas d'icône.", max_length=60, verbose_name="Nom d'icône Lucide"),
        ),
        migrations.AddField(
            model_name='category',
            name='is_deprecated',
            field=models.BooleanField(db_index=True, default=False, help_text="Catégorie legacy conservée pour la rétrocompatibilité. N'apparaît plus dans les nouveaux formulaires vendeur mais reste liée aux fiches existantes jusqu'à leur re-catégorisation.", verbose_name='Catégorie obsolète'),
        ),
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, editable=False, help_text='Calculé automatiquement. 0 = racine.', verbose_name='Profondeur'),
        ),
        migrations.AddField(
            model_name='category',
            name='requires_admin_approval',
            field=models.BooleanField(db_index=True, default=False, help_text='Si activé, toute fiche/offre créée dans cette catégorie (et ses sous-catégories) exige une validation admin renforcée avant publication. Utilisé pour drones, biométrie, batteries industrielles, amplificateurs de signal (Rule 5).', verbose_name='Modération renforcée'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=180, unique=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'display_order'], name='catalog_cat_parent__a3bae0_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'is_deprecated'], name='catalog_cat_is_acti_e2690f_idx'),
        ),

        migrations.RunPython(recompute_levels, reverse_noop),
    ]
