# Generated by Django 5.1.15 on 2026-07-07 20:47

import django.db.models.deletion
from django.utils.text import slugify
from django.db import migrations, models

def populate_brands_from_charfield(apps, schema_editor):
    """
    Peuple la table Brand à partir des valeurs distinctes non-vides du
    CharField `brand` de MasterProduct. Puis lie chaque MasterProduct à
    son Brand correspondant via brand_fk.
 
    Stratégie :
      1. Extraire les valeurs distinctes (case-insensitive, strippées)
      2. Pour chaque valeur, get_or_create un Brand (is_verified=False —
         l'admin les validera ensuite)
      3. Pour chaque MasterProduct qui a un brand non-vide, lier brand_fk
 
    Idempotent : peut être ré-exécutée sans dupliquer les Brand.
    """
    Brand = apps.get_model("catalog", "Brand")
    MasterProduct = apps.get_model("catalog", "MasterProduct")
 
    # 1. Collecter les valeurs distinctes de brand CharField (non vides)
    raw_values = (
        MasterProduct.objects
        .exclude(brand="")
        .exclude(brand__isnull=True)
        .values_list("brand", flat=True)
        .distinct()
    )
 
    # Normaliser : trim + dédupliquer case-insensitive
    # (garder la version avec la meilleure casse — "Samsung" plutôt que "SAMSUNG")
    normalized = {}
    for raw in raw_values:
        key = raw.strip().lower()
        if not key:
            continue
        # Préférer la version avec Majuscule au début si on a plusieurs casses
        current = normalized.get(key)
        candidate = raw.strip()
        if current is None or (candidate.istitle() and not current.istitle()):
            normalized[key] = candidate
 
    # 2. Créer les Brand (unverified — l'admin validera)
    brand_by_key = {}
    for key, display_name in normalized.items():
        slug_base = slugify(display_name) or "marque"
        slug = slug_base
        counter = 1
        # Éviter les collisions de slug
        while Brand.objects.filter(slug=slug).exclude(name=display_name).exists():
            slug = f"{slug_base}-{counter}"
            counter += 1
 
        brand, _created = Brand.objects.get_or_create(
            name=display_name,
            defaults={
                "slug": slug,
                "is_verified": False,   # L'admin validera après
                "is_active": True,
                "admin_note": (
                    "Créée automatiquement lors de la migration Phase 1.2 "
                    "depuis le CharField brand. À valider ou fusionner."
                ),
            },
        )
        brand_by_key[key] = brand
 
    # 3. Lier les MasterProduct à leur Brand via brand_fk
    linked_count = 0
    for mp in MasterProduct.objects.exclude(brand="").exclude(brand__isnull=True).iterator():
        key = mp.brand.strip().lower()
        brand = brand_by_key.get(key)
        if brand and mp.brand_fk_id != brand.id:
            mp.brand_fk_id = brand.id
            # save avec update_fields pour éviter les side-effects (auto_now, etc.)
            mp.save(update_fields=["brand_fk"])
            linked_count += 1
 
 
def reverse_populate(apps, schema_editor):
    """
    Rollback : détache les brand_fk mais laisse les Brand en place.
    Suppression des Brand serait dangereuse (perte de la table entière).
    """
    MasterProduct = apps.get_model("catalog", "MasterProduct")
    MasterProduct.objects.exclude(brand_fk__isnull=True).update(brand_fk=None)

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_category_hierarchy_upgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom officiel de la marque (ex : Samsung, Apple, Tecno).', max_length=120, unique=True, verbose_name='Nom de la marque')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, help_text='Logo officiel de la marque (PNG transparent recommandé, 200x200 min).', null=True, upload_to='brands/%Y/%m/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, default='', help_text='Présentation courte de la marque, affichée sur la page marque.', verbose_name='Description')),
                ('country_of_origin', models.CharField(blank=True, default='', help_text='Ex : Corée du Sud, USA, Chine, Hong Kong. Utile pour la transparence.', max_length=60, verbose_name="Pays d'origine")),
                ('website', models.URLField(blank=True, default='', verbose_name='Site officiel')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Décocher pour cacher la marque des suggestions sans la supprimer.', verbose_name='Active')),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text="Marque officielle validée par l'admin BelivaY. Les marques non vérifiées apparaissent avec un badge et peuvent être fusionnées avec une marque officielle.", verbose_name='Marque vérifiée')),
                ('admin_note', models.TextField(blank=True, default='', help_text="Note interne (ex : 'à fusionner avec Samsung', 'faux positif').", verbose_name='Note admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_fk', models.ForeignKey(blank=True, help_text='Marque référencée depuis le registre centralisé. Remplace progressivement le champ texte `brand`.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_products', to='catalog.brand', verbose_name='Marque (registre)')),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'ordering': ['-is_verified', 'name'],
                'indexes': [models.Index(fields=['is_active', 'is_verified'], name='catalog_bra_is_acti_d6c3bb_idx'), models.Index(fields=['name'], name='catalog_bra_name_1e38d9_idx')],
            },
        ),

        migrations.AddIndex(
            model_name="brand",
            index=models.Index(fields=["is_active", "is_verified"], name="brand_active_verif_idx"),
        ),
        migrations.AddIndex(
            model_name="brand",
            index=models.Index(fields=["name"], name="brand_name_idx"),
        ),
        migrations.AddField(
            model_name="masterproduct",
            name="brand_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="master_products",
                to="catalog.brand",
                help_text="Marque référencée depuis le registre centralisé. Remplace progressivement le champ texte `brand`.",
                verbose_name="Marque (registre)",
            ),
        ),

        migrations.RunPython(populate_brands_from_charfield, reverse_populate),
    ]
