# Generated by Django 5.1.15 on 2026-07-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_brand_registry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(choices=[('COLOR', 'Couleur'), ('FINISH', 'Finition')], db_index=True, default='COLOR', help_text='COLOR pour une couleur vraie, FINISH pour une finition/matériau.', max_length=8, verbose_name='Famille')),
                ('name', models.CharField(help_text='Nom affiché en français. Ex : Noir, Titane, Mat.', max_length=60, verbose_name='Nom (français)')),
                ('name_en', models.CharField(blank=True, default='', help_text='Nom affiché en anglais. Ex : Black, Titanium, Matte.', max_length=60, verbose_name='Nom (anglais)')),
                ('slug', models.SlugField(help_text='Identifiant stable, dérivé du nom français. Ne pas modifier après création.', max_length=80, unique=True, verbose_name='Slug (identifiant technique)')),
                ('hex_code', models.CharField(blank=True, default='', help_text='Format #RRGGBB. Utilisé pour rendre une pastille couleur côté frontend. Laisser vide pour les finitions non-colorées.', max_length=7, verbose_name='Code hexadécimal')),
                ('pattern_url', models.URLField(blank=True, default='', help_text="Optionnel — pour les finitions à texture visuelle (Cuir, Bois, Marbre...) ou couleurs multi-tons. URL absolue d'une image carrée, 100x100 recommandé.", verbose_name='URL image motif')),
                ('is_neutral', models.BooleanField(db_index=True, default=False, help_text="Marque les couleurs neutres (Noir, Blanc, Gris, Argent, Or). Utile pour les filtres 'Couleurs neutres uniquement' des acheteurs recherchant un smartphone sobre.", verbose_name='Neutre')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Décocher pour masquer une couleur des choix vendeur sans supprimer les valeurs existantes qui la référencent.', verbose_name='Active')),
                ('display_order', models.PositiveSmallIntegerField(default=100, help_text='Ordre dans les listes frontend. Convention : 0-99 = couleurs neutres, 100-199 = couleurs primaires, 200+ = couleurs secondaires et finitions.', verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entrée du dictionnaire couleurs/finitions',
                'verbose_name_plural': 'Dictionnaire couleurs & finitions',
                'ordering': ['family', 'display_order', 'name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='brand',
            name='brand_active_verif_idx',
        ),
        migrations.RemoveIndex(
            model_name='brand',
            name='brand_name_idx',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='brand_fk',
        ),
        migrations.AddIndex(
            model_name='colordictionary',
            index=models.Index(fields=['family', 'is_active', 'display_order'], name='catalog_col_family_5ddcfd_idx'),
        ),
        migrations.AddIndex(
            model_name='colordictionary',
            index=models.Index(fields=['is_neutral'], name='catalog_col_is_neut_93fca4_idx'),
        ),
        migrations.AddConstraint(
            model_name='colordictionary',
            constraint=models.UniqueConstraint(fields=('family', 'name'), name='colordict_family_name_unique'),
        ),
    ]
