# Generated by Django 5.1.15 on 2026-07-08 01:42

import django.db.models.deletion
from django.db import migrations, models


def set_default_roles_and_types(apps, schema_editor):
    """
    Initialise role, is_universal et values_type sur les ProductAttribute
    existants. Idempotent : ne touche pas ceux déjà configurés.
    """
    ProductAttribute = apps.get_model("catalog", "ProductAttribute")
 
    # Mapping type sémantique → values_type technique
    type_to_values_type = {
        "SIZE": "SELECT",
        "COLOR": "COLORDICT",
        "MATERIAL": "SELECT",
        "OTHER": "SELECT",
    }
 
    for attr in ProductAttribute.objects.all():
        changed = False
 
        # role : garde SPEC par défaut (déjà défini via default du modèle)
        if not attr.role:
            attr.role = "SPEC"
            changed = True
 
        # is_universal : reste False (déjà défini via default)
        # values_type : déduit du type existant si pas encore défini
        if not attr.values_type or attr.values_type == "SELECT":
            expected = type_to_values_type.get(attr.type, "SELECT")
            if attr.values_type != expected:
                attr.values_type = expected
                changed = True
 
        if changed:
            attr.save(update_fields=["role", "values_type"])
 
 
def reverse_noop(apps, schema_editor):
    """Le rollback n'a rien à faire — les champs seront supprimés."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_color_dictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterproduct',
            name='variant_axes',
            field=models.JSONField(blank=True, default=list, help_text='Liste des slugs d\'attributs (avec role=AXE) autorisés pour créer des Variants de cette fiche. Ex : ["color", "storage"] pour un iPhone. Vide = fiche mono-variant (composant atomique).', verbose_name='Axes de variante'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='is_universal',
            field=models.BooleanField(db_index=True, default=False, help_text="Si activé, l'attribut s'applique à TOUTES les catégories (ex : Bluetooth, WiFi, Poids). Dans ce cas, le champ 'category' doit être laissé vide.", verbose_name='Universel'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='role',
            field=models.CharField(choices=[('AXE', 'Axe (crée une variante)'), ('SPEC', 'Spécification (fixe du modèle, filtrable)'), ('OFFRE', 'Offre (dépend du vendeur)')], db_index=True, default='SPEC', help_text="AXE = crée une variante achetable (couleur/stockage d'un smartphone). SPEC = caractéristique fixe du modèle, filtrable. OFFRE = dépend du vendeur (état, garantie, import).", max_length=5, verbose_name='Rôle'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='values_type',
            field=models.CharField(choices=[('SELECT', 'Liste fermée (values JSON)'), ('NUMBER', 'Nombre (avec unit)'), ('BOOL', 'Oui/Non'), ('TEXT', 'Texte libre (à éviter — préférer SELECT)'), ('COLORDICT', 'Référence au dictionnaire couleurs'), ('BRAND', 'Référence au registre Brand')], default='SELECT', help_text='Détermine comment le vendeur saisit la valeur : SELECT (liste fermée), NUMBER, BOOL, TEXT, COLORDICT (piocher dans le dictionnaire couleurs), BRAND (piocher dans le registre marques).', max_length=10, verbose_name='Type de valeur'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='category',
            field=models.ForeignKey(blank=True, help_text="Catégorie à laquelle cet attribut s'applique. Laisser vide si is_universal=True.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.category', verbose_name='Catégorie'),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', True), ('is_universal', True)), models.Q(('category__isnull', False), ('is_universal', False)), _connector='OR'), name='attr_universal_xor_category'),
        ),

        migrations.RunPython(set_default_roles_and_types, reverse_noop),
    ]
