# Generated by Django 5.1.15 on 2026-07-08 01:59

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """
    Peuple le slug des ProductAttribute existants à partir du name.
    Idempotent : ne touche pas ceux qui ont déjà un slug.
    """
    ProductAttribute = apps.get_model("catalog", "ProductAttribute")
 
    used_slugs = set(
        ProductAttribute.objects
        .exclude(slug="")
        .values_list("slug", flat=True)
    )
 
    for attr in ProductAttribute.objects.filter(slug="").iterator():
        base = slugify(attr.name) or "attr"
        slug = base
        counter = 1
        while slug in used_slugs:
            slug = f"{base}-{counter}"
            counter += 1
        attr.slug = slug
        attr.save(update_fields=["slug"])
        used_slugs.add(slug)
 
 
def reverse_noop(apps, schema_editor):
    """Les champs seront supprimés par RemoveField au rollback."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_attribute_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='slug',
            field=models.SlugField(blank=True, help_text="Identifiant stable utilisé par MasterProduct.variant_axes pour référencer cet attribut. Auto-généré si vide (à partir du name). Doit être unique. Convention : préfixer par la catégorie pour les non-universels (ex : 'phone-color', 'kb-switch') et laisser simple pour les universels (ex : 'bluetooth', 'weight').", max_length=100, unique=True, verbose_name='Slug (identifiant technique)'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='unit',
            field=models.CharField(blank=True, default='', help_text="Unité de mesure affichée à côté de la valeur. Ex : 'Go' pour un stockage, 'mAh' pour une batterie, 'W' pour une puissance. Vide pour les attributs sans unité.", max_length=20, verbose_name='Unité'),
        ),

        migrations.RunPython(populate_slugs, reverse_noop),
    ]
