# Generated by Django 5.1.15 on 2026-07-08 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_attribute_slug_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('axis_values', models.JSONField(blank=True, default=dict, help_text='Dict {slug_axe: valeur}. Ex : {"phone-color": "titane", "phone-storage": "256"}. Vide = variant unique/atomique.', verbose_name='Valeurs des axes')),
                ('axis_key', models.CharField(blank=True, db_index=True, default='', editable=False, help_text="Représentation canonique triée de axis_values, pour garantir l'unicité (master, axis_values). Calculée au save().", max_length=500, verbose_name='Clé canonique (calculée)')),
                ('sku', models.CharField(blank=True, db_index=True, default='', help_text="SKU CANONIQUE de ce Variant (partagé entre tous les vendeurs). Distinct du Product.sku qui est le SKU spécifique de l'offre. Auto-généré : BLV-V-{master_id:06d}-{variant_id:04d}.", max_length=60, verbose_name='SKU canonique')),
                ('barcode', models.CharField(blank=True, db_index=True, default='', help_text='Code-barres EAN13, UPC-A, ISBN. Optionnel.', max_length=20, verbose_name='Code-barres (EAN/UPC)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('moderation_status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Validé'), ('REJECTED', 'Rejeté')], db_index=True, default='PENDING', max_length=10, verbose_name='Statut de modération')),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_reason', models.TextField(blank=True, default='')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.masterproduct', verbose_name='Fiche produit maître')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_variants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Variant produit',
                'verbose_name_plural': 'Variants produit',
                'ordering': ['master_id', 'axis_key'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.ForeignKey(blank=True, help_text="Variant précis auquel cette offre s'applique. Nullable pour rétrocompat (verticales non-Electronics). Pour Electronics : obligatoire (validation applicative).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='catalog.productvariant', verbose_name='Variant'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['master', 'is_active'], name='catalog_pro_master__781b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['moderation_status', 'is_active'], name='catalog_pro_moderat_94fa04_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('master', 'axis_key'), name='variant_master_axiskey_unique'),
        ),
    ]
