# Generated by Django 5.1.15 on 2026-08-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_productreview_order_item'),
        ('catalog', '0025_search_extensions'),
    ]

    operations = [
    ]
