# Generated by Django 5.1.15 on 2026-08-31 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_merge_20260821_0951'),
        ('catalog', '0026_merge_20260821_1328'),
    ]

    operations = [
    ]
