# Generated by Django 5.1.15 on 2026-09-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_merge_20260831_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='faq',
            field=models.JSONField(blank=True, default=list, help_text="FAQ produit à remplir par le vendeur : liste de {question, answer}. Compense l'absence de messagerie directe acheteur-vendeur — Addendum Décisions v1.0, Portail vendeur."),
        ),
    ]
