# Generated by Django 5.1.15 on 2026-09-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_product_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text="Bannière pour une catégorie racine, pastille ronde pour une sous-catégorie. Convertie en WebP à l'enregistrement.", null=True, upload_to='categories/%Y/%m/', verbose_name='Image'),
        ),
    ]
