# Generated by Django 5.1.15 on 2026-04-22 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userfavorite_usernotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='Double authentification activée'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_method',
            field=models.CharField(blank=True, choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', max_length=10, verbose_name='Méthode 2FA'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_phone',
            field=models.CharField(blank=True, help_text="Renseigné par l'utilisateur. Vérification à venir.", max_length=20, verbose_name='Numéro pour 2FA SMS/WhatsApp'),
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('2FA_LOGIN', 'Connexion 2FA'), ('2FA_ENABLE', 'Activation 2FA'), ('2FA_DISABLE', 'Désactivation 2FA')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code OTP',
                'verbose_name_plural': 'Codes OTP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True, verbose_name='JWT ID')),
                ('device_name', models.CharField(blank=True, max_length=200, verbose_name='Appareil')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Navigateur')),
                ('os_name', models.CharField(blank=True, max_length=100, verbose_name='Système')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session utilisateur',
                'verbose_name_plural': 'Sessions utilisateurs',
                'ordering': ['-last_activity'],
            },
        ),
    ]
