# Generated by Codex on 2026-07-08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_deliveryorganizationprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RelayPointProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("manager_name", models.CharField(blank=True, default="", max_length=120)),
                ("phone", models.CharField(max_length=20)),
                ("city", models.CharField(blank=True, default="", max_length=80)),
                ("zones", models.JSONField(blank=True, default=list)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("relay_code", models.CharField(blank=True, default="", max_length=80)),
                ("opening_hours", models.CharField(blank=True, default="", max_length=160)),
                ("storage_capacity", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("APPROVED", "Approuve"),
                            ("SUSPENDED", "Suspendu"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relay_point_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Point relais",
                "verbose_name_plural": "Points relais",
                "ordering": ["name"],
            },
        ),
    ]
