# Generated by Codex on 2026-07-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_relaypointprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="courierprofile",
            name="delivery_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="couriers",
                to="accounts.deliveryorganizationprofile",
            ),
        ),
    ]
