# Generated by Codex on 2026-07-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_courierprofile_delivery_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="courierprofile",
            name="max_active_shipments",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="deliveryorganizationprofile",
            name="allowed_vehicle_types",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="deliveryorganizationprofile",
            name="max_active_shipments",
            field=models.PositiveIntegerField(default=50),
        ),
    ]
