# Generated by Django 5.1.15 on 2026-08-21 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_trustscoreprofile_and_transport_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayTrainingCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(choices=[('reception', 'Reception & garde des colis'), ('cni', 'Verification CNI & cross-check ANTIC'), ('stockage', 'Securite du stockage'), ('litige', 'Gerer un litige & le mediateur'), ('relation', 'Relation acheteur & avis'), ('pidgin', 'Service en Pidgin')], max_length=30)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('relay_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_completions', to='accounts.relaypointprofile')),
            ],
            options={
                'verbose_name': 'Module de formation valide',
                'verbose_name_plural': 'Modules de formation valides',
                'ordering': ['-completed_at'],
                'constraints': [models.UniqueConstraint(fields=('relay_point', 'module_key'), name='unique_training_module_per_relay_point')],
            },
        ),
    ]
