# Generated by Django 5.1.15 on 2026-09-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_relaytrainingcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='relaypointprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Position GPS du point relais, utilisee pour le routage acheteur (point le plus proche avec de la place).', max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='relaypointprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
