# Generated by Django 5.1.15 on 2026-09-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_relaypointprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='non_retrait_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de non-retraits au relais'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='requires_prepayment',
            field=models.BooleanField(default=False, help_text="Déclenché après non-retraits répétés — sans effet tant qu'aucun mode de paiement différé n'existe.", verbose_name='Compte basculé en prépaiement obligatoire'),
        ),
    ]
