# Generated by Django 5.1.15 on 2026-09-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userprofile_non_retrait_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustscoreprofile',
            name='audit_passed',
            field=models.BooleanField(default=False, help_text="Verification manuelle admin requise pour Or/Platine vendeur (V5.5). A renouveler par l'admin (trimestriel pour Platine)."),
        ),
        migrations.AddField(
            model_name='trustscoreprofile',
            name='volume',
            field=models.PositiveIntegerField(default=0, help_text='Commandes livrees (vendeur) / colis geres (relais) / courses terminees (livreur) — jauge les paliers V5.5.'),
        ),
        migrations.AlterField(
            model_name='trustscoreprofile',
            name='candidate_tier',
            field=models.CharField(blank=True, choices=[('NEW', 'Nouveau'), ('CONFIRMED', 'Confirmé'), ('GOLD', 'Or'), ('PLATINUM', 'Platine')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='trustscoreprofile',
            name='score',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AlterField(
            model_name='trustscoreprofile',
            name='tier',
            field=models.CharField(choices=[('NEW', 'Nouveau'), ('CONFIRMED', 'Confirmé'), ('GOLD', 'Or'), ('PLATINUM', 'Platine')], default='NEW', max_length=20),
        ),
    ]
