# Generated by Django 5.1.15 on 2026-09-04 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_trustscoreprofile_audit_passed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trustscoreprofile',
            name='frozen_until',
            field=models.DateTimeField(blank=True, help_text="Niveau 3 : compte gelé jusqu'à cette date. À l'expiration, réhabilitation par re-cold-start (jamais restauration du score gelé).", null=True),
        ),
        migrations.AddField(
            model_name='trustscoreprofile',
            name='sanction_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Aucune'), (1, 'Avertissement'), (2, 'Throttling'), (3, 'Suspension'), (4, 'Bannissement')], default=0),
        ),
        migrations.AddField(
            model_name='trustscoreprofile',
            name='throttled_until',
            field=models.DateTimeField(blank=True, help_text="Niveau 2 : visibilité/dispatch réduits jusqu'à cette date.", null=True),
        ),
        migrations.AlterField(
            model_name='trustscoreprofile',
            name='role',
            field=models.CharField(choices=[('VENDOR', 'Vendeur'), ('COURIER', 'Livreur'), ('RELAY_POINT', 'Point relais'), ('BUYER', 'Acheteur (IFA interne)')], max_length=20),
        ),
        migrations.CreateModel(
            name='SanctionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Aucune'), (1, 'Avertissement'), (2, 'Throttling'), (3, 'Suspension'), (4, 'Bannissement')])),
                ('reason', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, help_text='Niveaux 2/3 : levée automatique prévue à cette date. Vide = niveau 1 (log) ou niveau 4 (permanent).', null=True)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, help_text='Vide = déclenché automatiquement par le système (ex. véto anti-collusion).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_sanctions', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='accounts.trustscoreprofile')),
            ],
            options={
                'verbose_name': 'Sanction',
                'verbose_name_plural': 'Sanctions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_type', models.CharField(choices=[('CNI', "Pièce d'identité"), ('MOMO', 'Numéro Mobile Money'), ('DEVICE', 'Empreinte appareil')], max_length=10)),
                ('identifier_hash', models.CharField(db_index=True, help_text='SHA-256 de la valeur normalisée.', max_length=64)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sanction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklist_entries', to='accounts.sanctionrecord')),
            ],
            options={
                'verbose_name': 'Blacklist partenaire',
                'verbose_name_plural': 'Blacklist partenaires',
                'constraints': [models.UniqueConstraint(fields=('identifier_type', 'identifier_hash'), name='unique_blacklist_identifier')],
            },
        ),
    ]
