# Generated by Django 5.1.15 on 2026-09-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_trustscoreprofile_frozen_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.CharField(choices=[('VENDOR', 'Vendeur'), ('COURIER', 'Livreur'), ('DELIVERY_ORG', 'Organisation de livraison'), ('RELAY_POINT', 'Point relais')], max_length=20, unique=True)),
                ('version', models.CharField(help_text='Ex. 1.2.0', max_length=30)),
                ('apk_url', models.URLField(help_text="Lien direct vers l'APK (heberge sur le domaine BelivaY, jamais un lien de stockage brut).", max_length=500)),
                ('release_notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Version d'appli partenaire",
                'verbose_name_plural': "Versions d'applis partenaires",
            },
        ),
    ]
