# Generated by Django 5.1.15 on 2026-10-01 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_apprelease'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayNotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_enabled', models.BooleanField(default=True)),
                ('courier_approach', models.BooleanField(default=True)),
                ('settlements', models.BooleanField(default=True)),
                ('score_and_sanctions', models.BooleanField(default=True)),
                ('digest_hour', models.PositiveSmallIntegerField(default=7)),
                ('quiet_from_hour', models.PositiveSmallIntegerField(default=22)),
                ('quiet_to_hour', models.PositiveSmallIntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relay_notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferences de notification du point relais',
                'verbose_name_plural': 'Preferences de notification des points relais',
            },
        ),
    ]
