# Generated by Django 5.1.15 on 2026-10-02 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_relaynotificationpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('role', models.CharField(choices=[('OWNER', 'Proprietaire'), ('EMPLOYEE', 'Employe')], default='EMPLOYEE', max_length=12)),
                ('can_receive', models.BooleanField(default=True)),
                ('can_hand_over', models.BooleanField(default=True)),
                ('can_money', models.BooleanField(default=False)),
                ('can_settings', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relay_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounts.relaypointprofile')),
            ],
            options={
                'verbose_name': "Membre d'equipe du point relais",
                'verbose_name_plural': "Membres d'equipe des points relais",
                'ordering': ['-role', 'created_at'],
            },
        ),
    ]
