# Generated by Django 5.1.15 on 2026-10-03 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_relayaccesspin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayEmployeeInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('invited_by_name', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptee'), ('REVOKED', 'Annulee'), ('EXPIRED', 'Expiree')], default='PENDING', max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='accounts.relayemployee')),
                ('relay_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.relaypointprofile')),
            ],
            options={
                'verbose_name': "Invitation d'employe",
                'verbose_name_plural': "Invitations d'employes",
                'ordering': ['-created_at'],
            },
        ),
    ]
