# Generated by Django 5.1.15 on 2026-10-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_relayemployee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='relaypointprofile',
            name='accepts_bulky',
            field=models.BooleanField(default=True, help_text='Decoche : les colis encombrants ne sont plus attribues a ce relais.', verbose_name='Accepte les encombrants'),
        ),
    ]
