# Generated by Django 5.1.15 on 2026-10-07 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_appleidentity'),
        ('accounts', '0027_relaypointprofile_accepts_bulky'),
    ]

    operations = [
    ]
