# Generated by Django 5.1.15 on 2026-10-04 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeFamille",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=12, unique=True)),
                ("jusqua", models.DateTimeField()),
                ("utilise_le", models.DateTimeField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="codes_famille", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Code famille",
                "verbose_name_plural": "Codes famille",
            },
        ),
        migrations.CreateModel(
            name="CompteDiaspora",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pays", models.CharField(max_length=60)),
                ("ville", models.CharField(max_length=80)),
                ("indicatif", models.CharField(max_length=6)),
                ("numero_chiffre", models.BinaryField(help_text="numéro étranger vérifié par SMS, chiffré (CAP-21)")),
                ("numero_empreinte", models.CharField(db_index=True, max_length=64)),
                ("numero_masque", models.CharField(max_length=40)),
                (
                    "devise",
                    models.CharField(choices=[("XAF", "Franc CFA"), ("EUR", "Euro"), ("USD", "Dollar US")], default="XAF", max_length=3),
                ),
                ("naissance", models.DateField()),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="compte_diaspora", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte diaspora",
                "verbose_name_plural": "Comptes diaspora",
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=12, unique=True)),
                ("jusqua", models.DateTimeField()),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="invitations_diaspora", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitation diaspora",
                "verbose_name_plural": "Invitations diaspora",
            },
        ),
        migrations.CreateModel(
            name="LienFamille",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "prenom_invite",
                    models.CharField(blank=True, default="", help_text="prénom donné à l'invitation par numéro", max_length=80),
                ),
                ("numero_chiffre", models.BinaryField(blank=True, help_text="invitation par numéro : chiffré (CAP-21)", null=True)),
                ("numero_empreinte", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("invite", "Invité (en attente du proche)"),
                            ("actif", "Actif"),
                            ("refuse", "Refusé par le proche"),
                            ("retire", "Retiré"),
                        ],
                        default="invite",
                        max_length=7,
                    ),
                ),
                ("relay_id", models.PositiveBigIntegerField(blank=True, help_text="relais choisi par le proche", null=True)),
                (
                    "domicile",
                    models.BooleanField(default=False, help_text="le proche accepte la livraison chez lui (adresse jamais montrée)"),
                ),
                ("prefere", models.CharField(choices=[("relais", "Relais"), ("domicile", "Domicile")], default="relais", max_length=8)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "diaspora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="liens_diaspora", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "proche",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liens_proche",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien famille",
                "verbose_name_plural": "Liens famille",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="DemandeProche",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lignes", models.JSONField(help_text="[{product_id, titre, qte, prix, boutique, classe}] au moment de l'envoi")),
                ("sous_total", models.PositiveIntegerField()),
                ("livraison", models.CharField(default="relais", max_length=8)),
                ("frais_relais", models.PositiveIntegerField()),
                ("frais_domicile", models.PositiveIntegerField()),
                ("mot", models.CharField(blank=True, default="", max_length=120)),
                ("jusqua", models.DateTimeField()),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("attente", "En attente"),
                            ("payee", "Payée"),
                            ("refusee", "Refusée"),
                            ("annulee", "Annulée"),
                            ("expiree", "Expirée"),
                        ],
                        default="attente",
                        max_length=8,
                    ),
                ),
                ("order_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("mot_refus", models.CharField(blank=True, default="", max_length=120)),
                ("supplement_par", models.CharField(blank=True, default="", max_length=12)),
                ("payee_le", models.DateTimeField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "lien",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="demandes", to="diaspora.lienfamille"),
                ),
            ],
            options={
                "verbose_name": "Panier envoyé à un proche diaspora",
                "verbose_name_plural": "Paniers envoyés aux proches diaspora",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="CommandeDiaspora",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_id", models.PositiveBigIntegerField(unique=True)),
                ("montant", models.PositiveIntegerField(help_text="francs, frais de service compris")),
                ("devise", models.CharField(default="EUR", max_length=3)),
                ("en_devise", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("taux", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ("carte", models.CharField(blank=True, default="", help_text="« Visa •••• 4242 »", max_length=40)),
                ("articles", models.PositiveIntegerField(default=0)),
                ("mot", models.CharField(blank=True, default="", max_length=80)),
                ("livraison", models.CharField(default="relais", max_length=8)),
                ("moyen", models.CharField(default="carte", max_length=6)),
                ("a_la_remise", models.PositiveIntegerField(default=0)),
                ("pays_carte", models.CharField(blank=True, default="", max_length=60)),
                ("reference", models.CharField(blank=True, default="", max_length=80)),
                (
                    "etat_paiement",
                    models.CharField(
                        choices=[("action", "3-D Secure à valider"), ("paye", "Payé"), ("rembourse", "Remboursé")],
                        default="paye",
                        max_length=10,
                    ),
                ),
                ("rembourse", models.PositiveIntegerField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "payeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="commandes_pour_proches", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "demande",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="diaspora.demandeproche"
                    ),
                ),
                (
                    "lien",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="commandes", to="diaspora.lienfamille"),
                ),
            ],
            options={
                "verbose_name": "Commande pour un proche",
                "verbose_name_plural": "Commandes pour des proches",
                "ordering": ["-id"],
            },
        ),
    ]
