# Generated by Django 5.1.15 on 2026-10-05 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diaspora", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comptediaspora",
            name="proche_actif",
            field=models.ForeignKey(
                blank=True,
                help_text="« Pour qui ? » (choisirProche)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="diaspora.lienfamille",
            ),
        ),
    ]
