# Generated by Django 5.1.15 on 2026-10-04 23:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Litige",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_id", models.PositiveBigIntegerField(db_index=True, help_text="orders.Order de relaya-marketplace")),
                ("colis", models.PositiveSmallIntegerField(help_text="numéro du colis (pickup.SousCommande.n)")),
                ("product_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("produit", models.CharField(max_length=200)),
                ("relay_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "pb",
                    models.CharField(
                        choices=[
                            ("jamais", "Jamais reçu"),
                            ("abime", "Abîmé"),
                            ("pas-commande", "Pas ce que j’ai commandé"),
                            ("manque", "Il manque quelque chose"),
                            ("autre", "Autre chose"),
                        ],
                        max_length=14,
                    ),
                ),
                ("probleme", models.CharField(help_text="libellé affiché (« Abîmé », « Semelle fendue »)", max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "souhait",
                    models.CharField(
                        choices=[("rembourse", "Un remboursement"), ("remplace", "Un remplacement"), ("signal", "Signaler seulement")],
                        max_length=10,
                    ),
                ),
                (
                    "origine",
                    models.CharField(
                        choices=[("appli", "Application"), ("comptoir", "Constat au comptoir"), ("auto", "Remboursement immédiat")],
                        default="appli",
                        max_length=10,
                    ),
                ),
                ("montant", models.PositiveIntegerField(help_text="bloqué pendant le litige : prix des articles du colis")),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("ouvert", "Ouvert"),
                            ("attente_vendeur", "Le vendeur a 48 h pour répondre"),
                            ("en_examen", "En examen"),
                            ("decide", "Décision"),
                            ("rembourse_automatiquement", "Remboursé automatiquement"),
                        ],
                        default="ouvert",
                        max_length=26,
                    ),
                ),
                (
                    "etat_colis_avant",
                    models.CharField(blank=True, default="", help_text="état du colis avant le litige (retrait du dossier)", max_length=24),
                ),
                ("palier_ifa", models.CharField(blank=True, default="", help_text="palier IFA du client à l'ouverture", max_length=12)),
                ("ouvert_le", models.DateTimeField(default=django.utils.timezone.now)),
                ("echeance_vendeur", models.DateTimeField(help_text="LIT-VENDEUR-H après l'ouverture")),
                ("decision_au_plus_tard", models.DateTimeField(help_text="LIT-DECISION-H après l'échéance du vendeur")),
                (
                    "reponse_vendeur",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Pas encore"),
                            ("accepte", "Accepte"),
                            ("conteste", "Conteste"),
                            ("arrangement", "Propose un arrangement"),
                            ("silence", "Sans réponse"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                ("arrangement_montant", models.PositiveIntegerField(blank=True, null=True)),
                ("arrangement_texte", models.TextField(blank=True, default="")),
                ("arrangement_propose_le", models.DateTimeField(blank=True, null=True)),
                ("arrangement_repondu_le", models.DateTimeField(blank=True, null=True)),
                ("arrangement_accepte", models.BooleanField(blank=True, null=True)),
                ("decision_le", models.DateTimeField(blank=True, null=True)),
                ("decision_motif", models.TextField(blank=True, default="", help_text="motif écrit, obligatoire")),
                (
                    "issue",
                    models.CharField(
                        blank=True,
                        choices=[("", "Pas encore"), ("rembourse", "Remboursement"), ("remplace", "Remplacement"), ("refuse", "Débouté")],
                        default="",
                        max_length=10,
                    ),
                ),
                ("rembourse", models.PositiveIntegerField(default=0, help_text="argent rendu au client pour ce dossier")),
                ("recours_le", models.DateTimeField(blank=True, null=True)),
                ("recours_motif", models.TextField(blank=True, default="")),
                ("retire_le", models.DateTimeField(blank=True, null=True)),
                ("clos_le", models.DateTimeField(blank=True, help_text="fin de la suspension (garde, libération)", null=True)),
                ("version_parametres", models.CharField(blank=True, default="", max_length=40)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="litiges_client", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Litige",
                "verbose_name_plural": "Litiges",
                "ordering": ["-ouvert_le"],
            },
        ),
        migrations.CreateModel(
            name="PreuveLitige",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titre", models.CharField(max_length=120)),
                ("sous", models.CharField(blank=True, default="", max_length=160)),
                ("photo", models.FileField(upload_to="litiges/%Y/%m/")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("client", "Le client (dossier)"),
                            ("conversation", "Le client (conversation du dossier)"),
                            ("relais", "Le relais"),
                            ("livreur", "Le livreur"),
                        ],
                        default="client",
                        max_length=14,
                    ),
                ),
                ("ajoutee_le", models.DateTimeField(default=django.utils.timezone.now, help_text="horodatée par le serveur")),
                ("litige", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="preuves", to="aftersales.litige")),
            ],
            options={
                "verbose_name": "Preuve d'un litige",
                "verbose_name_plural": "Preuves des litiges",
                "ordering": ["ajoutee_le", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Remplacement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("attente", "Le vendeur renvoie l'article"),
                            ("autre_vendeur", "Un autre vendeur l'a"),
                            ("expedie", "Nouvel article en route"),
                            ("remis", "Remis"),
                            ("rembourse", "Remboursé"),
                        ],
                        default="attente",
                        max_length=14,
                    ),
                ),
                ("debut", models.DateTimeField(default=django.utils.timezone.now)),
                ("avant", models.DateTimeField(help_text="RET-REMPL-DELAI heures ouvrées, dimanche non compté")),
                ("expedie_le", models.DateTimeField(blank=True, null=True)),
                ("remis_le", models.DateTimeField(blank=True, null=True)),
                ("vendeurs_essayes", models.JSONField(blank=True, default=list, help_text="vendor_id déjà sollicités (DP-01)")),
                ("autre_vendor_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("autre_product_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("autre_boutique", models.CharField(blank=True, default="", max_length=255)),
                ("autre_trust", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("ecart", models.PositiveIntegerField(default=0, help_text="payé par BelivaY, le client garde son prix")),
                ("autre_accepte_le", models.DateTimeField(blank=True, null=True)),
                (
                    "litige",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="remplacement", to="aftersales.litige"),
                ),
            ],
            options={
                "verbose_name": "Remplacement",
                "verbose_name_plural": "Remplacements",
            },
        ),
        migrations.CreateModel(
            name="Retour",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("accepte", "À déposer"),
                            ("retour_depose", "Retour déposé"),
                            ("collecte", "Récupéré par le livreur"),
                            ("recu", "Le vendeur inspecte"),
                            ("retour_inspecte", "Inspecté"),
                            ("clos", "Clos"),
                        ],
                        default="accepte",
                        max_length=16,
                    ),
                ),
                ("accepte_le", models.DateTimeField(default=django.utils.timezone.now)),
                ("deposer_avant", models.DateTimeField()),
                ("depose_le", models.DateTimeField(blank=True, null=True)),
                ("collecte_le", models.DateTimeField(blank=True, null=True)),
                ("recu_le", models.DateTimeField(blank=True, null=True)),
                ("inspecte_le", models.DateTimeField(blank=True, null=True)),
                ("clos_le", models.DateTimeField(blank=True, null=True)),
                ("en_tort", models.CharField(blank=True, default="", help_text="client | vendeur | transporteur", max_length=12)),
                ("rembourse", models.PositiveIntegerField(default=0)),
                (
                    "litige",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="retour", to="aftersales.litige"),
                ),
            ],
            options={
                "verbose_name": "Retour",
                "verbose_name_plural": "Retours",
            },
        ),
        migrations.CreateModel(
            name="VoteAvis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("review_id", models.PositiveBigIntegerField(help_text="catalog.ProductReview de relaya-marketplace")),
                ("utile", models.BooleanField(default=False)),
                ("signale_le", models.DateTimeField(blank=True, null=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="votes_avis", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Vote sur un avis produit",
                "verbose_name_plural": "Votes sur les avis produit",
            },
        ),
        migrations.CreateModel(
            name="AvisCommande",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_id", models.PositiveBigIntegerField()),
                ("notes", models.JSONField(help_text="une par colis (le vendeur), puis le relais")),
                ("commentaire", models.TextField(blank=True, default="")),
                ("photo", models.FileField(blank=True, default="", upload_to="avis/%Y/%m/")),
                ("note_basse", models.BooleanField(default=False, help_text="AVIS-BAS : un litige a été proposé")),
                ("envoye_le", models.DateTimeField(default=django.utils.timezone.now)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="avis_commandes", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Avis sur une commande",
                "verbose_name_plural": "Avis sur les commandes",
                "constraints": [models.UniqueConstraint(fields=("client", "order_id"), name="aftersales_avis_commande_unique")],
            },
        ),
        migrations.AddConstraint(
            model_name="litige",
            constraint=models.UniqueConstraint(
                condition=models.Q(("retire_le__isnull", True)), fields=("order_id", "colis"), name="aftersales_un_dossier_par_colis"
            ),
        ),
        migrations.AddConstraint(
            model_name="voteavis",
            constraint=models.UniqueConstraint(fields=("client", "review_id"), name="aftersales_un_vote_par_client"),
        ),
    ]
