# Generated by Django 5.1.15 on 2026-07-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_shipment_acceptance_penalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentmessage',
            name='sender_role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('COURIER', 'Livreur'), ('SYSTEM', 'Systeme')], default='COURIER', max_length=16),
        ),
    ]
