# Generated by Codex on 2026-07-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_delivery_capacity_vehicle"),
        ("shipping", "0006_alter_shipmentmessage_sender_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="assignment_issue_code",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="shipment",
            name="assignment_issue_message",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="shipment",
            name="parcel_size",
            field=models.CharField(blank=True, default="STANDARD", max_length=20),
        ),
        migrations.AddField(
            model_name="shipment",
            name="required_vehicle_type",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("WAITING_MANUAL_ASSIGNMENT", "Waiting manual assignment"),
                    ("ZONE_UNCOVERED", "Zone uncovered"),
                    ("CAPACITY_BLOCKED", "Capacity blocked"),
                    ("VEHICLE_INCOMPATIBLE", "Vehicle incompatible"),
                    ("ASSIGNED", "Assigned"),
                    ("PICKED_UP", "Picked up"),
                    ("IN_TRANSIT", "In transit"),
                    ("OUT_FOR_DELIVERY", "Out for delivery"),
                    ("DELIVERED", "Delivered"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="CREATED",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="RelayParcel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EXPECTED", "Attendu"),
                            ("RECEIVED", "Recu"),
                            ("STORED", "Stocke"),
                            ("PICKED_UP", "Retire"),
                            ("RETURN_REQUESTED", "Retour demande"),
                            ("RETURNED_TO_VENDOR", "Retour vendeur"),
                            ("RETURNED_TO_BELIVAY", "Retour BelivaY"),
                        ],
                        default="EXPECTED",
                        max_length=24,
                    ),
                ),
                ("slot_code", models.CharField(blank=True, default="", max_length=80)),
                ("pickup_code", models.CharField(blank=True, default="", max_length=24)),
                ("proof_note", models.TextField(blank=True, default="")),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relay_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcels",
                        to="accounts.relaypointprofile",
                    ),
                ),
                (
                    "shipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relay_parcel",
                        to="shipping.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Colis point relais",
                "verbose_name_plural": "Colis points relais",
                "ordering": ["-updated_at"],
            },
        ),
    ]
