# Generated by Django 5.1.15 on 2026-08-14 13:01

import apps.shipping.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_disputeevidencerequest_and_more'),
        ('shipping', '0008_shipmentlocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('VENDOR_PACKED', 'Emballage vendeur'), ('COURIER_PICKUP_VENDOR', 'Enlèvement vendeur'), ('RELAY_RECEIVED', 'Réception point relais'), ('RELAY_RELEASED', 'Sortie point relais'), ('CUSTOMER_DELIVERY', 'Remise client'), ('RETURN_DEPOSIT', 'Dépôt retour')], max_length=30)),
                ('actor_role', models.CharField(max_length=20)),
                ('file', models.FileField(blank=True, upload_to='shipment-evidences/%Y/%m/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('retain_until', models.DateTimeField(default=apps.shipping.models.shipment_evidence_retention_deadline)),
                ('litigation_hold', models.BooleanField(default=False)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_evidences', to='orders.orderitem')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='shipping.shipment')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_evidences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['retain_until', 'litigation_hold', 'purged_at'], name='shipping_sh_retain__54db65_idx'), models.Index(fields=['shipment', 'stage'], name='shipping_sh_shipmen_026f12_idx')],
            },
        ),
    ]
