# Generated by Django 5.1.15 on 2026-08-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0010_shipment_value_limit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='receipt_confirmation_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
