# Generated by Django 5.1.15 on 2026-08-21 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_trustscoreprofile_and_transport_insurance'),
        ('shipping', '0011_shipment_receipt_confirmation_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayPointReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Note de 1 a 5 etoiles.')),
                ('comment', models.TextField(blank=True, default='')),
                ('thanked_at', models.DateTimeField(blank=True, help_text="Date a laquelle le gerant a remercie l'acheteur.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relay_point_reviews', to=settings.AUTH_USER_MODEL)),
                ('relay_parcel', models.OneToOneField(blank=True, help_text="Retrait qui autorise cet avis. Un colis ne peut etre note qu'une fois.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='shipping.relayparcel')),
                ('relay_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.relaypointprofile')),
            ],
            options={
                'verbose_name': 'Avis point relais',
                'verbose_name_plural': 'Avis points relais',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['relay_point', '-created_at'], name='shipping_re_relay_p_78cf80_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='relay_review_rating_between_1_and_5')],
            },
        ),
    ]
