# Generated by Django 5.1.15 on 2026-09-02 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_order_relay_point_return'),
        ('shipping', '0013_alter_shipment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('city', models.CharField(max_length=80)),
                ('tier', models.CharField(choices=[('STANDARD', 'Standard'), ('VAGUE_3', 'Vague 3 (périphérie)')], default='STANDARD', max_length=20)),
                ('districts', models.JSONField(blank=True, default=list, help_text='Quartiers rattachés à cette zone (comparaison texte, insensible à la casse).')),
                ('is_active', models.BooleanField(default=True)),
                ('surcharge_xaf', models.PositiveIntegerField(default=0, help_text="Supplément appliqué aux commandes vers cette zone si tier=VAGUE_3. Non décidé par défaut (0) — à fixer par l'admin.", verbose_name='Majoration (FCFA)')),
                ('is_bootstrapping', models.BooleanField(default=False)),
                ('bootstrap_budget_xaf', models.PositiveIntegerField(default=0)),
                ('bootstrap_target_colis_per_tournee', models.PositiveIntegerField(default=8)),
                ('bootstrap_started_at', models.DateTimeField(blank=True, null=True)),
                ('morning_slot_start', models.TimeField(blank=True, null=True)),
                ('morning_slot_end', models.TimeField(blank=True, null=True)),
                ('afternoon_slot_start', models.TimeField(blank=True, null=True)),
                ('afternoon_slot_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='buyer_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_confirmation_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='shipment',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendeur de ce colis — un Shipment = un colis = un vendeur (règle mère).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_colis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order'),
        ),
    ]
