# Generated by Django 5.1.15 on 2026-09-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0014_zone_shipment_buyer_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relayparcel',
            name='garde_extended',
            field=models.BooleanField(default=False, help_text="L'acheteur a utilise sa prolongation unique de garde (repousse l'echeance J+7)."),
        ),
        migrations.AddField(
            model_name='relayparcel',
            name='non_retrait_processed_at',
            field=models.DateTimeField(blank=True, help_text='Date a laquelle le non-retrait a ete traite (retour vendeur + remboursement partiel).', null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='surcharge_xaf',
            field=models.PositiveIntegerField(default=1000, help_text="Supplément appliqué aux commandes vers cette zone si tier=VAGUE_3. 1000F provisoire (Addendum Décisions v1.0) — ajustable par l'admin.", verbose_name='Majoration (FCFA)'),
        ),
    ]
