# Generated by Django 5.1.15 on 2026-09-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0015_relayparcel_garde_extended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relayparcel',
            name='picked_up_by_id_reference',
            field=models.CharField(blank=True, default='', help_text="Type + numero de piece d'identite du tiers ayant retire le colis, loggue par le relais.", max_length=100),
        ),
        migrations.AddField(
            model_name='relayparcel',
            name='picked_up_by_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
