# Generated by Django 5.1.15 on 2026-09-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0016_relayparcel_picked_up_by_id_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relayparcel',
            name='status',
            field=models.CharField(choices=[('EXPECTED', 'Attendu'), ('RECEIVED', 'Recu'), ('STORED', 'Stocke'), ('PICKED_UP', 'Retire'), ('RETURN_REQUESTED', 'Retour demande'), ('RETURNED_TO_VENDOR', 'Retour vendeur'), ('RETURNED_TO_BELIVAY', 'Retour BelivaY'), ('REFUSED', 'Refuse au controle')], default='EXPECTED', max_length=24),
        ),
        migrations.AlterField(
            model_name='shipmentevidence',
            name='stage',
            field=models.CharField(choices=[('VENDOR_PACKED', 'Emballage vendeur'), ('COURIER_PICKUP_VENDOR', 'Enlèvement vendeur'), ('RELAY_RECEIVED', 'Réception point relais'), ('RELAY_REFUSED', 'Refus au contrôle relais'), ('RELAY_RELEASED', 'Sortie point relais'), ('CUSTOMER_DELIVERY', 'Remise client'), ('RETURN_DEPOSIT', 'Dépôt retour')], max_length=30),
        ),
    ]
