# Generated by Django 5.1.15 on 2026-09-03 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userprofile_non_retrait_count_and_more'),
        ('shipping', '0017_alter_relayparcel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='stop_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zone',
            name='tier',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('VAGUE_2', 'Vague 2'), ('VAGUE_3', 'Vague 3 (périphérie)')], default='STANDARD', max_length=20),
        ),
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField()),
                ('period', models.CharField(choices=[('MORNING', 'Matin'), ('AFTERNOON', 'Après-midi')], max_length=12)),
                ('status', models.CharField(choices=[('COMPOSED', 'Composée'), ('DEPARTED', 'Partie'), ('COMPLETED', 'Terminée')], default='COMPOSED', max_length=12)),
                ('is_forced_exit', models.BooleanField(default=False, help_text="Sortie forcee sous le seuil de 4 colis, apres deux creneaux d'attente (regle n°11 : journalisee ici).")),
                ('colis_count', models.PositiveIntegerField(default=0)),
                ('composed_at', models.DateTimeField(auto_now_add=True)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournees', to='accounts.courierprofile')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournees', to='shipping.zone')),
            ],
            options={
                'ordering': ['-composed_at'],
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='tournee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='shipping.tournee'),
        ),
        migrations.AddIndex(
            model_name='tournee',
            index=models.Index(fields=['zone', 'slot_date', 'period'], name='shipping_to_zone_id_374aa5_idx'),
        ),
    ]
