# Generated by Django 5.1.15 on 2026-09-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0018_shipment_stop_order_alter_zone_tier_tournee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentevidence',
            name='stage',
            field=models.CharField(choices=[('VENDOR_PACKED', 'Emballage vendeur'), ('COURIER_PICKUP_VENDOR', 'Enlèvement vendeur'), ('RELAY_RECEIVED', 'Réception point relais'), ('RELAY_REFUSED', 'Refus au contrôle relais'), ('RELAY_RELEASED', 'Sortie point relais'), ('RELAY_RELEASED_SIGNATURE', 'Signature au retrait relais'), ('CUSTOMER_DELIVERY', 'Remise client'), ('RETURN_DEPOSIT', 'Dépôt retour')], max_length=30),
        ),
    ]
