# Generated by Django 5.1.15 on 2026-09-03 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_trustscoreprofile_audit_passed_and_more'),
        ('shipping', '0019_alter_shipmentevidence_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournee',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournee',
            name='claimed_by_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_tournees', to='accounts.deliveryorganizationprofile'),
        ),
        migrations.AlterField(
            model_name='tournee',
            name='status',
            field=models.CharField(choices=[('COMPOSED', 'Composée'), ('PUBLISHED', 'Publiée sur la bourse'), ('DEPARTED', 'Partie'), ('COMPLETED', 'Terminée')], default='COMPOSED', max_length=12),
        ),
    ]
