# Generated by Django 5.1.15 on 2026-10-07 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_merge_20261007_0241'),
        ('shipping', '0020_tournee_claimed_at_tournee_claimed_by_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayPickupAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24)),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relay_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_attempts', to='accounts.relaypointprofile')),
            ],
            options={
                'verbose_name': 'Tentative de retrait',
                'verbose_name_plural': 'Tentatives de retrait',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['relay_point', 'code', '-created_at'], name='shipping_re_relay_p_4745d6_idx')],
            },
        ),
    ]
