# Generated by Django 5.1.15 on 2026-10-07 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0021_relaypickupattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentevent',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='Compte ayant déclenché ce changement — vide pour une transition automatique.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipmentevent',
            name='actor_role',
            field=models.CharField(blank=True, default='', help_text="Rôle de l'acteur au moment de l'action (VENDOR, COURIER, RELAY_POINT, CLIENT, SUPPORT, SYSTEM).", max_length=20),
        ),
        migrations.AddField(
            model_name='shipmentevent',
            name='previous_status',
            field=models.CharField(blank=True, default='', help_text="Statut du shipment juste avant cet événement, vide si c'est le premier événement.", max_length=32),
        ),
    ]
