# Generated by Django 5.1.15 on 2026-10-04 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VersionLegale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.CharField(max_length=20, unique=True)),
                ("publiee_le", models.DateTimeField(help_text="publication ; en vigueur dès cette date")),
                ("changements", models.JSONField(blank=True, default=list, help_text="ce qui change par rapport à la version précédente")),
                ("documents", models.JSONField(default=list, help_text="DocumentLegal[] du site : cle, icone, aAccepter, fr, en")),
                ("pdf", models.JSONField(blank=True, help_text="adresse du PDF complet par document et langue (« cgu-fr »)", null=True)),
            ],
            options={
                "verbose_name": "Version des textes légaux",
                "verbose_name_plural": "Versions des textes légaux",
                "ordering": ["-publiee_le"],
            },
        ),
        migrations.CreateModel(
            name="Adresse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nom", models.CharField(help_text="« Maison », « Bureau »", max_length=60)),
                ("quartier", models.CharField(help_text="nom d'une zone exploitée (ZONES-EXPLOITEES)", max_length=80)),
                ("reperes_chiffre", models.BinaryField(help_text="repères écrits comme dans la rue, chiffrés (CAP-21)")),
                ("instructions_chiffre", models.BinaryField(blank=True, null=True)),
                ("destinataire_chiffre", models.BinaryField(blank=True, null=True)),
                ("coords_chiffre", models.BinaryField(blank=True, help_text="« lat;lon;précision » chiffré", null=True)),
                ("position", models.BooleanField(default=False, help_text="position donnée par le téléphone")),
                (
                    "creneau",
                    models.CharField(
                        blank=True, choices=[("matin", "Matin"), ("apres-midi", "Après-midi"), ("soir", "Soir")], max_length=12, null=True
                    ),
                ),
                ("photo", models.TextField(blank=True, help_text="photo de l'entrée (adresse du fichier)", null=True)),
                ("principale", models.BooleanField(default=False)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="adresses_client", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Adresse de livraison",
                "verbose_name_plural": "Adresses de livraison",
                "ordering": ["-principale", "cree_le", "id"],
            },
        ),
        migrations.CreateModel(
            name="BoutiqueClient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vendor_id", models.PositiveBigIntegerField(blank=True, help_text="vendors.VendorProfile créé en attente", null=True)),
                ("nom", models.CharField(max_length=40)),
                ("categorie", models.CharField(max_length=60)),
                ("type", models.CharField(choices=[("particulier", "Particulier"), ("entreprise", "Entreprise")], max_length=12)),
                ("code", models.CharField(help_text="« KRN-4821 » : vendeur.belivay.com/b/KRN-4821", max_length=12, unique=True)),
                (
                    "piece",
                    models.CharField(
                        choices=[("aucune", "Aucune"), ("envoyee", "Envoyée"), ("verifiee", "Vérifiée"), ("refusee", "Refusée")],
                        default="aucune",
                        max_length=10,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="boutique_client", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Boutique ouverte depuis le compte",
                "verbose_name_plural": "Boutiques ouvertes depuis le compte",
            },
        ),
        migrations.CreateModel(
            name="ChangementNumero",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ancien_masque", models.CharField(max_length=40)),
                ("ancien_operateur", models.CharField(blank=True, default="", max_length=20)),
                ("nouveau_masque", models.CharField(max_length=40)),
                ("nouveau_operateur", models.CharField(blank=True, default="", max_length=20)),
                (
                    "renouvelees",
                    models.JSONField(blank=True, default=list, help_text="commandes dont le code de retrait est renouvelé (CIN-40)"),
                ),
                ("relay_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("le", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="changements_numero", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Changement de numéro",
                "verbose_name_plural": "Changements de numéro",
                "ordering": ["-le"],
            },
        ),
        migrations.CreateModel(
            name="ConsentementLegal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("doc", models.CharField(max_length=40)),
                ("version", models.CharField(max_length=20)),
                ("le", models.DateTimeField(auto_now_add=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("appareil", models.CharField(blank=True, default="", max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="consentements_legaux", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Consentement légal",
                "verbose_name_plural": "Consentements légaux",
                "ordering": ["-le", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DemandeBusiness",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("piece", models.TextField(help_text="adresse du fichier envoyé")),
                (
                    "etat",
                    models.CharField(
                        choices=[("envoyee", "Envoyée"), ("verifiee", "Vérifiée"), ("refusee", "Refusée")], default="envoyee", max_length=10
                    ),
                ),
                ("le", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="demandes_business", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de compte Business",
                "verbose_name_plural": "Demandes de compte Business",
                "ordering": ["-le", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Recherche",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("texte", models.CharField(max_length=120)),
                ("le", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="recherches_client", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Recherche (historique)",
                "verbose_name_plural": "Recherches (historique)",
                "ordering": ["-le", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AlerteFavori",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("favorite_id", models.PositiveBigIntegerField(help_text="accounts.UserFavorite")),
                ("prix", models.BooleanField(default=False, help_text="alerte de baisse de prix")),
                ("stock", models.BooleanField(default=False, help_text="alerte de retour en stock")),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="alertes_favoris", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte sur un favori",
                "verbose_name_plural": "Alertes sur les favoris",
                "constraints": [models.UniqueConstraint(fields=("user", "favorite_id"), name="client_accounts_alerte_favori_unique")],
            },
        ),
        migrations.CreateModel(
            name="IdentiteLiee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fournisseur", models.CharField(choices=[("google", "Google"), ("apple", "Apple")], max_length=10)),
                ("sujet", models.CharField(help_text="« sub » du jeton du fournisseur", max_length=255)),
                ("email_masque", models.CharField(blank=True, default="", max_length=160)),
                ("liee_le", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="identites_liees", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Identité liée",
                "verbose_name_plural": "Identités liées",
                "constraints": [
                    models.UniqueConstraint(fields=("fournisseur", "sujet"), name="client_accounts_identite_unique"),
                    models.UniqueConstraint(fields=("user", "fournisseur"), name="client_accounts_identite_par_compte"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProduitVu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_id", models.PositiveBigIntegerField()),
                ("le", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="produits_vus_client", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit vu (historique)",
                "verbose_name_plural": "Produits vus (historique)",
                "ordering": ["-le"],
                "constraints": [models.UniqueConstraint(fields=("user", "product_id"), name="client_accounts_produit_vu_unique")],
            },
        ),
        migrations.CreateModel(
            name="ProfilClient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero_chiffre", models.BinaryField(blank=True, null=True)),
                ("numero_empreinte", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("numero_masque", models.CharField(blank=True, default="", max_length=40)),
                ("operateur", models.CharField(blank=True, default="", max_length=20)),
                ("numero_verifie_le", models.DateTimeField(blank=True, null=True)),
                ("relais_habituel_id", models.PositiveBigIntegerField(blank=True, help_text="accounts.RelayPointProfile", null=True)),
                (
                    "type_compte",
                    models.CharField(choices=[("standard", "Standard"), ("diaspora", "Diaspora")], default="standard", max_length=10),
                ),
                (
                    "devise",
                    models.CharField(choices=[("XAF", "Franc CFA"), ("EUR", "Euro"), ("USD", "Dollar")], default="XAF", max_length=3),
                ),
                ("langue", models.CharField(default="fr", max_length=5)),
                ("alerte_connexion", models.BooleanField(default=True, help_text="message au numéro vérifié à chaque nouvel appareil")),
                ("personnalisation", models.BooleanField(default=True, help_text="suggestions selon ce que le client regarde et achète")),
                (
                    "nom_retrait",
                    models.CharField(blank=True, help_text="nom donné au comptoir à la place du nom complet", max_length=60, null=True),
                ),
                (
                    "photo",
                    models.TextField(blank=True, help_text="photo de profil choisie (DP-52) : adresse ou data URL rognée", null=True),
                ),
                ("interets", models.JSONField(blank=True, default=list, help_text="univers choisis à l'arrivée")),
                ("cgu_version", models.CharField(blank=True, default="", max_length=20)),
                ("cgu_acceptee_le", models.DateTimeField(blank=True, null=True)),
                ("email_modifie_le", models.DateTimeField(blank=True, null=True)),
                ("supprime_le", models.DateTimeField(blank=True, help_text="compte supprimé et pseudonymisé", null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="profil_client", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil client",
                "verbose_name_plural": "Profils clients",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("numero_verifie_le__isnull", False)),
                        fields=("numero_empreinte",),
                        name="client_accounts_numero_verifie_unique",
                    )
                ],
            },
        ),
    ]
