# Generated by Django 5.1.15 on 2026-10-05 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvoiRecu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("liste", "liste"),
                            ("cagnotte", "cagnotte"),
                            ("cotisation", "cotisation"),
                            ("panier", "panier"),
                            ("lien-paiement", "lien-paiement"),
                            ("demande-diaspora", "demande-diaspora"),
                            ("rentree", "rentree"),
                            ("colis", "colis"),
                            ("lien-famille", "lien-famille"),
                            ("abonnement", "abonnement"),
                            ("panier-famille", "panier-famille"),
                            ("code-retrait", "code-retrait"),
                            ("parrainage", "parrainage"),
                            ("partage", "partage"),
                        ],
                        max_length=20,
                    ),
                ),
                ("de_prenom", models.CharField(max_length=80)),
                ("depuis", models.CharField(blank=True, default="", help_text="pays de l'envoyeur s'il vit à l'étranger", max_length=60)),
                ("pour_prenom", models.CharField(max_length=80)),
                ("a_chiffre", models.BinaryField(help_text="numéro ou e-mail visé, chiffré (CAP-21)")),
                ("a_empreinte", models.CharField(db_index=True, max_length=64)),
                ("titre", models.CharField(max_length=200)),
                ("occasion", models.CharField(blank=True, default="", max_length=20)),
                ("hotes", models.JSONField(blank=True, default=list)),
                ("date", models.DateTimeField(blank=True, help_text="jour de l'événement, de la remise", null=True)),
                ("lieu", models.CharField(blank=True, default="", help_text="relais de remise (jamais une adresse)", max_length=160)),
                ("mot", models.CharField(blank=True, default="", max_length=280)),
                ("jusqua", models.DateTimeField(blank=True, null=True)),
                ("lignes", models.JSONField(blank=True, default=list, help_text="LigneEnvoi[] : prix relus dans le catalogue à l'envoi")),
                ("frais", models.PositiveIntegerField(default=0)),
                ("qui", models.CharField(blank=True, default="", help_text="payeur | destinataire ; vide : au choix", max_length=12)),
                ("objectif", models.PositiveIntegerField(blank=True, null=True)),
                ("reuni", models.PositiveIntegerField(default=0)),
                ("cagnotte", models.JSONField(blank=True, null=True)),
                ("code", models.CharField(blank=True, default="", help_text="code public (liste, cotisation, invitation…)", max_length=40)),
                ("ref", models.CharField(blank=True, default="", help_text="la commande liée", max_length=40)),
                ("detail", models.CharField(blank=True, default="", max_length=200)),
                ("lien", models.CharField(blank=True, default="", max_length=200)),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("a_traiter", "À traiter"),
                            ("accepte", "Accepté"),
                            ("fait", "Fait"),
                            ("refuse", "Refusé"),
                            ("expire", "Expiré"),
                        ],
                        default="a_traiter",
                        max_length=10,
                    ),
                ),
                ("actions", models.JSONField(blank=True, default=list, help_text="ActionEnvoi[]")),
                ("merci", models.JSONField(blank=True, null=True)),
                ("le", models.DateTimeField(auto_now_add=True)),
                (
                    "de",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="envois_faits", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "pour",
                    models.ForeignKey(
                        blank=True,
                        help_text="vide : sans compte",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="envois_recus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Envoi entre clients",
                "verbose_name_plural": "Envois entre clients (Reçus)",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["pour", "etat"], name="recus_envoi_pour_id_b672c1_idx"),
                    models.Index(fields=["de", "-id"], name="recus_envoi_de_id_f4d776_idx"),
                ],
            },
        ),
    ]
