# Generated by Django 5.1.15 on 2026-08-08 20:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_financial_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=120, verbose_name='Libelle')),
                ('account_type', models.CharField(choices=[('ASSET', 'Actif'), ('LIABILITY', 'Passif'), ('REVENUE', 'Produit'), ('EXPENSE', 'Charge'), ('SUSPENSE', 'Attente')], max_length=12)),
                ('normal_side', models.CharField(choices=[('DEBIT', 'Debiteur'), ('CREDIT', 'Crediteur')], max_length=6)),
                ('psp_family', models.CharField(choices=[('NONE', 'Non applicable'), ('DERIVABLE', 'Derivable de nos evenements'), ('PROVIDER', 'Dependant du prestataire')], default='NONE', help_text="PROVIDER = reconciliable seulement si le prestataire expose l'information.", max_length=12, verbose_name='Famille PSP')),
                ('operator', models.CharField(blank=True, default='', max_length=20)),
                ('is_auxiliary', models.BooleanField(default=False, help_text='Ventile par beneficiaire via le champ payee_code des ecritures.', verbose_name='Compte auxiliaire')),
                ('is_reserved', models.BooleanField(default=False, help_text='Declare mais sans mouvement autorise en Phase 1.', verbose_name='Reserve')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compte comptable',
                'verbose_name_plural': 'Plan comptable',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('seq', models.BigAutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=48, unique=True)),
                ('kind', models.CharField(choices=[('OPENING', 'A-nouveau'), ('COLLECT', 'Encaissement'), ('ESCROW_RELEASE', 'Liberation de sequestre'), ('PAYOUT', 'Versement'), ('REFUND', 'Remboursement'), ('ADJUSTMENT', 'Ajustement'), ('RECONCILIATION', 'Reconciliation'), ('REVERSAL', 'Contre-passation')], max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, default='')),
                ('source_type', models.CharField(blank=True, default='', help_text='PaymentIntent, SettlementBatch, Adjustment…', max_length=40)),
                ('source_ref', models.CharField(blank=True, default='', max_length=64)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', help_text='Permet de reconstituer une transaction de bout en bout.', max_length=64)),
                ('previous_hash', models.CharField(blank=True, default='', editable=False, max_length=64)),
                ('entry_hash', models.CharField(blank=True, default='', editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_label', models.CharField(blank=True, default='', help_text="Acteur ou tache a l'origine de l'ecriture.", max_length=80)),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='payments.ledgertransaction', verbose_name='Contre-passe la transaction')),
            ],
            options={
                'verbose_name': 'Transaction comptable',
                'verbose_name_plural': 'Transactions comptables',
                'ordering': ['-seq'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('amount_xaf', models.PositiveBigIntegerField(help_text='Toujours strictement positif. Le sens est porte par direction.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Montant (FCFA)')),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('payee_code', models.CharField(blank=True, db_index=True, default='', help_text='Obligatoire sur un compte auxiliaire. Donne le solde individuel.', max_length=40, verbose_name='Beneficiaire')),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='payments.ledgeraccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='payments.ledgertransaction')),
            ],
            options={
                'verbose_name': 'Ecriture comptable',
                'verbose_name_plural': 'Ecritures comptables',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['source_type', 'source_ref'], name='payments_le_source__0bd42d_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['kind', 'occurred_at'], name='payments_le_kind_fa3093_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', 'payee_code'], name='payments_le_account_1ab10d_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount_xaf__gt', 0)), name='ledger_entry_amount_positive'),
        ),
    ]
