# Generated by Django 5.1.15 on 2026-08-08 21:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delivery_capacity_vehicle'),
        ('payments', '0004_ledger_db_guards'),
        ('vendors', '0007_systemlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayeeAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payee_code', models.CharField(editable=False, help_text='Identite stable a vie. Ex : PAY-VND-000341.', max_length=40, unique=True, verbose_name='Code beneficiaire')),
                ('payee_type', models.CharField(choices=[('VENDOR', 'Vendeur'), ('DELIVERY_COMPANY', 'Entreprise de livraison'), ('RELAY_POINT', 'Point relais'), ('PLATFORM', 'Plateforme BelivaY'), ('BUYER', 'Acheteur'), ('COURIER', 'Livreur independant (reserve)')], max_length=20)),
                ('display_label', models.CharField(help_text="Libelle neutre pour l'administration financiere.", max_length=140, verbose_name='Libelle')),
                ('kyc_status', models.CharField(choices=[('PENDING', 'En attente'), ('VERIFIED', 'Verifie'), ('REJECTED', 'Rejete'), ('SUSPENDED', 'Suspendu')], default='PENDING', max_length=12)),
                ('kyc_verified_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_note', models.TextField(blank=True, default='')),
                ('payout_hold', models.BooleanField(default=False, help_text="Reserve aux cas graves : fraude, KYC, litige majeur. Une petite creance s'impute sur le prochain reglement, elle ne gele pas tout.", verbose_name='Versements geles')),
                ('payout_hold_reason', models.TextField(blank=True, default='')),
                ('payout_hold_at', models.DateTimeField(blank=True, null=True)),
                ('momo_operator', models.CharField(blank=True, choices=[('MTN', 'MTN Mobile Money'), ('ORANGE', 'Orange Money')], default='', max_length=10)),
                ('momo_number_enc', models.BinaryField(blank=True, null=True, verbose_name='Numero chiffre')),
                ('momo_number_masked', models.CharField(blank=True, default='', editable=False, max_length=32, verbose_name='Numero masque')),
                ('momo_fingerprint', models.CharField(blank=True, db_index=True, default='', editable=False, help_text="Detecte qu'un meme numero sert plusieurs beneficiaires — signal de mule financiere — sans stocker le numero en clair.", max_length=64, verbose_name='Empreinte du numero')),
                ('momo_changed_at', models.DateTimeField(blank=True, help_text='Declenche la periode de refroidissement avant tout versement.', null=True, verbose_name='Dernier changement de numero')),
                ('settlement_cycle_key', models.SlugField(blank=True, default='', help_text="config_key d'un SettlementCycle. Chaine et non cle etrangere : le cycle est versionne, la reference doit survivre aux versions.", max_length=120, verbose_name='Cycle de reglement')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kyc_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payout_hold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beneficiaire (compte financier)',
                'verbose_name_plural': 'Beneficiaires (comptes financiers)',
                'ordering': ['payee_type', 'payee_code'],
            },
        ),
        migrations.CreateModel(
            name='PayeeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_platform', models.BooleanField(default=False, help_text='Compte de la plateforme elle-meme — sans entite metier.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payee_link', to='accounts.deliveryorganizationprofile')),
                ('payee_account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='link', to='payments.payeeaccount')),
                ('relay_point', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payee_link', to='accounts.relaypointprofile')),
                ('user', models.OneToOneField(blank=True, help_text='Pour un acheteur (remboursements).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payee_link', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payee_link', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'Rattachement beneficiaire',
                'verbose_name_plural': 'Rattachements beneficiaires',
            },
        ),
        migrations.CreateModel(
            name='PayeeMomoChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_masked', models.CharField(blank=True, default='', max_length=32)),
                ('new_masked', models.CharField(max_length=32)),
                ('previous_operator', models.CharField(blank=True, default='', max_length=10)),
                ('new_operator', models.CharField(max_length=10)),
                ('previous_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('new_fingerprint', models.CharField(max_length=64)),
                ('reason', models.TextField(blank=True, default='')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='momo_changes', to='payments.payeeaccount')),
            ],
            options={
                'verbose_name': 'Changement de numero Mobile Money',
                'verbose_name_plural': 'Changements de numero Mobile Money',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payeeaccount',
            index=models.Index(fields=['payee_type', 'kyc_status'], name='payments_pa_payee_t_1b024f_idx'),
        ),
        migrations.AddIndex(
            model_name='payeeaccount',
            index=models.Index(fields=['payout_hold'], name='payments_pa_payout__c87001_idx'),
        ),
        migrations.AddConstraint(
            model_name='payeelink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('delivery_company__isnull', True), ('is_platform', False), ('relay_point__isnull', True), ('user__isnull', True), ('vendor__isnull', False)), models.Q(('delivery_company__isnull', False), ('is_platform', False), ('relay_point__isnull', True), ('user__isnull', True), ('vendor__isnull', True)), models.Q(('delivery_company__isnull', True), ('is_platform', False), ('relay_point__isnull', False), ('user__isnull', True), ('vendor__isnull', True)), models.Q(('delivery_company__isnull', True), ('is_platform', False), ('relay_point__isnull', True), ('user__isnull', False), ('vendor__isnull', True)), models.Q(('delivery_company__isnull', True), ('is_platform', True), ('relay_point__isnull', True), ('user__isnull', True), ('vendor__isnull', True)), _connector='OR'), name='payee_link_exactly_one_subject', violation_error_message='Un rattachement doit designer EXACTEMENT une entite metier (vendeur, entreprise, point relais, utilisateur) ou etre marque comme plateforme.'),
        ),
    ]
