# Generated by Django 5.1.15 on 2026-08-08 21:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_merge_20260707_2030'),
        ('payments', '0005_payees_bridge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=40, unique=True)),
                ('idempotency_key', models.CharField(help_text='Fournie par le client. Empeche le double encaissement.', max_length=120, unique=True, verbose_name="Cle d'idempotence")),
                ('payer_relationship', models.CharField(choices=[('SELF', "L'acheteur paie lui-meme"), ('THIRD_PARTY', 'Un tiers paie')], default='SELF', max_length=12)),
                ('payer_msisdn_enc', models.BinaryField(blank=True, null=True)),
                ('payer_msisdn_masked', models.CharField(blank=True, default='', max_length=32)),
                ('payer_msisdn_fingerprint', models.CharField(blank=True, db_index=True, default='', editable=False, help_text='Detecte un meme numero payant pour un nombre anormal de comptes.', max_length=64)),
                ('payer_operator', models.CharField(blank=True, default='', max_length=10)),
                ('payer_first_seen_at', models.DateTimeField(blank=True, help_text='Premiere utilisation de ce numero sur ce compte acheteur.', null=True)),
                ('refund_target', models.CharField(choices=[('ORIGINAL_SOURCE', "Source de paiement d'origine"), ('BUYER_ACCOUNT', "Compte de l'acheteur (derogation)")], default='ORIGINAL_SOURCE', help_text="Rembourser ailleurs que vers la source d'origine cree un transfert de valeur non consenti. Derogation a justifier.", max_length=20)),
                ('amount_xaf', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('amount_captured_xaf', models.PositiveBigIntegerField(default=0)),
                ('amount_refunded_xaf', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('REQUIRES_ACTION', 'Action acheteur attendue'), ('PROCESSING', 'En cours de traitement'), ('SUCCEEDED', 'Encaisse'), ('FAILED', 'Echoue'), ('EXPIRED', 'Expire'), ('CANCELLED', 'Annule'), ('PARTIALLY_REFUNDED', 'Partiellement rembourse'), ('REFUNDED', 'Rembourse')], default='DRAFT', max_length=20)),
                ('provider_code', models.CharField(blank=True, default='', max_length=30)),
                ('config_snapshot', models.JSONField(blank=True, default=dict, help_text="Regles resolues au moment de la creation. Une modification ulterieure en administration n'affecte JAMAIS cette intention.")),
                ('distribution_plan', models.JSONField(blank=True, default=dict, help_text='Plan de repartition fige. Materialise en sequestres au Lot 7.')),
                ('resolution_trace', models.JSONField(blank=True, default=dict, help_text='Quelle regle a gagne, pourquoi les autres ont ete ecartees.')),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intention de paiement',
                'verbose_name_plural': 'Intentions de paiement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_reference', models.CharField(editable=False, help_text="NOTRE cle d'idempotence, envoyee au prestataire.", max_length=80, unique=True, verbose_name='Reference externe')),
                ('provider_code', models.CharField(max_length=30)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', help_text='Identifiant attribue par le prestataire.', max_length=120)),
                ('status', models.CharField(choices=[('INITIATED', 'Emise'), ('PENDING', 'En attente de confirmation'), ('SUCCESSFUL', 'Reussie'), ('FAILED', 'Echouee'), ('TIMEOUT', 'Delai depasse')], default='INITIATED', max_length=12)),
                ('provider_status_raw', models.CharField(blank=True, default='', help_text='Statut brut du prestataire, non traduit.', max_length=60)),
                ('error_code', models.CharField(blank=True, default='', max_length=30)),
                ('error_message', models.TextField(blank=True, default='')),
                ('amount_xaf', models.PositiveBigIntegerField()),
                ('payer_msisdn_masked', models.CharField(blank=True, default='', max_length=32)),
                ('payer_operator', models.CharField(blank=True, default='', max_length=10)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('poll_count', models.PositiveIntegerField(default=0)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, help_text='Horodatage de la confirmation VERIFIEE aupres du prestataire.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='payments.paymentintent')),
            ],
            options={
                'verbose_name': 'Tentative de paiement',
                'verbose_name_plural': 'Tentatives de paiement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentIntentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_links', to='payments.paymentintent')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intent_links', to='orders.order')),
            ],
            options={
                'verbose_name': 'Commande couverte par une intention',
                'verbose_name_plural': 'Commandes couvertes par une intention',
            },
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_79eeea_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['buyer', 'status'], name='payments_pa_buyer_i_d26b32_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['status', 'last_polled_at'], name='payments_pa_status_402610_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['provider_code', 'provider_reference'], name='payments_pa_provide_9d673e_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentintentorder',
            constraint=models.UniqueConstraint(fields=('intent', 'order'), name='unique_intent_order'),
        ),
    ]
