# Generated by Django 5.1.15 on 2026-08-08 23:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_intents'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_code', models.CharField(db_index=True, max_length=30)),
                ('http_method', models.CharField(default='POST', max_length=10)),
                ('raw_body', models.TextField(blank=True, default='', help_text='Corps brut, NON parse. Ecrit avant toute analyse.')),
                ('raw_query', models.TextField(blank=True, default='', help_text='Chaine de requete brute. CamPay livre le callback en GET.')),
                ('raw_headers', models.JSONField(blank=True, default=dict)),
                ('source_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('body_sha256', models.CharField(db_index=True, editable=False, help_text="Empreinte du contenu. Base de l'anti-rejeu.", max_length=64)),
                ('signature_state', models.CharField(choices=[('VALID', 'Verifiee'), ('INVALID', 'Invalide'), ('UNVERIFIABLE', 'Non verifiable')], default='UNVERIFIABLE', max_length=14)),
                ('signature_reason', models.TextField(blank=True, default='')),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('external_reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('reported_status', models.CharField(blank=True, default='', max_length=40)),
                ('endpoint', models.CharField(blank=True, default='', help_text="collect | withdraw — indique de quel flux vient l'evenement.", max_length=20)),
                ('status', models.CharField(choices=[('RECEIVED', 'Recu'), ('VERIFIED', 'Verifie aupres du prestataire'), ('PROCESSED', 'Traite'), ('IGNORED', 'Ignore (doublon ou hors perimetre)'), ('REJECTED', 'Rejete'), ('ERROR', 'Erreur de traitement')], default='RECEIVED', max_length=12)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('processing_note', models.TextField(blank=True, default='')),
                ('verified_status', models.CharField(blank=True, default='', max_length=40)),
                ('verified_payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Webhook recu',
                'verbose_name_plural': 'Webhooks recus',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['provider_code', 'status'], name='payments_we_provide_e8c63d_idx'), models.Index(fields=['received_at'], name='payments_we_receive_d7f31e_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookReplayGuard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_sha256', models.CharField(max_length=64, unique=True)),
                ('provider_code', models.CharField(max_length=30)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('hit_count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Empreinte anti-rejeu',
                'verbose_name_plural': 'Empreintes anti-rejeu',
                'indexes': [models.Index(fields=['first_seen_at'], name='payments_we_first_s_1cb3eb_idx')],
            },
        ),
    ]
