# Generated by Django 5.1.15 on 2026-08-09 08:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_webhooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(help_text="Identifiant fourni par l'emetteur. Garantit l'idempotence.", max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('BUYER_RECEIPT_CONFIRMED', "Reception confirmee par l'acheteur"), ('AUTO_CONFIRMED', 'Confirmation automatique'), ('DELIVERY_PROOF_VALIDATED', 'Preuve de livraison validee'), ('RELAY_HANDOVER_SCANNED', 'Remise scannee'), ('DISPUTE_OPENED', 'Litige ouvert'), ('DISPUTE_RESOLVED', 'Litige resolu'), ('ORDER_CANCELLED', 'Commande annulee'), ('ADMIN_OVERRIDE', 'Intervention administrative')], max_length=30)),
                ('emitter', models.CharField(blank=True, default='', help_text='Domaine emetteur : apps.orders, apps.shipping, relais…', max_length=60)),
                ('order_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('intent_reference', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('component', models.CharField(blank=True, default='', max_length=20)),
                ('payee_code', models.CharField(blank=True, default='', max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('outcome', models.CharField(choices=[('APPLIED', 'Applique'), ('IGNORED', 'Ignore (doublon ou hors perimetre)'), ('REJECTED', 'Rejete'), ('ERROR', 'Erreur')], default='APPLIED', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('affected_holds', models.PositiveIntegerField(default=0)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evenement metier consomme',
                'verbose_name_plural': 'Evenements metier consommes',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['kind', 'received_at'], name='payments_es_kind_bf7f03_idx'), models.Index(fields=['outcome'], name='payments_es_outcome_2bb027_idx')],
            },
        ),
        migrations.CreateModel(
            name='EscrowHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=48, unique=True)),
                ('order_id', models.PositiveIntegerField(blank=True, db_index=True, help_text="Entier et NON cle etrangere : le domaine financier ne depend d'aucune autre application. Nul pour TRANSPORT, qui est de niveau paiement.", null=True, verbose_name='Commande')),
                ('component', models.CharField(choices=[('GOODS', 'Marchandise'), ('TRANSPORT', 'Transport'), ('RELAY_HANDLING', 'Remise en point relais')], max_length=20)),
                ('gross_amount_xaf', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('commission_xaf', models.PositiveBigIntegerField(default=0)),
                ('net_amount_xaf', models.PositiveBigIntegerField()),
                ('refunded_amount_xaf', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'En attente de paiement'), ('HELD', 'Sous sequestre'), ('RELEASE_SCHEDULED', 'Liberation programmee'), ('RELEASED', 'Libere'), ('FROZEN', 'Gele (litige)'), ('REFUNDED', 'Rembourse'), ('PARTIALLY_REFUNDED', 'Partiellement rembourse'), ('CANCELLED', 'Annule')], default='PENDING', max_length=20)),
                ('release_trigger', models.CharField(choices=[('BUYER_RECEIPT_CONFIRMED', 'Reception confirmee'), ('AUTO_CONFIRMED', 'Confirmation automatique'), ('DELIVERY_PROOF_VALIDATED', 'Preuve de livraison validee'), ('RELAY_HANDOVER_SCANNED', 'Remise scannee')], max_length=30)),
                ('auto_confirm_at', models.DateTimeField(blank=True, help_text='Echeance de confirmation automatique sans litige.', null=True)),
                ('release_at', models.DateTimeField(blank=True, help_text='Echeance de liberation effective apres confirmation.', null=True)),
                ('dispute_window_ends_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('frozen_reason', models.TextField(blank=True, default='')),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('policy_snapshot', models.JSONField(blank=True, default=dict)),
                ('settlement_batch_ref', models.CharField(blank=True, db_index=True, default='', help_text='Lot de reglement qui a couvert ce sequestre (Lot 8).', max_length=48)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_holds', to='payments.paymentintent')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_holds', to='payments.payeeaccount')),
            ],
            options={
                'verbose_name': 'Sequestre',
                'verbose_name_plural': 'Sequestres',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'release_at'], name='payments_es_status_aaf0e9_idx'), models.Index(fields=['status', 'auto_confirm_at'], name='payments_es_status_46871e_idx'), models.Index(fields=['payee', 'status'], name='payments_es_payee_i_5b5e84_idx'), models.Index(fields=['component', 'status'], name='payments_es_compone_dd3a96_idx')],
                'constraints': [models.UniqueConstraint(fields=('intent', 'order_id', 'payee', 'component'), name='unique_escrow_hold_key', nulls_distinct=False), models.CheckConstraint(condition=models.Q(('net_amount_xaf__lte', models.F('gross_amount_xaf'))), name='escrow_net_not_above_gross'), models.CheckConstraint(condition=models.Q(('refunded_amount_xaf__lte', models.F('net_amount_xaf'))), name='escrow_refund_not_above_net')],
            },
        ),
    ]
