# Generated by Django 5.1.15 on 2026-08-09 11:02

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_escrow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutpolicy',
            name='allow_exceptional_settlement',
            field=models.BooleanField(default=False, help_text='Chaque exception rapproche du modele portefeuille que le referentiel interdit pour raison reglementaire.', verbose_name='Autoriser les reglements hors cycle'),
        ),
        migrations.AddField(
            model_name='payoutpolicy',
            name='exceptional_alert_share_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text="LE garde-fou reglementaire. Le risque n'est pas UNE exception, c'est qu'elle devienne la norme : si une part importante des reglements est exceptionnelle, un regulateur verra un portefeuille quelle que soit l'etiquette.", max_digits=5, verbose_name="Seuil d'alerte sur la part d'exceptionnel (%)"),
        ),
        migrations.AddField(
            model_name='payoutpolicy',
            name='exceptional_max_amount_xaf',
            field=models.PositiveIntegerField(default=500000, verbose_name='Plafond par reglement hors cycle'),
        ),
        migrations.AddField(
            model_name='payoutpolicy',
            name='exceptional_max_per_month',
            field=models.PositiveSmallIntegerField(default=1, help_text='Au-dela, la demande est refusee automatiquement.', verbose_name='Quota mensuel par partenaire'),
        ),
        migrations.AddField(
            model_name='payoutpolicy',
            name='exceptional_max_percent_of_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='Part maximale du montant du (%)'),
        ),
        migrations.AddField(
            model_name='payoutpolicy',
            name='exceptional_required_approvals',
            field=models.PositiveSmallIntegerField(default=2, help_text='Double validation systematique, quel que soit le montant.', verbose_name='Approbations exigees (hors cycle)'),
        ),
        migrations.AddField(
            model_name='payoutpolicy',
            name='max_offset_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text="Part maximale d'un reglement pouvant etre retenue pour recouvrer une creance. A 100 %, un partenaire qui doit autant qu'on lui doit toucherait ZERO : il ne pourrait plus s'approvisionner ni livrer, et la retenue totale s'apparente juridiquement a une saisie.", max_digits=5, verbose_name='Retenue maximale (%)'),
        ),
        migrations.AddField(
            model_name='payoutpolicy',
            name='min_settlement_after_offset_xaf',
            field=models.PositiveIntegerField(default=0, help_text='Plancher absolu en valeur, cumule au plafond en pourcentage.', verbose_name='Reste minimal apres retenue (FCFA)'),
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=48, unique=True)),
                ('direction', models.CharField(choices=[('DEBIT', 'BelivaY doit au partenaire'), ('CREDIT', 'Le partenaire doit a BelivaY')], max_length=8)),
                ('category', models.CharField(choices=[('PENALTY', 'Penalite'), ('COMPENSATION', 'Compensation'), ('CORRECTION', 'Correction'), ('REBILLING', 'Refacturation'), ('GOODWILL', 'Geste commercial'), ('BONUS', 'Bonus'), ('TRUST_SCORE', 'Trust Score'), ('RETURN_COST', 'Cout de retour')], max_length=20)),
                ('amount_xaf', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('remaining_xaf', models.PositiveBigIntegerField(default=0, help_text="Reste a imputer. Une creance importante s'etale sur plusieurs reglements plutot que de vider un seul.")),
                ('reason', models.TextField(help_text='Obligatoire.', verbose_name='Motif')),
                ('evidence_url', models.URLField(blank=True, default='')),
                ('source_order_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_event', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', "En attente d'approbation"), ('APPROVED', 'Approuve'), ('APPLIED', 'Impute'), ('CANCELLED', 'Annule'), ('DISPUTED', 'Conteste')], default='PENDING_APPROVAL', max_length=20)),
                ('max_offset_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Surcharge la politique. Vide = valeur de la PayoutPolicy.', max_digits=5, null=True, verbose_name='Retenue maximale (%)')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments_created', to=settings.AUTH_USER_MODEL)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='payments.payeeaccount')),
            ],
            options={
                'verbose_name': 'Ajustement',
                'verbose_name_plural': 'Ajustements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=48, unique=True)),
                ('provider_external_reference', models.CharField(editable=False, help_text='UUID4 exige par CamPay. Jamais reutilise.', max_length=64, unique=True)),
                ('amount_xaf', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('psp_fee_xaf', models.PositiveBigIntegerField(default=0, help_text="Charge PLATEFORME. Jamais retenue au partenaire : il recoit l'integralite de son net (referentiel §7.1).")),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_APPROVAL', "En attente d'approbation"), ('APPROVED', 'Approuve'), ('PROCESSING', 'En cours'), ('PAID', 'Verse'), ('FAILED', 'Echoue'), ('UNKNOWN', 'Issue INCONNUE'), ('REJECTED', 'Rejete'), ('CANCELLED', 'Annule'), ('REVERSED', 'Contre-passe')], default='DRAFT', max_length=20)),
                ('required_approvals', models.PositiveSmallIntegerField(default=1)),
                ('provider_code', models.CharField(blank=True, default='', max_length=30)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('provider_status_raw', models.CharField(blank=True, default='', max_length=60)),
                ('error_code', models.CharField(blank=True, default='', max_length=30)),
                ('error_message', models.TextField(blank=True, default='')),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('payee_msisdn_masked', models.CharField(blank=True, default='', max_length=32)),
                ('payee_operator', models.CharField(blank=True, default='', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, default='')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_requests', to='payments.payeeaccount')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de versement',
                'verbose_name_plural': 'Demandes de versement',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_approvals', to=settings.AUTH_USER_MODEL)),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='payments.payoutrequest')),
            ],
            options={
                'verbose_name': 'Approbation de versement',
                'verbose_name_plural': 'Approbations de versement',
                'ordering': ['approved_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=48, unique=True)),
                ('amount_xaf', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reason', models.CharField(choices=[('DISPUTE', 'Litige'), ('CANCELLATION', 'Annulation'), ('ADMIN', 'Decision administrative'), ('RECONCILIATION', 'Ecart de reconciliation'), ('DUPLICATE', 'Double encaissement')], max_length=20)),
                ('detail', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', "En attente d'approbation"), ('APPROVED', 'Approuve'), ('PROCESSING', 'En cours'), ('PAID', 'Rembourse'), ('FAILED', 'Echoue'), ('UNKNOWN', 'Issue INCONNUE'), ('REJECTED', 'Rejete')], default='PENDING_APPROVAL', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds_approved', to=settings.AUTH_USER_MODEL)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.paymentintent')),
                ('payout', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='payments.payoutrequest')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds_requested', to=settings.AUTH_USER_MODEL)),
                ('source_holds', models.ManyToManyField(blank=True, related_name='refunds', to='payments.escrowhold')),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=48, unique=True)),
                ('cycle_key', models.SlugField(blank=True, default='', max_length=120)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('gross_amount_xaf', models.PositiveBigIntegerField(default=0, help_text='Somme des sequestres liberes sur la periode.')),
                ('adjustments_xaf', models.BigIntegerField(default=0, help_text='Signe : negatif si une creance a ete retenue.')),
                ('net_amount_xaf', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('CONFIRMED', 'Confirme'), ('PENDING_APPROVAL', "En attente d'approbation"), ('APPROVED', 'Approuve'), ('PROCESSING', 'En cours de versement'), ('PAID', 'Verse'), ('FAILED', 'Echoue'), ('PARTIAL', 'Partiel')], default='DRAFT', max_length=20)),
                ('is_exceptional', models.BooleanField(default=False, help_text="Derogation au cycle contractuel. Surveille : si la part d'exceptionnel devient importante, le modele s'apparente de fait a un portefeuille.", verbose_name='Reglement hors cycle')),
                ('exceptional_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_adjustments', models.ManyToManyField(blank=True, related_name='settlement_batches', to='payments.adjustment')),
                ('covered_holds', models.ManyToManyField(blank=True, related_name='settlement_batches', to='payments.escrowhold')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_batches', to='payments.payeeaccount')),
            ],
            options={
                'verbose_name': 'Lot de reglement',
                'verbose_name_plural': 'Lots de reglement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='batch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout', to='payments.settlementbatch'),
        ),
        migrations.AddIndex(
            model_name='adjustment',
            index=models.Index(fields=['payee', 'status', 'direction'], name='payments_ad_payee_i_141848_idx'),
        ),
        migrations.AddConstraint(
            model_name='adjustment',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('created_by')), _negated=True), _connector='OR'), name='adjustment_maker_is_not_checker'),
        ),
        migrations.AddConstraint(
            model_name='adjustment',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_xaf__lte', models.F('amount_xaf'))), name='adjustment_remaining_not_above_amount'),
        ),
        migrations.AddConstraint(
            model_name='payoutapproval',
            constraint=models.UniqueConstraint(fields=('payout', 'approved_by'), name='unique_payout_approval'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('requested_by')), _negated=True), _connector='OR'), name='refund_maker_is_not_checker'),
        ),
        migrations.AddIndex(
            model_name='settlementbatch',
            index=models.Index(fields=['payee', 'status'], name='payments_se_payee_i_54d09e_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementbatch',
            index=models.Index(fields=['status', 'period_end'], name='payments_se_status_3b00bc_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementbatch',
            index=models.Index(fields=['is_exceptional', 'created_at'], name='payments_se_is_exce_5b265f_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['status', 'requested_at'], name='payments_pa_status_d5f369_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['payee', 'status'], name='payments_pa_payee_i_0d4cae_idx'),
        ),
    ]
