# Generated by Django 5.1.15 on 2026-08-09 11:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_settlements'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('RUNNING', 'En cours'), ('SUCCESS', 'Terminee'), ('ERROR', 'En echec'), ('SKIPPED', 'Ignoree (verrou)')], default='RUNNING', max_length=10)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('traceback_text', models.TextField(blank=True, default='')),
                ('hostname', models.CharField(blank=True, default='', max_length=80)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Execution de tache',
                'verbose_name_plural': 'Executions de taches',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['task_name', '-started_at'], name='payments_ta_task_na_c29aca_idx'), models.Index(fields=['status', '-started_at'], name='payments_ta_status_a0f451_idx')],
            },
        ),
    ]
