# Generated by Django 5.1.15 on 2026-08-09 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_task_runs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=48, unique=True)),
                ('level', models.CharField(choices=[('SOLVENCY', 'N1 — Solvabilite'), ('ESCROW', 'N2 — Coherence du sequestre'), ('TRANSACTIONAL', 'N3 — Rapprochement transactionnel'), ('UNKNOWN_PAYOUTS', 'Resolution des versements inconnus')], max_length=20)),
                ('status', models.CharField(choices=[('RUNNING', 'En cours'), ('CLEAN', 'Aucun ecart'), ('DISCREPANCIES', 'Ecarts detectes'), ('ERROR', 'Erreur')], default='RUNNING', max_length=15)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('checked_count', models.PositiveIntegerField(default=0)),
                ('discrepancy_count', models.PositiveIntegerField(default=0)),
                ('total_gap_xaf', models.BigIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Execution de reconciliation',
                'verbose_name_plural': 'Executions de reconciliation',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['level', '-started_at'], name='payments_re_level_9340c5_idx'), models.Index(fields=['status', '-started_at'], name='payments_re_status_529036_idx')],
            },
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('INSOLVENCY', 'Insolvabilite'), ('OPERATOR_LIQUIDITY', 'Liquidite par porteur'), ('ESCROW_MISMATCH', "Ecart d'equation de sequestre"), ('MISSING_LOCALLY', 'Transaction absente chez BelivaY'), ('MISSING_AT_PROVIDER', 'Absente chez le prestataire'), ('AMOUNT_MISMATCH', 'Montant divergent'), ('STATUS_MISMATCH', 'Statut divergent'), ('FEE_MISMATCH', 'Frais divergents'), ('UNKNOWN_PAYOUT_RESOLVED', 'Versement inconnu resolu'), ('UNKNOWN_PAYOUT_PENDING', 'Versement inconnu non resolu')], max_length=30)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critique — gel requis'), ('HIGH', 'Elevee'), ('MEDIUM', 'Moyenne'), ('LOW', 'Faible'), ('INFO', 'Information')], max_length=10)),
                ('subject_type', models.CharField(blank=True, default='', max_length=40)),
                ('subject_ref', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('expected_xaf', models.BigIntegerField(default=0)),
                ('observed_xaf', models.BigIntegerField(default=0)),
                ('gap_xaf', models.BigIntegerField(default=0)),
                ('detail', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('suggested_action', models.TextField(blank=True, default='')),
                ('resolution', models.CharField(choices=[('OPEN', 'Ouvert'), ('INVESTIGATING', 'En investigation'), ('RESOLVED', 'Resolu'), ('ACCEPTED', 'Accepte (ecart connu)'), ('FALSE_POSITIVE', 'Faux positif')], default='OPEN', max_length=15)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancies', to='payments.reconciliationrun')),
            ],
            options={
                'verbose_name': 'Ecart de reconciliation',
                'verbose_name_plural': 'Ecarts de reconciliation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'resolution'], name='payments_di_kind_776e2c_idx'), models.Index(fields=['severity', 'resolution'], name='payments_di_severit_f38b92_idx')],
            },
        ),
    ]
