# Generated by Django 5.1.15 on 2026-08-09 13:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_reconciliation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('PAYMENT_INTENT', 'Intention de paiement'), ('PAYOUT_REQUEST', 'Demande de versement'), ('PAYEE', 'Beneficiaire')], max_length=20)),
                ('subject_ref', models.CharField(db_index=True, max_length=120)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('decision', models.CharField(choices=[('ALLOW', 'Autorise'), ('REVIEW', 'Revue manuelle recommandee'), ('BLOCK', 'Bloque')], default='ALLOW', max_length=8)),
                ('policy_key', models.SlugField(blank=True, default='', max_length=120)),
                ('policy_snapshot', models.JSONField(blank=True, default=dict, help_text="Seuils appliques, figes au moment de l'evaluation.")),
                ('note', models.TextField(blank=True, default='')),
                ('override_reason', models.TextField(blank=True, default='')),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluation de risque',
                'verbose_name_plural': 'Evaluations de risque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.SlugField(help_text='Identite stable a travers les versions. Ne change jamais.', max_length=120, verbose_name='Cle de configuration')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('is_active', models.BooleanField(default=True, verbose_name='Version active')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valide a partir du')),
                ('valid_until', models.DateTimeField(blank=True, help_text="Renseigne automatiquement lorsqu'une version ulterieure la remplace.", null=True, verbose_name="Valide jusqu'au")),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=140)),
                ('shared_msisdn_payee_threshold', models.PositiveSmallIntegerField(default=2, help_text='Au-dela, le numero sert plusieurs beneficiaires : signal fort.', verbose_name='Comptes beneficiaires par numero')),
                ('shared_msisdn_buyer_threshold', models.PositiveSmallIntegerField(default=5, help_text="Un numero diaspora finance legitimement plusieurs proches. Le seuil doit rester GENEREUX : c'est le volume anormal qui compte, pas le fait de payer pour autrui.", verbose_name='Acheteurs distincts par numero payeur')),
                ('shared_msisdn_window_days', models.PositiveSmallIntegerField(default=30)),
                ('velocity_intents_per_hour', models.PositiveSmallIntegerField(default=10, verbose_name='Intentions par heure et par acheteur')),
                ('velocity_failed_attempts', models.PositiveSmallIntegerField(default=5, verbose_name='Tentatives echouees consecutives')),
                ('amount_anomaly_multiplier', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text="Montant superieur a N fois la moyenne de l'acheteur.", max_digits=6, verbose_name="Multiplicateur d'anomalie de montant")),
                ('amount_review_threshold_xaf', models.PositiveIntegerField(default=500000, verbose_name='Seuil de revue manuelle (FCFA)')),
                ('momo_change_lookback_days', models.PositiveSmallIntegerField(default=7, help_text="Un changement de numero suivi de pres par une demande de versement est le scenario d'un compte compromis.")),
                ('weight_shared_msisdn', models.PositiveSmallIntegerField(default=40)),
                ('weight_velocity', models.PositiveSmallIntegerField(default=20)),
                ('weight_amount', models.PositiveSmallIntegerField(default=15)),
                ('weight_new_payer', models.PositiveSmallIntegerField(default=5, help_text='VOLONTAIREMENT FAIBLE. Un premier paiement par un tiers est le cas nominal du segment diaspora.')),
                ('weight_momo_change', models.PositiveSmallIntegerField(default=50, help_text='Calibre pour atteindre A LUI SEUL le seuil de revue. La fenetre qui compte est celle ou le refroidissement de 72 h a expire mais ou le changement reste recent : le versement redevient possible alors que le compte a peut-etre ete compromis.')),
                ('weight_failed_burst', models.PositiveSmallIntegerField(default=10)),
                ('review_score_threshold', models.PositiveSmallIntegerField(default=50, verbose_name='Score declenchant une revue')),
                ('block_score_threshold', models.PositiveSmallIntegerField(default=90, help_text='Volontairement HAUT. Un blocage automatique sur un faux positif coute un client ; le laisser passer coute une transaction.', verbose_name='Score declenchant un blocage')),
                ('auto_block_enabled', models.BooleanField(default=False, help_text="Desactive par defaut. Tant qu'il est inactif, un score eleve produit une ALERTE et non un refus.", verbose_name='Blocage automatique actif')),
                ('trust_initial_score', models.PositiveSmallIntegerField(default=70)),
                ('trust_dispute_penalty', models.PositiveSmallIntegerField(default=10)),
                ('trust_late_penalty', models.PositiveSmallIntegerField(default=5)),
                ('trust_success_bonus', models.PositiveSmallIntegerField(default=1)),
                ('trust_window_days', models.PositiveSmallIntegerField(default=90)),
                ('trust_adjustment_review_xaf', models.PositiveIntegerField(default=50000, help_text="Au-dela, un ajustement issu du Trust Score exige une validation humaine. Un bug de calcul applique en masse viderait des partenaires avant qu'on le detecte.", verbose_name="Seuil de revue d'un ajustement Trust Score (FCFA)")),
                ('priority', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cree par')),
            ],
            options={
                'verbose_name': 'Politique de risque',
                'verbose_name_plural': 'Politiques de risque',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('SHARED_MSISDN_PAYEE', 'Numero partage entre beneficiaires'), ('SHARED_MSISDN_BUYER', 'Numero payeur servant plusieurs acheteurs'), ('VELOCITY', 'Cadence anormale'), ('FAILED_BURST', "Rafale d'echecs"), ('AMOUNT_ANOMALY', 'Montant inhabituel'), ('LARGE_AMOUNT', 'Montant eleve'), ('NEW_THIRD_PARTY_PAYER', 'Nouveau payeur tiers'), ('RECENT_MOMO_CHANGE', 'Numero recemment modifie'), ('KYC_INCOMPLETE', 'KYC incomplet')], max_length=30)),
                ('severity', models.CharField(choices=[('HIGH', 'Elevee'), ('MEDIUM', 'Moyenne'), ('LOW', 'Faible'), ('INFO', 'Information')], max_length=8)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('detail', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='payments.riskassessment')),
            ],
            options={
                'verbose_name': 'Signal de risque',
                'verbose_name_plural': 'Signaux de risque',
                'ordering': ['-weight', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField()),
                ('previous_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('disputes_count', models.PositiveIntegerField(default=0)),
                ('late_count', models.PositiveIntegerField(default=0)),
                ('cancelled_count', models.PositiveIntegerField(default=0)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('policy_key', models.SlugField(blank=True, default='', max_length=120)),
                ('window_days', models.PositiveSmallIntegerField(default=90)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trust_scores', to='payments.payeeaccount')),
            ],
            options={
                'verbose_name': 'Score de confiance',
                'verbose_name_plural': 'Scores de confiance',
                'ordering': ['-computed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['subject_type', 'subject_ref'], name='payments_ri_subject_f8b3d9_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['decision', '-created_at'], name='payments_ri_decisio_614f53_idx'),
        ),
        migrations.AddIndex(
            model_name='risksignal',
            index=models.Index(fields=['kind', 'created_at'], name='payments_ri_kind_f70319_idx'),
        ),
        migrations.AddIndex(
            model_name='trustscore',
            index=models.Index(fields=['payee', '-computed_at'], name='payments_tr_payee_i_8b2266_idx'),
        ),
    ]
