# Generated by Django 5.1.15 on 2026-08-11 10:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_risk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='source_contract',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Cle de la regle de remuneration qui a genere cet ajustement. Vide pour un ajustement decide par un operateur.', max_length=120, verbose_name='Contrat autorisant'),
        ),
        migrations.CreateModel(
            name='RelayCompensationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.SlugField(help_text='Identite stable a travers les versions. Ne change jamais.', max_length=120, verbose_name='Cle de configuration')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('is_active', models.BooleanField(default=True, verbose_name='Version active')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valide a partir du')),
                ('valid_until', models.DateTimeField(blank=True, help_text="Renseigne automatiquement lorsqu'une version ulterieure la remplace.", null=True, verbose_name="Valide jusqu'au")),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=140)),
                ('payee_code', models.CharField(blank=True, db_index=True, default='', help_text='Code du compte financier du point relais. Laisser VIDE pour definir le tarif par defaut applique aux relais sans contrat particulier.', max_length=40, verbose_name='Point relais')),
                ('parcel_size', models.CharField(blank=True, choices=[('SMALL', 'Petit colis'), ('STANDARD', 'Colis standard'), ('LARGE', 'Gros colis'), ('BULKY', 'Encombrant')], db_index=True, default='', help_text="Laisser VIDE pour appliquer ce tarif a TOUTES les categories. Un encombrant n'occupe pas la meme place qu'un petit colis : les contrats le refletent.", max_length=20, verbose_name='Categorie de colis')),
                ('basis', models.CharField(choices=[('PER_PARCEL', 'Montant fixe par colis remis')], default='PER_PARCEL', max_length=20)),
                ('amount_xaf', models.PositiveIntegerField(help_text='Montant du au point relais pour chaque colis remis.', verbose_name='Montant (FCFA)')),
                ('is_accepted', models.BooleanField(default=True, help_text="Decocher si ce point relais REFUSE cette categorie — un local exigu ne prend pas d'encombrant. Aucune remuneration n'est alors due, et le domaine livraison peut interroger cette grille pour eviter de lui router le colis.", verbose_name='Categorie acceptee')),
                ('contract_reference', models.CharField(blank=True, default='', help_text='Piece justificative de la negociation.', max_length=120, verbose_name='Reference du contrat')),
                ('priority', models.IntegerField(default=0, help_text='Une regle nominative doit primer sur la regle par defaut.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cree par')),
            ],
            options={
                'verbose_name': 'Remuneration de point relais',
                'verbose_name_plural': 'Remunerations de points relais',
                'abstract': False,
            },
        ),
    ]
