# Generated by Django 5.1.15 on 2026-09-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_relay_compensation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowevent',
            name='kind',
            field=models.CharField(choices=[('BUYER_RECEIPT_CONFIRMED', "Reception confirmee par l'acheteur"), ('AUTO_CONFIRMED', 'Confirmation automatique'), ('DELIVERY_PROOF_VALIDATED', 'Preuve de livraison validee'), ('RELAY_HANDOVER_SCANNED', 'Remise scannee'), ('DISPUTE_OPENED', 'Litige ouvert'), ('DISPUTE_RESOLVED', 'Litige resolu'), ('RETURN_INITIATED', 'Retour initie'), ('RETURN_COMPLETED', 'Retour finalise'), ('ORDER_CANCELLED', 'Commande annulee'), ('ADMIN_OVERRIDE', 'Intervention administrative')], max_length=30),
        ),
    ]
