# Generated by Django 5.1.15 on 2026-09-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_escrowevent_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowpolicy',
            name='auto_confirm_hours',
            field=models.PositiveIntegerField(default=96, help_text='Verrouille a 4 jours (96h) depuis la remise — Addendum Decisions v1.0 §3.1.', verbose_name='Auto-confirmation (h)'),
        ),
        migrations.AlterField(
            model_name='escrowpolicy',
            name='dispute_window_days',
            field=models.PositiveIntegerField(default=4, help_text="Verrouille a 4 jours depuis la remise, cale sur l'auto-confirmation — Addendum Decisions v1.0 §4.4.", verbose_name='Fenetre de litige (jours)'),
        ),
        migrations.AlterField(
            model_name='escrowpolicy',
            name='release_delay_hours',
            field=models.PositiveIntegerField(default=72, help_text='Verrouille a J+3 (72h) depuis la cloture du droit de retour — Addendum Decisions v1.0 §3.1.', verbose_name='Delai de liberation (h)'),
        ),
    ]
