# Generated by Django 5.1.15 on 2026-09-06 12:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_alter_escrowpolicy_auto_confirm_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierIndemnityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.SlugField(help_text='Identite stable a travers les versions. Ne change jamais.', max_length=120, verbose_name='Cle de configuration')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('is_active', models.BooleanField(default=True, verbose_name='Version active')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valide a partir du')),
                ('valid_until', models.DateTimeField(blank=True, help_text="Renseigne automatiquement lorsqu'une version ulterieure la remplace.", null=True, verbose_name="Valide jusqu'au")),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Nom affiche dans les ecrans de configuration.', max_length=140)),
                ('kind', models.CharField(choices=[('COURSE_CANCELLED', 'Course annulee apres acceptation'), ('WAITING_TIME', 'Attente prolongee'), ('FAILED_DELIVERY', 'Livraison infructueuse')], help_text='La situation qui ouvre droit a cette indemnite.', max_length=24)),
                ('amount_xaf', models.PositiveIntegerField(default=0, help_text="Montant verse au livreur. C'est une charge BelivaY, pas une part du paiement acheteur.")),
                ('contract_reference', models.CharField(blank=True, default='', help_text='La reference du contrat qui autorise cette indemnite.', max_length=80)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cree par')),
            ],
            options={
                'verbose_name': 'Indemnite livreur',
                'verbose_name_plural': 'Indemnites livreur',
                'ordering': ['kind'],
                'constraints': [models.UniqueConstraint(fields=('config_key', 'version'), name='unique_courier_indemnity_version')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.SlugField(help_text='Identite stable a travers les versions. Ne change jamais.', max_length=120, verbose_name='Cle de configuration')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('is_active', models.BooleanField(default=True, verbose_name='Version active')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valide a partir du')),
                ('valid_until', models.DateTimeField(blank=True, help_text="Renseigne automatiquement lorsqu'une version ulterieure la remplace.", null=True, verbose_name="Valide jusqu'au")),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Nom affiche dans les ecrans de configuration.', max_length=120)),
                ('delivery_mode', models.CharField(choices=[('PICKUP', 'Retrait en point relais'), ('DELIVERY', 'Livraison a domicile')], help_text="Le mode de livraison auquel ce bareme s'applique.", max_length=12)),
                ('base_xaf', models.PositiveIntegerField(default=0, help_text='Frais de base, couvrant le premier vendeur du panier.')),
                ('extra_vendor_same_zone_xaf', models.PositiveIntegerField(default=0, help_text='Supplement par vendeur supplementaire situe dans la meme zone que les precedents.')),
                ('extra_vendor_other_zone_xaf', models.PositiveIntegerField(default=0, help_text='Supplement par vendeur supplementaire situe dans une zone differente.')),
                ('apply_zone_surcharge', models.BooleanField(default=True, help_text='Ajoute la majoration portee par la zone de destination quand elle est eloignee.')),
                ('filter_city', models.CharField(blank=True, default='', help_text="Ne s'applique qu'a cette ville. Vide = toutes.", max_length=80)),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text="Plus le nombre est bas, plus la regle s'applique tot.")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cree par')),
            ],
            options={
                'verbose_name': 'Tarif de livraison',
                'verbose_name_plural': 'Tarifs de livraison',
                'ordering': ['priority', 'delivery_mode'],
                'constraints': [models.UniqueConstraint(fields=('config_key', 'version'), name='unique_delivery_pricing_version')],
            },
        ),
    ]
