# Generated by Django 5.1.15 on 2026-10-04 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appareil",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(choices=[("webpush", "Web Push"), ("fcm", "Firebase (application)")], max_length=10)),
                ("endpoint", models.TextField(help_text="adresse Web Push, ou jeton FCM")),
                (
                    "endpoint_empreinte",
                    models.CharField(db_index=True, help_text="sha256 de l'adresse : identifiant stable", max_length=64),
                ),
                ("cles", models.JSONField(blank=True, default=dict, help_text="p256dh et auth (Web Push)")),
                ("expire_le", models.DateTimeField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("revoque_le", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="appareils_push", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Appareil (push)",
                "verbose_name_plural": "Appareils (push)",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="ConsentementCanal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("canal", models.CharField(choices=[("sms", "SMS"), ("whatsapp", "WhatsApp")], max_length=10)),
                ("le", models.DateTimeField(auto_now_add=True)),
                ("retire_le", models.DateTimeField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("appareil", models.CharField(blank=True, default="", max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="consentements_canal", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Consentement à un canal",
                "verbose_name_plural": "Consentements aux canaux",
                "ordering": ["-le", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ReglagesNotifications",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("messages", models.BooleanField(default=True)),
                ("suivi", models.BooleanField(default=True)),
                ("promotions", models.BooleanField(default=True)),
                ("flash", models.BooleanField(default=False, help_text="alerte des ventes flash (FF-FLASH)")),
                ("canal", models.CharField(choices=[("sms", "SMS"), ("whatsapp", "WhatsApp")], default="sms", max_length=10)),
                ("calme_actif", models.BooleanField(default=False)),
                ("calme_debut", models.PositiveSmallIntegerField(default=22, help_text="heure de début (0 à 23, heure de Yaoundé)")),
                ("calme_fin", models.PositiveSmallIntegerField(default=7, help_text="heure de fin (0 à 23, heure de Yaoundé)")),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reglages_notifications", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Réglages des notifications",
                "verbose_name_plural": "Réglages des notifications",
            },
        ),
        migrations.CreateModel(
            name="JournalNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(max_length=20)),
                ("titre", models.CharField(max_length=160)),
                ("critique", models.BooleanField(default=False)),
                ("centre", models.BooleanField(default=False, help_text="écrite dans le centre de notifications")),
                ("pousses", models.PositiveSmallIntegerField(default=0, help_text="appareils atteints par push")),
                ("sms", models.CharField(blank=True, default="", help_text="canal de repli utilisé", max_length=10)),
                (
                    "raison",
                    models.CharField(blank=True, default="", help_text="pourquoi pas de push (choix, calme, limite)", max_length=60),
                ),
                ("le", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="journal_notifications", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification envoyée",
                "verbose_name_plural": "Notifications envoyées",
                "ordering": ["-le", "-id"],
                "indexes": [models.Index(fields=["user", "type", "le"], name="notificatio_user_id_330854_idx")],
            },
        ),
    ]
