# Generated by Django 5.1.15 on 2026-10-05 07:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarteConfiance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
                ("lien", models.CharField(max_length=200)),
                ("icone", models.CharField(help_text="nom d'icône Lucide : shield-check, map-pin, rotate-ccw…", max_length=40)),
                ("ton", models.CharField(blank=True, choices=[("", "neutre"), ("o", "or")], default="", max_length=2)),
                ("titre", models.CharField(max_length=80)),
                ("texte", models.TextField()),
                ("action", models.CharField(help_text="« En savoir plus »", max_length=40)),
            ],
            options={
                "verbose_name": "carte du bandeau de confiance",
                "verbose_name_plural": "bandeau de confiance",
                "ordering": ("ordre", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "fichier",
                    models.FileField(blank=True, help_text="photo téléversée (JPEG, PNG, WebP, AVIF)", upload_to="contenus/%Y/%m/"),
                ),
                ("url_externe", models.URLField(blank=True, default="", help_text="ou adresse d'une photo déjà en ligne (CDN)")),
                ("alt", models.CharField(blank=True, default="", help_text="texte alternatif (lecteurs d'écran)", max_length=200)),
                ("largeur", models.PositiveIntegerField(blank=True, null=True)),
                ("hauteur", models.PositiveIntegerField(blank=True, null=True)),
                ("variantes", models.JSONField(blank=True, default=list, help_text="[[chemin, largeur], …] : srcset")),
                ("par", models.PositiveBigIntegerField(blank=True, help_text="utilisateur (staff) qui l'a déposée", null=True)),
                ("cree_le", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "photo",
                "ordering": ("-cree_le",),
            },
        ),
        migrations.CreateModel(
            name="CategorieAccueil",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
                ("lien", models.CharField(max_length=200)),
                ("titre", models.CharField(max_length=80)),
                ("dessin", models.CharField(blank=True, default="", max_length=20)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="contenus.media"
                    ),
                ),
            ],
            options={
                "verbose_name": "catégorie mise en avant",
                "verbose_name_plural": "catégories mises en avant",
                "ordering": ("ordre", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BandeauAccueil",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
                ("lien", models.CharField(help_text="chemin du site : /liste?cat=femme&from=accueil", max_length=200)),
                ("titre", models.CharField(max_length=80)),
                ("sous", models.JSONField(blank=True, default=list, help_text='sous-catégories : ["Robes", "Pagnes & wax"]')),
                ("produits", models.CharField(blank=True, default="", help_text="nombre affiché (« 283 »)", max_length=20)),
                ("dessin", models.CharField(blank=True, default="", help_text="dessin du prototype (repli sans photo)", max_length=20)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="contenus.media"
                    ),
                ),
            ],
            options={
                "verbose_name": "bandeau du carrousel",
                "verbose_name_plural": "carrousel de l'accueil",
                "ordering": ("ordre", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PageContenu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("langue", models.CharField(default="fr", max_length=5)),
                ("titre", models.CharField(max_length=160)),
                ("corps", models.TextField(help_text="Markdown")),
                ("publie", models.BooleanField(default=True)),
                ("maj_le", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="contenus.media"
                    ),
                ),
            ],
            options={
                "verbose_name": "page de contenu",
                "verbose_name_plural": "pages de contenu",
            },
        ),
        migrations.CreateModel(
            name="ReglagesAccueil",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("flash_titre", models.CharField(default="Flash Deals", max_length=60)),
                ("flash_sous_titre", models.CharField(default="Vraie fin · vrai stock", max_length=80)),
                ("confiance_question", models.CharField(default="Pourquoi choisir", max_length=60)),
                ("confiance_marque", models.CharField(default="BelivaY", max_length=40)),
                ("maj_le", models.DateTimeField(auto_now=True)),
                (
                    "fond_arrivee",
                    models.ForeignKey(
                        blank=True,
                        help_text="photo de l'écran d'arrivée (grand écran)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenus.media",
                    ),
                ),
            ],
            options={
                "verbose_name": "réglages de l'accueil",
                "verbose_name_plural": "réglages de l'accueil",
            },
        ),
    ]
