# Generated by Django 5.1.15 on 2026-10-04 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interrupteur",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(help_text="FF-WALLET, FF-ABONNEMENT…", max_length=40, unique=True)),
                ("ouvert", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Interrupteur de module",
                "verbose_name_plural": "Interrupteurs de module",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ParametreMetier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=60, unique=True)),
                ("valeur", models.TextField(help_text="Telle qu'écrite au registre, ex. « 500 F » ; la forme est vérifiée par le moteur.")),
                ("sens", models.TextField(blank=True, default="")),
                ("categorie", models.CharField(blank=True, default="", max_length=160)),
                (
                    "gouvernance",
                    models.CharField(
                        choices=[("N2", "N2 · délais et textes (un responsable)"), ("N3", "N3 · argent (deux personnes)")],
                        default="N2",
                        max_length=2,
                    ),
                ),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètre métier",
                "verbose_name_plural": "Paramètres métier",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CleIdempotence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cle", models.CharField(max_length=120)),
                ("auteur", models.CharField(blank=True, default="", max_length=120)),
                ("methode", models.CharField(max_length=8)),
                ("chemin", models.CharField(max_length=255)),
                ("empreinte", models.CharField(help_text="sha256 du corps de la requête", max_length=64)),
                ("statut", models.PositiveSmallIntegerField(blank=True, help_text="Vide tant que l'action est en cours", null=True)),
                ("reponse", models.JSONField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Clé d'idempotence",
                "verbose_name_plural": "Clés d'idempotence",
                "indexes": [models.Index(fields=["cree_le"], name="client_core_cree_le_345d92_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("utilisateur", "auteur", "cle"), name="client_core_cle_idempotence_unique")
                ],
            },
        ),
    ]
