from django.urls import path
from .views import (
    ClientOrderMessagesView,
    CourierDisputeMessageCreateView,
    CourierDisputeListView,
    CourierDisputeReplyPermissionRequestView,
    CourierDashboardView,
    CourierNetworkView,
    CourierSettingsView,
    CourierSOSAlertView,
    CourierShipmentMessageListCreateView,
    CourierShipmentScanView,
    CourierMyShipmentsView,
    CourierShipmentActionView,
    CourierShipmentDetailView,
    CourierAvailableShipmentsView,
    CourierClaimShipmentView,
    ShipmentCreateView,
    ShipmentEventCreateView,
    ShipmentTrackView,
)

urlpatterns = [
    path("orders/<int:order_id>/messages/", ClientOrderMessagesView.as_view(), name="shipping-client-messages"),
    path("create/", ShipmentCreateView.as_view(), name="shipping-create"),
    path("events/", ShipmentEventCreateView.as_view(), name="shipping-events"),
    path("track/", ShipmentTrackView.as_view(), name="shipping-track"),
    path("dashboard/", CourierDashboardView.as_view(), name="shipping-dashboard"),
    path("network/", CourierNetworkView.as_view(), name="shipping-network"),
    path("settings/", CourierSettingsView.as_view(), name="shipping-settings"),
    path("sos/", CourierSOSAlertView.as_view(), name="shipping-sos"),
    path("disputes/", CourierDisputeListView.as_view(), name="shipping-disputes"),
    path("disputes/<int:dispute_id>/request-reply/", CourierDisputeReplyPermissionRequestView.as_view(), name="shipping-dispute-request-reply"),
    path("disputes/<int:dispute_id>/messages/", CourierDisputeMessageCreateView.as_view(), name="shipping-dispute-message"),
    path("scan/", CourierShipmentScanView.as_view(), name="shipping-scan"),
    path("my-shipments/", CourierMyShipmentsView.as_view(), name="shipping-my-shipments"),
    path("my-shipments/<int:id>/", CourierShipmentDetailView.as_view(), name="shipping-my-shipments-detail"),
    path("my-shipments/<int:id>/messages/", CourierShipmentMessageListCreateView.as_view(), name="shipping-my-shipments-messages"),
    path("my-shipments/<int:id>/action/", CourierShipmentActionView.as_view(), name="shipping-my-shipments-action"),
    path("available/", CourierAvailableShipmentsView.as_view(), name="shipping-available"),
    path("available/<int:id>/claim/", CourierClaimShipmentView.as_view(), name="shipping-claim"),
]
