import type { Product } from "@/services/api/products";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    title: "Casque audio Pro",
    slug: "casque-audio-pro",
    description: "Casque audio haute qualité avec réduction de bruit active.",
    price_xaf: 59000,
    discount: 10,
    price_final: 53100,
    stock_quantity: 15,
    is_active: true,
    category: { id: 1, name: "Électronique", slug: "electronique", is_active: true },
    media: [],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 2,
    title: "Sac à dos urbain",
    slug: "sac-a-dos-urbain",
    description: "Sac à dos tendance pour usage quotidien.",
    price_xaf: 25000,
    discount: 0,
    price_final: 25000,
    stock_quantity: 30,
    is_active: true,
    category: { id: 2, name: "Mode", slug: "mode", is_active: true },
    media: [],
    created_at: "2024-01-02T00:00:00Z",
    updated_at: "2024-01-02T00:00:00Z",
  },
  {
    id: 3,
    title: "Lampe minimaliste",
    slug: "lampe-minimaliste",
    description: "Lampe design pour décorer votre intérieur.",
    price_xaf: 18000,
    discount: 5,
    price_final: 17100,
    stock_quantity: 20,
    is_active: true,
    category: { id: 3, name: "Maison & Bureau", slug: "maison-bureau", is_active: true },
    media: [],
    created_at: "2024-01-03T00:00:00Z",
    updated_at: "2024-01-03T00:00:00Z",
  },
  {
    id: 4,
    title: "Montre classique",
    slug: "montre-classique",
    description: "Montre élégante pour homme et femme.",
    price_xaf: 42000,
    discount: 15,
    price_final: 35700,
    stock_quantity: 10,
    is_active: true,
    category: { id: 4, name: "Accessoires", slug: "accessoires", is_active: true },
    media: [],
    created_at: "2024-01-04T00:00:00Z",
    updated_at: "2024-01-04T00:00:00Z",
  },
  {
    id: 5,
    title: "Enceinte compacte",
    slug: "enceinte-compacte",
    description: "Enceinte Bluetooth portable avec son cristallin.",
    price_xaf: 36000,
    discount: 0,
    price_final: 36000,
    stock_quantity: 12,
    is_active: true,
    category: { id: 5, name: "Électronique", slug: "electronique", is_active: true },
    media: [],
    created_at: "2024-01-05T00:00:00Z",
    updated_at: "2024-01-05T00:00:00Z",
  },
  {
    id: 6,
    title: "Chaussures lifestyle",
    slug: "chaussures-lifestyle",
    description: "Chaussures confortables pour tous les jours.",
    price_xaf: 31000,
    discount: 0,
    price_final: 31000,
    stock_quantity: 25,
    is_active: true,
    category: { id: 2, name: "Mode", slug: "mode", is_active: true },
    media: [],
    created_at: "2024-01-06T00:00:00Z",
    updated_at: "2024-01-06T00:00:00Z",
  },
  {
    id: 7,
    title: "Mug céramique",
    slug: "mug-ceramique",
    description: "Mug artisanal en céramique fait main.",
    price_xaf: 6000,
    discount: 0,
    price_final: 6000,
    stock_quantity: 50,
    is_active: true,
    category: { id: 3, name: "Maison & Bureau", slug: "maison-bureau", is_active: true },
    media: [],
    created_at: "2024-01-07T00:00:00Z",
    updated_at: "2024-01-07T00:00:00Z",
  },
  {
    id: 8,
    title: "Kit voyage premium",
    slug: "kit-voyage-premium",
    description: "Kit complet pour voyager léger et stylé.",
    price_xaf: 27000,
    discount: 20,
    price_final: 21600,
    stock_quantity: 8,
    is_active: true,
    category: { id: 4, name: "Accessoires", slug: "accessoires", is_active: true },
    media: [],
    created_at: "2024-01-08T00:00:00Z",
    updated_at: "2024-01-08T00:00:00Z",
  },
  {
    id: 9,
    title: "Ceinture cuir",
    slug: "ceinture-cuir",
    description: "Ceinture en cuir véritable pour homme.",
    price_xaf: 12000,
    discount: 0,
    price_final: 12000,
    stock_quantity: 18,
    is_active: true,
    category: { id: 4, name: "Accessoires", slug: "accessoires", is_active: true },
    media: [],
    created_at: "2024-01-09T00:00:00Z",
    updated_at: "2024-01-09T00:00:00Z",
  },
  {
    id: 10,
    title: "Lunettes de soleil",
    slug: "lunettes-de-soleil",
    description: "Lunettes polarisées protection UV400.",
    price_xaf: 15000,
    discount: 10,
    price_final: 13500,
    stock_quantity: 22,
    is_active: true,
    category: { id: 4, name: "Accessoires", slug: "accessoires", is_active: true },
    media: [],
    created_at: "2024-01-10T00:00:00Z",
    updated_at: "2024-01-10T00:00:00Z",
  },
  {
    id: 11,
    title: "Smartphone Tecno Spark",
    slug: "smartphone-tecno-spark",
    description: "Smartphone abordable avec double caméra.",
    price_xaf: 85000,
    discount: 5,
    price_final: 80750,
    stock_quantity: 7,
    is_active: true,
    category: { id: 6, name: "Téléphones & Tablettes", slug: "telephones-tablettes", is_active: true },
    media: [],
    created_at: "2024-01-11T00:00:00Z",
    updated_at: "2024-01-11T00:00:00Z",
  },
  {
    id: 12,
    title: "Robe wax imprimé",
    slug: "robe-wax-imprime",
    description: "Belle robe en tissu wax africain.",
    price_xaf: 22000,
    discount: 0,
    price_final: 22000,
    stock_quantity: 14,
    is_active: true,
    category: { id: 7, name: "Mode Femme", slug: "mode-femme", is_active: true },
    media: [],
    created_at: "2024-01-12T00:00:00Z",
    updated_at: "2024-01-12T00:00:00Z",
  },
];

export function searchMockProducts(query: string): Product[] {
  const q = query.toLowerCase().trim();
  if (!q) return MOCK_PRODUCTS;
  return MOCK_PRODUCTS.filter(
    (p) =>
      p.title.toLowerCase().includes(q) ||
      (p.category?.name.toLowerCase().includes(q) ?? false) ||
      p.description.toLowerCase().includes(q),
  );
}
