# Generated by Django 5.1.15 on 2026-10-04 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayPointProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('manager_name', models.CharField(blank=True, default='', max_length=120)),
                ('phone', models.CharField(default='', max_length=20)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('zones', models.JSONField(blank=True, default=list)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('opening_hours', models.CharField(blank=True, default='', max_length=160)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('storage_capacity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='APPROVED', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relay_point_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
